### ISSUE TITLE
motan:registry zookeeper异常（500-20008）

### ISSUE THREAD

**Issue by hexian55** [weibocom/motan#106]
配置如下：
motan:registry regProtocol="zookeeper" name="fans_server" address="127.0.0.1:3181,127.0.0.1:3182,127.0.0.1:3183"
异常栈：
Exception in thread "main" com.weibo.api.motan.exception.MotanFrameworkException: error_message: register error! Could not find extension for registry protocol:zookeeper, make sure registry module for zookeeper is in classpath!, status: 500, error_code: 20008,r=
    at com.weibo.api.motan.config.handler.SimpleConfigHandler.register(SimpleConfigHandler.java:107)
    at com.weibo.api.motan.config.handler.SimpleConfigHandler.export(SimpleConfigHandler.java:80)
    at com.weibo.api.motan.config.ServiceConfig.doExport(ServiceConfig.java:211)
    at com.weibo.api.motan.config.ServiceConfig.export(ServiceConfig.java:129)
    at com.weibo.api.motan.config.springsupport.ServiceConfigBean.onApplicationEvent(ServiceConfigBean.java:90)
    at com.weibo.api.motan.config.springsupport.ServiceConfigBean.onApplicationEvent(ServiceConfigBean.java:42)
    at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:163)
    at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:136)
    at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:381)
    at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:335)
    at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:855)
    at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:541)
    at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:139)
    at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:83)
    at com.app.miaomiao.FansServer.main.Server.main(Server.java:11)

**Comment by hexian55** [comment]
我使用的是快速入门的代码，consul测试过没有什么问题，但是zk却有问题，请大神帮忙解答一下

**Comment by qdaxb** [comment]
看一下classpath下是否有motan-registry-zookeeper包

**Comment by hexian55** [comment]
maven没有引motan-registry-zookeeper这个包导致的   感谢      另外还有一个问题帮忙解答一下
限制服务端连接池工作线程数  motan:protocol id="demoMotan" name="motan" maxWorkerThread="800" minWorkerThread="20"    我在service中，怎么设置这个protocol呢？还在只需要再server.xml里面加上这一行？

**Comment by qdaxb** [comment]
@hexian55 service的配置项里， `export="protocol:port"`

可以参考https://github.com/weibocom/motan/blob/master/motan-demo/motan-demo-server/src/main/resources/motan_demo_server.xml
