### ISSUE TITLE
zookeeper 集群问题 NettyChannel connect to server timeout

### ISSUE THREAD

**Issue by NuiStrawBerry** [weibocom/motan#125]
在使用zookeeper做集群的的时候遇到 `NettyChannel connect to server timeout` 查阅官方文档异常代码文档 提示说 “服务使用方初始化netty中，连接服务端超时，确认服务提供方是否正确提供服务”。请问如何确认所说的服务方是否正常提供服务？ 通过直连的方式能调通服务能算作确认服务方的服务正常吗？

另咨询下一般引起超时的原因会有哪些呢?
 附上配置文件内容，及异常信息。

motan_server.xml

```
 <motan:registry regProtocol="zookeeper" name="my_zookeeper" address="114.215.xxx.xxx:2181"/>
    <motan:service interface="com.blackhole.global.service.MatchService" filter="url,access" ref="matchServiceImpl" export="8002" group="match-service" registry="my_zookeeper" connectTimeout="5000"/>
```

motan_client.xml

```
<motan:registry regProtocol="zookeeper" name="my_zookeeper" address="114.215.xxx.xxx:2181" connectTimeout="50000"/>
    <motan:referer id="matchServiceImplement" interface="com.blackhole.global.service.MatchService" registry="my_zookeeper"  requestTimeout="5000" group="match-service" accessLog="true"/>
```

异常信息

```
2016-06-21 10:54:30,910 ERROR [error] - NettyClient init pool create connect Error: url=motan://10.252.31.104:8002/com.blackhole.global.service.MatchService
com.weibo.api.motan.exception.MotanServiceException: error_message: NettyChannel connect to server timeout url: motan://10.252.31.104:8002/com.blackhole.global.service.MatchService, cost: 1007, result: false, success: false, connected: false, status: 503, error_code: 10001,r=
    at com.weibo.api.motan.transport.netty.NettyChannel.open(NettyChannel.java:154)
    at com.weibo.api.motan.transport.netty.NettyChannelFactory.makeObject(NettyChannelFactory.java:53)
    at org.apache.commons.pool.impl.GenericObjectPool.addObject(GenericObjectPool.java:1666)
    at com.weibo.api.motan.transport.AbstractPoolClient.initPool(AbstractPoolClient.java:64)
    at com.weibo.api.motan.transport.netty.NettyClient.open(NettyClient.java:217)
    at com.weibo.api.motan.protocol.rpc.DefaultRpcProtocol$DefaultRpcReferer.doInit(DefaultRpcProtocol.java:196)
    at com.weibo.api.motan.rpc.AbstractNode.init(AbstractNode.java:46)
    at com.weibo.api.motan.protocol.AbstractProtocol.refer(AbstractProtocol.java:100)
    at com.weibo.api.motan.protocol.support.ProtocolFilterDecorator.refer(ProtocolFilterDecorator.java:70)
    at com.weibo.api.motan.cluster.support.ClusterSupport.notify(ClusterSupport.java:175)
    at com.weibo.api.motan.registry.support.AbstractRegistry.notify(AbstractRegistry.java:214)
    at com.weibo.api.motan.registry.zookeeper.ZookeeperRegistry.doSubscribe(ZookeeperRegistry.java:96)
    at com.weibo.api.motan.registry.support.AbstractRegistry.subscribe(AbstractRegistry.java:101)
    at com.weibo.api.motan.registry.support.FailbackRegistry.subscribe(FailbackRegistry.java:107)
    at com.weibo.api.motan.cluster.support.ClusterSupport.init(ClusterSupport.java:90)
    at com.weibo.api.motan.config.handler.SimpleConfigHandler.buildClusterSupport(SimpleConfigHandler.java:55)
    at com.weibo.api.motan.config.RefererConfig.createClusterSupport(RefererConfig.java:184)
    at com.weibo.api.motan.config.RefererConfig.initRef(RefererConfig.java:128)
    at com.weibo.api.motan.config.RefererConfig.getRef(RefererConfig.java:85)
    at com.weibo.api.motan.config.springsupport.RefererConfigBean.getObject(RefererConfigBean.java:41)
    at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.doGetObjectFromFactoryBean(FactoryBeanRegistrySupport.java:168)
    at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.getObjectFromFactoryBean(FactoryBeanRegistrySupport.java:103)
    at org.springframework.beans.factory.support.AbstractBeanFactory.getObjectForBeanInstance(AbstractBeanFactory.java:1512)
    at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:250)
    at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:198)
    at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:271)
    at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:193)
    at org.springframework.beans.factory.support.DefaultListableBeanFactory.findAutowireCandidates(DefaultListableBeanFactory.java:1017)
    at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:960)
    at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:858)
    at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:480)
    at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:87)
    at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:289)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1185)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:537)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:475)
    at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:302)
    at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:228)
    at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:298)
    at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:193)
    at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:703)
    at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:760)
    at org.springframework.context.support.AbstractApplicationContext.__refresh(AbstractApplicationContext.java:482)
    at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java)
    at org.springframework.web.servlet.FrameworkServlet.configureAndRefreshWebApplicationContext(FrameworkServlet.java:658)
    at org.springframework.web.servlet.FrameworkServlet.createWebApplicationContext(FrameworkServlet.java:624)
    at org.springframework.web.servlet.FrameworkServlet.createWebApplicationContext(FrameworkServlet.java:672)
    at org.springframework.web.servlet.FrameworkServlet.initWebApplicationContext(FrameworkServlet.java:543)
    at org.springframework.web.servlet.FrameworkServlet.initServletBean(FrameworkServlet.java:484)
    at org.springframework.web.servlet.HttpServletBean.init(HttpServletBean.java:136)
    at javax.servlet.GenericServlet.init(GenericServlet.java:158)
    at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1231)
    at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1144)
    at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:1031)
    at org.apache.catalina.core.StandardContext.loadOnStartup(StandardContext.java:4914)
    at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5201)
    at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
    at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:725)
    at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:701)
    at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717)
    at org.apache.catalina.startup.HostConfig.manageApp(HostConfig.java:1648)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.apache.tomcat.util.modeler.BaseModelMBean.invoke(BaseModelMBean.java:300)
    at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.invoke(DefaultMBeanServerInterceptor.java:819)
    at com.sun.jmx.mbeanserver.JmxMBeanServer.invoke(JmxMBeanServer.java:801)
    at org.apache.catalina.mbeans.MBeanFactory.createStandardContext(MBeanFactory.java:463)
    at org.apache.catalina.mbeans.MBeanFactory.createStandardContext(MBeanFactory.java:413)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.apache.tomcat.util.modeler.BaseModelMBean.invoke(BaseModelMBean.java:300)
    at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.invoke(DefaultMBeanServerInterceptor.java:819)
    at com.sun.jmx.mbeanserver.JmxMBeanServer.invoke(JmxMBeanServer.java:801)
    at javax.management.remote.rmi.RMIConnectionImpl.doOperation(RMIConnectionImpl.java:1466)
    at javax.management.remote.rmi.RMIConnectionImpl.access$300(RMIConnectionImpl.java:76)
    at javax.management.remote.rmi.RMIConnectionImpl$PrivilegedOperation.run(RMIConnectionImpl.java:1307)
    at javax.management.remote.rmi.RMIConnectionImpl.doPrivilegedOperation(RMIConnectionImpl.java:1399)
    at javax.management.remote.rmi.RMIConnectionImpl.invoke(RMIConnectionImpl.java:828)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:323)
    at sun.rmi.transport.Transport$1.run(Transport.java:200)
    at sun.rmi.transport.Transport$1.run(Transport.java:197)
    at java.security.AccessController.doPrivileged(Native Method)
    at sun.rmi.transport.Transport.serviceCall(Transport.java:196)
    at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:568)
    at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:826)
    at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$254(TCPTransport.java:683)
    at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler$$Lambda$8/1563902209.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:682)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
2016-06-21 10:54:31,240 WARN [warn] - NettyClient heartbeat Error: state=UNINIT url=motan://10.252.31.104:8002/com.blackhole.global.service.MatchService
2016-06-21 10:54:31,745 WARN [warn] - NettyClient heartbeat Error: state=UNINIT url=motan://10.252.31.104:8002/com.blackhole.global.service.MatchService
2016-06-21 10:54:31,926 ERROR [error] - NettyClient init pool create connect Error: url=motan://10.252.31.104:8002/com.blackhole.global.service.MatchService
com.weibo.api.motan.exception.MotanServiceException: error_me

```

**Comment by sunnights** [comment]
确认服务方是否正常提供服务可以通过motan-manager后台管理模块来查询服务
或者在zookeeper上确认相关服务节点是否存在，路径是`/motan/{group}/{service}/availableServer/`，查看该结点下是否有服务提供端的临时结点即可

**Comment by NuiStrawBerry** [comment]
是availableServer嘛？  我这边zookeeper 里面只有 server路径

```
ls  /motan/match-service/com.blackhole.global.service.MatchService

[client, server, unavailableServer]

ls /motan/match-service/com.blackhole.global.service.MatchService/server

[10.252.xxx.xxx:8002]

get /motan/match-service/com.blackhole.global.service.MatchService/server/10.252.xxx.xxx:8002

��t�motan://10.252.xxx.xxx:8002/com.blackhole.global.service.MatchService?filter=url,access&protocol=motan&refreshTimestamp=1466477115417&id=com.weibo.api.motan.config.springsupport.ServiceConfigBean&nodeType=service&export=motan:8002&group=match-service&
cZxid = 0x1d4
ctime = Tue Jun 21 10:45:43 CST 2016
mZxid = 0x1d4
mtime = Tue Jun 21 10:45:43 CST 2016
pZxid = 0x1d4
cversion = 0
dataVersion = 0
aclVersion = 0
ephemeralOwner = 0x155482975b7006b
dataLength = 257
numChildren = 0

```

我这样的 算是 服务可用的嘛？
如果是 那我上面的连接超时，会是什么原因呢？

**Comment by sunnights** [comment]
是server，
上面的连接超时是在client启动后第一次调用时发生的吗

**Comment by NuiStrawBerry** [comment]
不只是第一次。 启动的时候就有超时异常，每次调用的服务的时候都是

**Comment by rayzhang0603** [comment]
这个异常是netty链接server时超时了，请确认一下两台主机之间的网络是否正常，可以在client端ping一下10.252.31.104试试

**Comment by NuiStrawBerry** [comment]
10.252.31.104 是内网的ip地址，对应的公网地址是114.215.xxx.xxx。 网络是可以ping通的。

我是在公网调用的服务，并产生的异常。 @rayzhang0603

**Comment by rayzhang0603** [comment]
异常中motan获取到的server地址是motan://10.252.31.104:8002/com.blackhole.global.service.MatchService，如果是在公网请求，应该无法链接到10.252.21.104这个ip。建议在同网段的两台服务器进行测试。

**Comment by NuiStrawBerry** [comment]
谢谢两位， 同一网段可以的。
