### ISSUE TITLE
服务端已经启动成功，但是为什么客户端启动的时候，一直报找不到订阅消息的错误？

### ISSUE THREAD

**Issue by lijhua** [weibocom/motan#129]
服务端日志;
`2016-06-22 17:44:22.393  INFO 8072 --- [pool-3-thread-1] serviceStatsLog                          : [motan-totalAccessStatistic] app: motan module: motan total_count: 0 slow_count: 0 biz_excp: 0 other_excp: 0 avg_time: 0.00ms biz_time: 0.00ms avg_tps: 0
2016-06-22 17:44:22.396  INFO 8072 --- [pool-3-thread-1] serviceStatsLog                          : [motan-memoryStatistic] 124.68MB of 1797.50 MB (6.9%) used 
2016-06-22 17:44:22.397  INFO 8072 --- [pool-3-thread-1] serviceStatsLog                          : [motan-statisticCallback] identity: motan://192.168.20.208:8002/activeGroup/com.epai.contract.iface.ActivityService/1.0/service connectionCount: 0 taskCount: 0 queueCount: 0 maxThreadCount: 800 maxTaskCount: 800
2016-06-22 17:44:22.397  INFO 8072 --- [pool-3-thread-1] serviceStatsLog                          : [motan-statisticCallback] identity: motan://192.168.20.208:8003/dataCrawlGroup/com.epai.contract.iface.DataCrawlService/1.0/service connectionCount: 0 taskCount: 0 queueCount: 0 maxThreadCount: 800 maxTaskCount: 800
`

错误描述：
`Caused by: com.weibo.api.motan.exception.MotanFrameworkException: error_message: Failed to subscribe motan://192.168.20.208:0/com.epai.contract.iface.ActivityService?group=activeGroup to zookeeper(zookeeper://127.0.0.1:2181/com.weibo.api.motan.registry.RegistryService?group=default_rpc), cause: null, status: 503, error_code: 20001,r=
    at com.weibo.api.motan.registry.zookeeper.ZookeeperRegistry.doSubscribe(ZookeeperRegistry.java:98) ~[motan-registry-zookeeper-0.1.1.jar:na]
    at com.weibo.api.motan.registry.support.AbstractRegistry.subscribe(AbstractRegistry.java:101) ~[motan-core-0.1.1.jar:na]
    at com.weibo.api.motan.registry.support.FailbackRegistry.subscribe(FailbackRegistry.java:107) ~[motan-core-0.1.1.jar:na]
    ... 36 common frames omitted`

**Comment by sunnights** [comment]
麻烦能不能在71行打个断点，单步执行看一下具体是哪行代码抛出的异常

**Comment by lijhua** [comment]
com.weibo.api.motan.registry.zookeeper这个包下面的ZookeeperRegistry这个类的protected void doSubscribe(final URL url, final NotifyListener notifyListener) {....}方法的  this.notify(url, notifyListener, this.nodeChildsToUrls(serverTypePath, currentChilds))这行，执行完以后传入List<URL> nodeChildsToUrls(String parentPath, List<String> currentChilds) {..}这个方法的第一个参数为parentPath=/motan/default_rpc/com.epai.contract.iface.ActivityService/server,但是第二个参数为null，这时候首先抛出下面的异常
`java.lang.NullPointerException: null
    at com.weibo.api.motan.registry.zookeeper.ZookeeperRegistry.nodeChildsToUrls(ZookeeperRegistry.java:164) ~[motan-registry-zookeeper-0.1.1.jar:na]
    at com.weibo.api.motan.registry.zookeeper.ZookeeperRegistry.access$000(ZookeeperRegistry.java:33) ~[motan-registry-zookeeper-0.1.1.jar:na]
    at com.weibo.api.motan.registry.zookeeper.ZookeeperRegistry$1.handleChildChange(ZookeeperRegistry.java:81) ~[motan-registry-zookeeper-0.1.1.jar:na]
    at org.I0Itec.zkclient.ZkClient$7.run(ZkClient.java:570) ~[zkclient-0.3.jar:0.3]
    at org.I0Itec.zkclient.ZkEventThread.run(ZkEventThread.java:71) ~[zkclient-0.3.jar:0.3]`

最后就抛出这样的错误：
`com.weibo.api.motan.exception.MotanFrameworkException: error_message: Failed to subscribe motan://192.168.20.208:0/com.epai.contract.iface.ActivityService?group=activeGroup to zookeeper(zookeeper://127.0.0.1:2181/com.weibo.api.motan.registry.RegistryService?group=default_rpc), cause: null, status: 503, error_code: 20001,r=
    at com.weibo.api.motan.registry.zookeeper.ZookeeperRegistry.doSubscribe(ZookeeperRegistry.java:98) ~[motan-registry-zookeeper-0.1.1.jar:na]
    at com.weibo.api.motan.registry.support.AbstractRegistry.subscribe(AbstractRegistry.java:101) ~[motan-core-0.1.1.jar:na]
    at com.weibo.api.motan.registry.support.FailbackRegistry.subscribe(FailbackRegistry.java:107) ~[motan-core-0.1.1.jar:na]
    at com.weibo.api.motan.cluster.support.ClusterSupport.init(ClusterSupport.java:90) [motan-core-0.1.1.jar:na]
    at com.weibo.api.motan.config.handler.SimpleConfigHandler.buildClusterSupport(SimpleConfigHandler.java:55) [motan-core-0.1.1.jar:na]
    at com.weibo.api.motan.config.RefererConfig.createClusterSupport(RefererConfig.java:184) [motan-core-0.1.1.jar:na]
    at com.weibo.api.motan.config.RefererConfig.initRef(RefererConfig.java:128) [motan-core-0.1.1.jar:na]
    at com.weibo.api.motan.config.RefererConfig.getRef(RefererConfig.java:85) [motan-core-0.1.1.jar:na]
    at com.weibo.api.motan.config.springsupport.RefererConfigBean.getObject(RefererConfigBean.java:41) [motan-springsupport-0.1.1.jar:na]
    at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.doGetObjectFromFactoryBean(FactoryBeanRegistrySupport.java:168) [spring-beans-4.2.3.RELEASE.jar:4.2.3.RELEASE]
    at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.getObjectFromFactoryBean(FactoryBeanRegistrySupport.java:103) [spring-beans-4.2.3.RELEASE.jar:4.2.3.RELEASE]
    at org.springframework.beans.factory.support.AbstractBeanFactory.getObjectForBeanInstance(AbstractBeanFactory.java:1585) [spring-beans-4.2.3.RELEASE.jar:4.2.3.RELEASE]
    at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:254) [spring-beans-4.2.3.RELEASE.jar:4.2.3.RELEASE]
    at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197) [spring-beans-4.2.3.RELEASE.jar:4.2.3.RELEASE]
    at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1051) [spring-context-4.2.3.RELEASE.jar:4.2.3.RELEASE]
    at cn.epai.web.controller.HomeController.<init>(HomeController.java:23) [classes/:na]
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) [na:1.8.0_65]
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) [na:1.8.0_65]
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) [na:1.8.0_65]
    at java.lang.reflect.Constructor.newInstance(Constructor.java:422) [na:1.8.0_65]
    at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:147) [spring-beans-4.2.3.RELEASE.jar:4.2.3.RELEASE]
    at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:89) [spring-beans-4.2.3.RELEASE.jar:4.2.3.RELEASE]
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1098) [spring-beans-4.2.3.RELEASE.jar:4.2.3.RELEASE]
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1050) [spring-beans-4.2.3.RELEASE.jar:4.2.3.RELEASE]
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:510) [spring-beans-4.2.3.RELEASE.jar:4.2.3.RELEASE]
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482) [spring-beans-4.2.3.RELEASE.jar:4.2.3.RELEASE]
    at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306) [spring-beans-4.2.3.RELEASE.jar:4.2.3.RELEASE]
    at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) [spring-beans-4.2.3.RELEASE.jar:4.2.3.RELEASE]
    at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302) [spring-beans-4.2.3.RELEASE.jar:4.2.3.RELEASE]
    at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197) [spring-beans-4.2.3.RELEASE.jar:4.2.3.RELEASE]
    at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:772) [spring-beans-4.2.3.RELEASE.jar:4.2.3.RELEASE]
    at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:838) [spring-context-4.2.3.RELEASE.jar:4.2.3.RELEASE]
    at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:537) [spring-context-4.2.3.RELEASE.jar:4.2.3.RELEASE]
    at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118) [spring-boot-1.3.0.RELEASE.jar:1.3.0.RELEASE]
    at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:752) [spring-boot-1.3.0.RELEASE.jar:1.3.0.RELEASE]
    at org.springframework.boot.SpringApplication.doRun(SpringApplication.java:347) [spring-boot-1.3.0.RELEASE.jar:1.3.0.RELEASE]
    at org.springframework.boot.SpringApplication.run(SpringApplication.java:295) [spring-boot-1.3.0.RELEASE.jar:1.3.0.RELEASE]
    at cn.lxz.sweb.config.XApplication.run(XApplication.java:59) [classes/:na]
    at cn.epai.web.AppStart.main(AppStart.java:14) [classes/:na]
`

麻烦给指条解决的办法，服务端是正常运行了，心跳也打印正常
`2016-06-22 19:03:31.287  INFO 928 --- [pool-3-thread-1] serviceStatsLog                          : [motan-statisticCallback] identity: motan://192.168.20.208:8002/default_rpc//1.0/service connectionCount: 0 taskCount: 0 queueCount: 0 maxThreadCount: 800 maxTaskCount: 800
2016-06-22 19:03:31.287  INFO 928 --- [pool-3-thread-1] serviceStatsLog                          : [motan-statisticCallback] identity: motan://192.168.20.208:8003/default_rpc//1.0/service connectionCount: 0 taskCount: 0 queueCount: 0 maxThreadCount: 800 maxTaskCount: 800
2016-06-22 19:04:01.286  INFO 928 --- [pool-3-thread-1] serviceStatsLog                          : [motan-totalAccessStatistic] app: motan module: motan total_count: 0 slow_count: 0 biz_excp: 0 other_excp: 0 avg_time: 0.00ms biz_time: 0.00ms avg_tps: 0
2016-06-22 19:04:01.287  INFO 928 --- [pool-3-thread-1] serviceStatsLog                          : [motan-memoryStatistic] 239.98MB of 1797.50 MB (13.4%) used 
2016-06-22 19:04:01.287  INFO 928 --- [pool-3-thread-1] serviceStatsLog                          : [motan-statisticCallback] identity: motan://192.168.20.208:8002/default_rpc//1.0/service connectionCount: 0 taskCount: 0 queueCount: 0 maxThreadCount: 800 maxTaskCount: 800
2016-06-22 19:04:01.287  INFO 928 --- [pool-3-thread-1] serviceStatsLog                          : [motan-statisticCallback] identity: motan://192.168.20.208:8003/default_rpc//1.0/service connectionCount: 0 taskCount: 0 queueCount: 0 maxThreadCount: 800 maxTaskCount: 800
`

**Comment by sunnights** [comment]
这个问题在新版本中已经修复了，但还未正式发布，你可以下载最新的源码执行`mvn package`，用新的`motan-registry-zookeeper`包替换掉原来的即可

另外，出现这个问题可能是因为服务正常启动后没有调用对外提供服务的开关，
确认服务方是否正常提供服务可以通过motan-manager后台管理模块来查询服务
或者在zookeeper上确认相关服务节点是否存在，路径是`/motan/{group}/{service}/server/`，查看该结点下是否有服务提供端的临时结点即可
请参考#128

**Comment by qdaxb** [comment]
尝试一下在服务启动后调用

```
MotanSwitcherUtil.setSwitcherValue(MotanConstants.REGISTRY_HEARTBEAT_SWITCHER, true);
```

出现这个问题的原因应该是首次使用motan时没有标记服务为可用状态，此时注册中心中缺少一个根节点，导致订阅时有问题。
这个问题应该只会在首次使用motan时出现，调用过一次上述代码之后，后续订阅就不会再出这个问题了。

**Comment by lijhua** [comment]
我的服务端是SpringBoot框架：

```
 public static void main(String[] args) {
      new XApplication(BootStrapService.class,args).run();
    MotanSwitcherUtil.setSwitcherValue(MotanConstants.REGISTRY_HEARTBEAT_SWITCHER, true);
 }
```

加上这行代码`MotanSwitcherUtil.setSwitcherValue(MotanConstants.REGISTRY_HEARTBEAT_SWITCHER,true);`打印如下日志，是和之前不一样了，这回确实OK了：

日志如下：
`: SpringBoot Application started.
2016-06-22 22:11:17.040  INFO 8240 --- [           main] info                                     : [ZookeeperRegistry] Url (null) will set to available to Registry [zookeeper://127.0.0.1:2181/default_rpc/com.weibo.api.motan.registry.RegistryService/1.0/service]
2016-06-22 22:11:17.088  INFO 8240 --- [:0:0:0:0:8002])] info                                     : NettyChannelHandler channelConnected: remote=/192.168.1.104:63654 local=/192.168.1.104:8002 event=UpstreamChannelStateEvent
2016-06-22 22:11:17.098  INFO 8240 --- [:0:0:0:0:8003])] info                                     : NettyChannelHandler channelConnected: remote=/192.168.1.104:63664 local=/192.168.1.104:8003 event=UpstreamChannelStateEvent
2016-06-22 22:11:17.100  INFO 8240 --- [:0:0:0:0:8002])] info                                     : NettyChannelHandler channelConnected: remote=/192.168.1.104:63659 local=/192.168.1.104:8002 event=UpstreamChannelStateEvent
2016-06-22 22:11:17.114  INFO 8240 --- [:0:0:0:0:8003])] info                                     : NettyChannelHandler channelConnected: remote=/192.168.1.104:63671 local=/192.168.1.104:8003 event=UpstreamChannelStateEvent
`
另外我查看这句代码，那个常量的值为feature.configserver.heartbeat，字面意思不就是服务端心跳配置吗？难道是给客户端通知服务端已准备就绪？这个不应该去通知吧，这应该是注册中心的事情了，还有弱弱的问一句，这个已注册成功的服务在Controller中可以@Autowired自动注入吗？看你们的demo中都是ctx.getBean("xxxServerRefer")的形式，要做到自动注入，需要什么配置吗？

**Comment by sunnights** [comment]
1. motan中使用这个开关用来实现优雅停机的功能，服务注册的时候需要[显式调用这个开关](https://github.com/weibocom/motan/wiki/zh_quickstart#motan-zookeeper%E9%85%8D%E7%BD%AE)，来对外提供服务
   需要优雅停机的时候，将此开关设为false，即可保证服务不被调用
2. 关于服务端和注册中心间的心跳，可以参考 #121 中的部分回复
3. 使用注解方式配置功能尚未完善，可关注PR #101

**Comment by lijhua** [comment]
好，谢谢疑问解答，在目前Spring逐渐趋于零配置化的方向下，希望Motan也能支持零配置，能早日集成注解功能，随后将持续关注，学习~

**Comment by rayzhang0603** [comment]
@smart-vole motan的配置暂时不支持注解方式。不过motan已注册成功的服务bean在Controller中是可以使用@Autowired自动注入的

**Comment by lijhua** [comment]
不需要什么配置就可以@Autowired？你们自己测试过吗？求示例代码，反正目前我这边是不行，客户端启动时调用报如下错误，但是这个服务肯定是注册成功的，用ctx.getBean("xxxServerRefer")这种方式可以获取到实例，自动注入错误如下：
`Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [com.epai.contract.iface.ActivityService] found for dependency: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}
    at org.springframework.beans.factory.support.DefaultListableBeanFactory.raiseNoSuchBeanDefinitionException(DefaultListableBeanFactory.java:1373) ~[spring-beans-4.2.3.RELEASE.jar:4.2.3.RELEASE]
    at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1119) ~[spring-beans-4.2.3.RELEASE.jar:4.2.3.RELEASE]
    at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1014) ~[spring-beans-4.2.3.RELEASE.jar:4.2.3.RELEASE]
    at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:545) ~[spring-beans-4.2.3.RELEASE.jar:4.2.3.RELEASE]
    ... 23 common frames omitted`

**Comment by wydream** [comment]
Controller里@Autowired确实不行，我也试了，小白表示不清楚Controller里应该怎么引用Service，求指教

**Comment by rayzhang0603** [comment]
我没有在web项目中测试，直接使用controller注解，从ApplicationContext获取的这个controller bean是已经注入的好的。

```
@Controller
public class TestAutoWired {
 FooService service;
 public FooService getService() {
       return service;
   }

@Autowired
public void setService(FooService service) {
    this.service = service;
}
}
```

**Comment by rayzhang0603** [comment]
xml配置如下，其中motan_client.xml是rpc配置。我从这个   ApplicationContext获取TestAutoWired是可以正常使用的。

```
<context:annotation-config />
<context:component-scan base-package="quickstart" />
<import resource="motan_client.xml"/>
```

按说注解bean和motan bean在一个spring ApplicationContext中就可以的。

**Comment by rayzhang0603** [comment]
如果使用spring boot的话，使用@ImportResource加载一下motan配置就可以了。

```
@Controller
@EnableAutoConfiguration
@ImportResource(locations="classpath:motan_client.xml")
public class SpringbootTest {
    @RequestMapping("/")
    @ResponseBody
    String home() {
        System.out.println(service.hello("test"));
        return "Hello World!";
    }

    public static void main(String[] args) throws Exception {
        SpringApplication.run(SpringbootTest.class, args);
    }

    FooService service;
    public FooService getService() {
        return service;
    }

    @Autowired
    public void setService(FooService service) {
        this.service = service;
    }

}
```

**Comment by qdaxb** [comment]
annotation support is implement by #101 . See [wiki](https://github.com/weibocom/motan/wiki/zh_quickstart#使用注解方式配置motan) for more details.

close.
