### ISSUE TITLE
Motan decode error

### ISSUE THREAD

**Issue by thisxulz** [weibocom/motan#134]
你好，
Motan client端报了一个错误
com.weibo.api.motan.exception.MotanFrameworkException: error_message: decode error: isResponse=true, status: 503, error_code: 20003,r=
at com.weibo.api.motan.protocol.rpc.DefaultRpcCodec.decode(DefaultRpcCodec.java:136)
....

Caused by: com.caucho.hessian.io.HessianProtocolException: readObject: unknown code 0x43 (C)
at com.caucho.hessian.io.Hessian2Input.error(Hessian2Input.java:2705)

这个是什么原因引起的呢？
使用resin启动，jdk1.8，会报这个错误，单独测试类不会报错

**Comment by rayzhang0603** [comment]
有可能是hessian的版本冲突。看一下server端和client端使用的hessian版本是多少，是否一致

**Comment by thisxulz** [comment]
确实是hessian架包冲突了...
