### ISSUE TITLE
0.1.2版本中的Demo中motan-demo-server运行报空指针异常

### ISSUE THREAD

**Issue by cn-yh** [weibocom/motan#163]
我检出源码切换到0.1.2版本，运行motan\motan-demo\motan-demo-server项目中的com.weibo.motan.demo.server.DemoRpcServer 类的main方法时报空指针异常，异常信息如下：

```
Exception in thread "main" java.lang.NullPointerException
    at com.weibo.api.motan.protocol.rpc.DefaultRpcProtocol$DefaultRpcExporter.<init>(DefaultRpcProtocol.java:83)
    at com.weibo.api.motan.protocol.rpc.DefaultRpcProtocol.createExporter(DefaultRpcProtocol.java:58)
    at com.weibo.api.motan.protocol.AbstractProtocol.export(AbstractProtocol.java:70)
    at com.weibo.api.motan.protocol.support.ProtocolFilterDecorator.export(ProtocolFilterDecorator.java:65)
    at com.weibo.api.motan.config.handler.SimpleConfigHandler.export(SimpleConfigHandler.java:77)
    at com.weibo.api.motan.config.ServiceConfig.doExport(ServiceConfig.java:211)
    at com.weibo.api.motan.config.ServiceConfig.export(ServiceConfig.java:129)
    at com.weibo.api.motan.config.springsupport.ServiceConfigBean.onApplicationEvent(ServiceConfigBean.java:90)
    at com.weibo.api.motan.config.springsupport.ServiceConfigBean.onApplicationEvent(ServiceConfigBean.java:42)
    at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:163)
    at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:136)
    at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:381)
    at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:335)
    at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:855)
    at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:541)
    at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:139)
    at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:93)
    at com.weibo.motan.demo.server.DemoRpcServer.main(DemoRpcServer.java:27)
```

抛出异常的代码：

```
        public DefaultRpcExporter(Provider<T> provider, URL url) {
            super(provider, url);

            ProviderMessageRouter requestRouter = initRequestRouter(url);
            endpointFactory =
                    ExtensionLoader.getExtensionLoader(EndpointFactory.class).getExtension(
                            url.getParameter(URLParamType.endpointFactory.getName(), URLParamType.endpointFactory.getValue()));
            server = endpointFactory.createServer(url, requestRouter);
        }
```

其中endpointFactory为null。
EndpointFactory为接口：com.weibo.api.motan.transport.EndpointFactory，这个接口只有一个抽象实现类：com.weibo.api.motan.transport.support.AbstractEndpointFactory。
这个Demo是还需要哪个jar包才能运行么？该如何解决这个空指针问题？

**Comment by rayzhang0603** [comment]
请检查是否依赖了motan-tansport-netty模块

**Comment by cn-yh** [comment]
确实是maven下载的jar没下载完整，删了重新下载就好了。多谢
