### ISSUE TITLE
使用 consul cluster 时,consul 能发现服务 motan 发现不了 client 调用出现 404 /  10101 错误

### ISSUE THREAD

**Issue by yelllowhat** [weibocom/motan#165]
问题描述： 在单节点 consul 注册时，服务运行正常, 采用 consul cluster 多节点时，motan 找不到服务

Exception in thread "main" com.weibo.api.motan.exception.MotanFrameworkException: error_message: ClusterSupport No service urls for the refer:motan://192.168.1.73:0/sk-tools/com.csf.api.demo.GenMd5Code/1.0/referer, registries:[consul://192.168.0.198:8500/com.weibo.api.motan.registry.RegistryService?group=default_rpc], status: 404, error_code: 10101,r=
    at com.weibo.api.motan.cluster.support.ClusterSupport.init(ClusterSupport.java:102)
    at com.weibo.api.motan.config.handler.SimpleConfigHandler.buildClusterSupport(SimpleConfigHandler.java:55)
    at com.weibo.api.motan.config.RefererConfig.createClusterSupport(RefererConfig.java:184)
    at com.weibo.api.motan.config.RefererConfig.initRef(RefererConfig.java:128)
    at com.weibo.api.motan.config.RefererConfig.getRef(RefererConfig.java:85)
    at com.csf.demo.ApiClientMain.main(ApiClientMain.java:66)

ERROR 错误日志报出：

17:01:52,482 ERROR error:87 - com.weibo.api.motan.config.handler.ConfigHandler: Error load spi class
java.lang.ClassNotFoundException: com.weibo.api.motan.config.handler.MockConfigHandler
    at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:348)
    at com.weibo.api.motan.core.extension.ExtensionLoader.loadClass(ExtensionLoader.java:351)
    at com.weibo.api.motan.core.extension.ExtensionLoader.loadExtensionClasses(ExtensionLoader.java:338)
    at com.weibo.api.motan.core.extension.ExtensionLoader.loadExtensionClasses(ExtensionLoader.java:167)
    at com.weibo.api.motan.core.extension.ExtensionLoader.checkInit(ExtensionLoader.java:78)
    at com.weibo.api.motan.core.extension.ExtensionLoader.getExtension(ExtensionLoader.java:89)
    at com.weibo.api.motan.config.RefererConfig.initRef(RefererConfig.java:114)
    at com.weibo.api.motan.config.RefererConfig.getRef(RefererConfig.java:85)

跟踪了一下，代码发现 motan-core 中并没有 com.weibo.api.motan.config.handler.MockConfigHandler 类，报出 ClassNotFoundException 也是情理之中的，但这个 MockConfigHandler  从哪时来的需要查一下.
1. consul 查找服务

在 consul cluster 上使用 dns 查找:

;; ANSWER SECTION:
motanrpc_tools.service.consul. 0 IN     SRV     1 1 8007 n1.node.dc1.consul.
motanrpc_tools.service.consul. 0 IN     SRV     1 1 8008 n1.node.dc1.consul.
1.  在 motan motanmanager 界面 RPC服务查询  显示

该服务  Unavailable Server  
1. 检察配置

配置说明:  未采用  injvm 方式 

下面是  motan_base_cofig.xml  基础配置文件,在 main 中加载导入.

  < motan:protocol id="motan-protocol" name="motan"
        default="true" serialization="hessian2" codec="motan" iothreads="4"
        requestTimeout="200" minClientConnection="1" maxClientConnection="50"
        minWorkerThread="20" maxWorkerThread="800" maxContentLength="10485760"
        maxServerConnection="100000" poolLifo="true" lazyInit="false" cluster="default"
        loadbalance="random" haStrategy="failover" async="false"
        switcherService="localSwitcherService" />

```
<!-- 降级功能可以通过配置SwitcherFilter实现，通过设置开关状态控制是否处理request。 -->
<!-- filter="switcher" -->
<!-- export格式为“protocol id:提供服务的端口” -->
<motan:basicService id="serviceBasicConfig"
    registry="consul-registry" shareChannel="true" accessLog="true" group="tools"
    module="base" application="sk-tools" filter="switcher"  / >

<!-- 通用referer基础配置 -->
< motan:basicReferer id="clientBasicConfig" registry="consul-registry"
    connectTimeout="300" requestTimeout="300" protocol="motan-protocol"
    throwException="false" group="sk-tools" module="sk-tools" application="sk-tools"
    version="1.0" / >
  `

  5. 发布方式

    服务发布采用 @MotanService(export = "8008") 方式发布

   @MotanService(export = "8008")
   public class GenMd5CodeImpl2 implements GenMd5Code {

@Override
public String genMd5Str(String souStr) {

    if (StringUtils.isBlank(souStr)) {
        return null;
    }
    return MD5.md5(souStr.trim());
} 
```

   }

   main:

   public static void main(String[] args) throws InterruptedException {
           ctx = new ClassPathXmlApplicationContext(
                new String[] { "motan_base_cofig.xml", "annotation_server-config.xml" });
           MotanSwitcherUtil.setSwitcherValue(MotanConstants.REGISTRY_HEARTBEAT_SWITCHER, true);
 }

**Comment by afk6** [comment]
我也遇到类似的问题了...  
最后发现是,  
 zookeeper做注册中心的帮助页面,  版本号是 RELEASE,实际用的是0.3.1
motan的帮助页面是0.3.0 
两个不一致的时候,出现找不到Closeable类.
