### ISSUE TITLE
motan 发布服务后，客户端未能连接上server

### ISSUE THREAD

**Issue by javenliu** [weibocom/motan#197]
用例：MotanApiExportDemo和MotanApiClientDemo，略改动servierImpl的类名，具体为：
MotanDemoService->FooService
MotanDemoServiceImpl->FooServiceImpl

zookeeper已搭建。
运行MotanApiExportDemo和MotanApiClientDemo后，通过zkCli.sh查看

[zk: 127.0.0.1(CONNECTED) 2] ls /motan/motan-demo-rpc/demo.motan.service.FooService
[server, unavailableServer, client]

[zk: 127.0.0.1(CONNECTED) 3] ls /motan/motan-demo-rpc/demo.motan.service.FooService/server
[192.168.1.88:8002]

[zk: 127.0.0.1(CONNECTED) 4] ls /motan/motan-demo-rpc/demo.motan.service.FooService/server/192.168.1.88:8002
[]

客户端错误日志：
Exception in thread "main" com.weibo.api.motan.exception.MotanServiceException: error_message: NettyChannel failed to connect to server, url: motan://192.168.1.88:8002/demo.motan.service.FooService, result: true, success: false, connected: false, status: 503, error_code: 10001,r=null
    at com.weibo.api.motan.transport.netty.NettyChannel.open(NettyChannel.java:150)
    at com.weibo.api.motan.transport.netty.NettyChannelFactory.makeObject(NettyChannelFactory.java:53)
    at org.apache.commons.pool.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:1188)
    at com.weibo.api.motan.transport.AbstractPoolClient.borrowObject(AbstractPoolClient.java:75)
    at com.weibo.api.motan.transport.netty.NettyClient.request(NettyClient.java:160)
    at com.weibo.api.motan.transport.netty.NettyClient.request(NettyClient.java:116)
    at com.weibo.api.motan.protocol.rpc.DefaultRpcProtocol$DefaultRpcReferer.doCall(DefaultRpcProtocol.java:171)
    at com.weibo.api.motan.rpc.AbstractReferer.call(AbstractReferer.java:64)
    at com.weibo.api.motan.cluster.ha.FailoverHaStrategy.call(FailoverHaStrategy.java:72)
    at com.weibo.api.motan.cluster.support.ClusterSpi.call(ClusterSpi.java:73)

**Comment by yelllowhat** [comment]
建议检察
1. 域名配置, ip 不要配置 127.0.0.1 / localhost ，请配置实际的IP名
2. 检察服务暴露的 group  , module   , 查看 server / client 配置 motan:basicService /  motan:basicReferer
