### ISSUE TITLE
No available referers for call  / request timeout: 

### ISSUE THREAD

**Issue by yelllowhat** [weibocom/motan#199]
Dear all 

 我在使用过程中发现这个问题，先上一下 stack 信息  
1. LocalFirstLoadBalance No available referers for call

18:49:27,268  WARN warn:75 - RefererInvocationHandler invoke false, so return default value: uri=motan://192.168.1.73:0/com.csf.api.fund.service.IFundService requestId=1545443912993219049 interface=com.csf.api.fund.service.IFundService method=getDetail(java.lang.String)
com.weibo.api.motan.exception.MotanServiceException: error_message: LocalFirstLoadBalance No available referers for call : referers_size=1 requestId=1545443912993219049 interface=com.csf.api.fund.service.IFundService method=getDetail(java.lang.String), status: 503, error_code: 10001,r=null
    at com.weibo.api.motan.cluster.loadbalance.AbstractLoadBalance.selectToHolder(AbstractLoadBalance.java:80)
    at com.weibo.api.motan.cluster.ha.FailoverHaStrategy.selectReferers(FailoverHaStrategy.java:90)
    at com.weibo.api.motan.cluster.ha.FailoverHaStrategy.call(FailoverHaStrategy.java:53)
    at com.weibo.api.motan.cluster.support.ClusterSpi.call(ClusterSpi.java:73)
    at com.weibo.api.motan.proxy.RefererInvocationHandler.invoke(RefererInvocationHandler.java:108)
    at com.sun.proxy.$Proxy44.getDetail(Unknown Source)
    at com.csf.business.fund.FundBaseControl.listKeys(FundBaseControl.java:29)
    at sun.reflect.GeneratedMethodAccessor13.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:137)
    at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:296)
    at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:250)
    at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:237)
    at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:356)
    at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:179)
    at org.jboss.resteasy.plugins.server.netty.RequestDispatcher.service(RequestDispatcher.java:83)
    at org.jboss.resteasy.plugins.server.netty.RequestHandler.messageReceived(RequestHandler.java:52)
    at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:80)
    at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
    at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:783)
    at org.jboss.netty.handler.execution.ChannelEventRunnable.run(ChannelEventRunnable.java:69)
    at org.jboss.netty.handler.execution.OrderedMemoryAwareThreadPoolExecutor$ChildExecutor.run(OrderedMemoryAwareThreadPoolExecutor.java:316)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
1.  NettyResponseFuture request timeout

com.weibo.api.motan.exception.MotanServiceException: error_message: NettyResponseFuture request timeout: serverPort=192.168.1.73:8002 requestId=1545439090469502977 interface=com.csf.api.fund.service.IFundService method=getDetail(java.lang.String) cost=500, status: 503, error_code: 10003,r=null
    at com.weibo.api.motan.transport.netty.NettyResponseFuture.timeoutSoCancel(NettyResponseFuture.java:234)
    at com.weibo.api.motan.transport.netty.NettyResponseFuture.getValue(NettyResponseFuture.java:137)
    at com.weibo.api.motan.proxy.RefererInvocationHandler.invoke(RefererInvocationHandler.java:109)
    at com.sun.proxy.$Proxy44.getDetail(Unknown Source)
    at com.csf.business.fund.FundBaseControl.listKeys(FundBaseControl.java:29)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:137)
    at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:296)
    at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:250)
    at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:237)
    at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:356)
    at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:179)
    at org.jboss.resteasy.plugins.server.netty.RequestDispatcher.service(RequestDispatcher.java:83)
    at org.jboss.resteasy.plugins.server.netty.RequestHandler.messageReceived(RequestHandler.java:52)
    at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:80)
    at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
    at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:783)
    at org.jboss.netty.handler.execution.ChannelEventRunnable.run(ChannelEventRunnable.java:69)
    at org.jboss.netty.handler.execution.OrderedMemoryAwareThreadPoolExecutor$ChildExecutor.run(OrderedMemoryAwareThreadPoolExecutor.java:316)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)

配置说明:  
motan-base-config.xml

< motan:protocol id="motan-protocol" default="true" name="motan"
        serialization="hessian2" codec="motan" iothreads="8" requestTimeout="500"
        minClientConnection="50" maxClientConnection="500" minWorkerThread="50"
        maxWorkerThread="1024" maxContentLength="10485760"
        maxServerConnection="100000" poolLifo="true" lazyInit="false" cluster="default"
        loadbalance="localFirst" haStrategy="failover" async="false"
        switcherService="localSwitcherService" /  >

< motan:basicService id="serviceBasicConfig"
        registry="consul-registry" shareChannel="true" accessLog="false"
        throwException="true" group="dev-fund-service" module="dev-fund-dao"
        application="dev-fund-service" filter="switcher" export="motan-protocol:8002"
        requestTimeout="1000" / >

< motan:basicReferer id="clientBasicConfig" registry="consul-registry"
        connectTimeout="500" requestTimeout="500" protocol="motan-protocol"
        throwException="true" check="true" accessLog="false" group="dev-fund-dao"
        module="dev-fund-dao" application="dev-fund-dao" version="1.0"
        retries="2"/ >

背景：
1.  consul 作为 registory 工具
2.  服务发布，尝试过 单机与 多机，server / client 放在同一个机器上，和不同机器上分别实现，都尝试过 　

问题排查：
1.   出现timeout 时，我检察是否是应用出现的问题，// 服务正常,日志监控不曾出现 timeout 数据处理
2.   加大connectTimeout 参数  解决不了问题
3.  switcherService 修改， 修改为  localSwitcherService 本地优先
4.  根据 错误码说明：
　　503   10001   No available referers for call request
      // 在消费方所有referers被标为不可用，检查是否所有的请求都失败

```
 这里我的情况是，大部分成功，部分现现以上问题
```

发现还是经常找不到服务，根据自己测试的情况来看，应该问题出在 服务发现上，出现服务不可用，才会出现以上情况的

**Comment by rayzhang0603** [comment]
看样子能够提供服务的server只有一台，当这台server的请求连续失败超过10ci时会自动把server标记为不可用，就会出现上面的异常。这种情况下建议调大requestTimeout时间，并多创建些链接，可以调整minClientConnection、maxClientConnection为20试试。

**Comment by yelllowhat** [comment]
@rayzhang0603  感谢耐心回复，谢谢

这个问题比较复杂，不太容易排除
1. 在此之前 为了验证单台服务问题，我尝试把服务多发布几台，在局域网中，发现没有效果
2. minClientConnection="50" maxClientConnection="500" 我现在的配置是 你说配置成 20 ? 不是配置更小了吗？

**Comment by rayzhang0603** [comment]
抱歉，没有仔细看配置。
第一个报错中LocalFirstLoadBalance No available referers for call : referers_size=1 referers_size表示注册中心可用的server数量，为1的话服务发现应该没有问题，这时提示No available referers for call是因为这个server被client置为了unavailable状态。server被标记为unavailable的条件是连续请求失败超过10次。
因为大部分请求是成功的，所以应该是并发请求中出现了连续超时的情况，可以把basicReferer的requestTimeout调大试试，例如2000

**Comment by yelllowhat** [comment]
@rayzhang0603  你好

在之前的场景中，我们业务层采用 http 方式提供直接的服务，操作未超过 200ms ，采用服务发布后就现出长时间的超时，所以在测试 qps ,tps 时在同样的业务逻辑下，在切换后，表现的差别比较大

我现在想弄清楚，出现 timeout 的原因 ( 我们先排除 业务层的东西 ) 为了排除 业务层的干扰，我把业务层数据采用 mock 来实现，基本排除业务因素， 测试时还是出现服务发现及不可用的问题

说明： 修改成 2000 后，错误少了一些，但效率很差

问问，有没有出现过类似的情况 ？

**Comment by rayzhang0603** [comment]
之前没有出现过类似情况，一般业务超时配置都是1s以内。你可以通过抓包确认一下具体耗时是在server端还是client端还是网络，在具体分析耗时的点吧。消息处理部分可以从com.weibo.api.motan.transport.netty.NettyEncoder、NettyDecoder类中的encode、decode开始排查

**Comment by yelllowhat** [comment]
好的，谢谢我先查一下原因。

**Comment by yelllowhat** [comment]
从 c/s 两端的分析来看，delay 主要是发生在 client  ，在查找服务时出现服务状态不对,日志如下

WARN warn:71 NettyClient heartbeat Error: state=UNINIT url=motan://192.168.0.198:8002/com.csf.api.fund.service.IFundService

通过 api 直接调用，同样的也发现此问题,还在继续排查  state=UNINIT  的原因, 有类似的情况大家分享一下.

说明： 测试统计数据
服务查找局域网 cost 平均 85ms ，场景是每次初始环境获取服务

Q1:   服务引用是可否 single  查看配置好像不支持
Q2:   api 调用方式与 config 配置方式引用服务差别比较大,若 构建好  RefererConfig 并保持，这时获取 
         getRef() 效率很快，测试基本为 0~1ms, 此时的引用是 single 的,  是否有线程问题，需要测试

api方式使用不太灵活，在项目中大多还是采用配置，但配置的方式效率较低( 在服务查找上，不能像 api 一样持有)  如何正确使用，请 weibo  小组给建议

**Comment by rayzhang0603** [comment]
xml配置方式默认就是单例的，refer对象线程安全。加载spring bean后直接使用就可以。服务发现是单独的线程负责维护，调用时并不需要查找服务，只是从本地缓存中按lb规则直接使用。
使用配置方式、api方式、注解方式，实际的调用效率是一致的。
建议用demo中最简单的例子测试一下，看是不是配置方式有问题，例如是不是在请求时有重复加载配置之类的

**Comment by zrbcool** [comment]
> 请求失败

我想基于这个回答问一下， 我们线上也出现了这个错误，这个[连续请求失败超过10次]的策略是特指超时这个异常吗，还是服务端向上抛出的异常都算呢？ 谢谢

**Comment by zrbcool** [comment]
> 抱歉，没有仔细看配置。
> 第一个报错中LocalFirstLoadBalance No available referers for call : referers_size=1 referers_size表示注册中心可用的server数量，为1的话服务发现应该没有问题，这时提示No available referers for call是因为这个server被client置为了unavailable状态。server被标记为unavailable的条件是连续请求失败超过10次。
> 因为大部分请求是成功的，所以应该是并发请求中出现了连续超时的情况，可以把basicReferer的requestTimeout调大试试，例如2000

我想基于这个回答问一下， 我们线上也出现了这个错误，这个[连续请求失败超过10次]的策略是特指超时这个异常吗，还是服务端向上抛出的异常都算呢？ 谢谢

**Comment by rayzhang0603** [comment]
@zrbcool 服务端抛出的异常在框架里会封装成BizException（业务异常），这种异常不会算作请求失败，也不会记录失败次数
