### ISSUE TITLE
NettyDecoder transport header not support

### ISSUE THREAD

**Issue by panjianping1991** [weibocom/motan#216]
2016-10-08 17:58:36.201 [New I/O server worker #1-22] [error] [ERROR] [87]- NettyChannelHandler exceptionCaught: remote=/58.60.171.230:58865 local=/10.248.161.6:443 event=com.weibo.api.motan.exception.MotanFrameworkException: error_message: NettyDecoder transport header not support, type: 0, status: 503, error_code: 20001,r=null
com.weibo.api.motan.exception.MotanFrameworkException: error_message: NettyDecoder transport header not support, type: 0, status: 503, error_code: 20001,r=null
    at com.weibo.api.motan.transport.netty.NettyDecoder.decode(NettyDecoder.java:67)
    at org.jboss.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:282)
    at org.jboss.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:216)
    at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:274)
    at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:261)
    at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:349)
    at org.jboss.netty.channel.socket.nio.NioWorker.processSelectedKeys(NioWorker.java:280)
    at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:200)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)

**Comment by rayzhang0603** [comment]
异常的意思是这个请求不是motan rpc 请求。你用的端口是443吗？是不是有什么非rpc的请求调用到了这个端口？

异常代码位置见NettyDecoder line： 65

**Comment by panjianping1991** [comment]
刚才确认了，确实有非rpc请求调用了这个端口，谢谢你
