### ISSUE TITLE
客户端调用失败

### ISSUE THREAD

**Issue by kividii** [weibocom/motan#217]
服务端配置:
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:motan="http://api.weibo.com/schema/motan"
    xsi:schemaLocation="http://www.springframework.org/schema/beans 
        http://www.springframework.org/schema/beans/spring-beans-2.5.xsd
        http://api.weibo.com/schema/motan http://api.weibo.com/schema/motan.xsd">
    <bean id="testService" class="com.xyz.TestServiceImpl" />

```
<motan:protocol id="mmm_service_protocol_id" name="motan" />

<motan:registry regProtocol="zookeeper" name="mmm_zk"
    address="10.0.10.241:2181" />

<motan:basicService id="mmm_basic_id"
    export="mmm_service_protocol_id:8002" shareChannel="true"
    application="mmm_basic_application" registry="mmm_zk" />

<motan:service interface="com.xyz.TestService"
    ref="testService" basicService="mmm_basic_id" />
```

</beans>
启动后信息:
2016-10-09 13:45:12,864 DEBUG [org.apache.zookeeper.ClientCnxn] - Got ping response for sessionid: 0x157a21e1f58000f after 1ms
2016-10-09 13:45:26,198 DEBUG [org.apache.zookeeper.ClientCnxn] - Got ping response for sessionid: 0x157a21e1f58000f after 1ms
2016-10-09 13:45:35,823 INFO [serviceStatsLog] - [motan-totalAccessStatistic] app: motan module: motan total_count: 0 slow_count: 0 biz_excp: 0 other_excp: 0 avg_time: 0.00ms biz_time: 0.00ms avg_tps: 0
2016-10-09 13:45:35,824 INFO [serviceStatsLog] - [motan-memoryStatistic] 25.65MB of 1810.00 MB (1.4%) used 
2016-10-09 13:45:35,824 INFO [serviceStatsLog] - [motan-statisticCallback] identity: motan://10.0.20.239:8002/default_rpc//1.0/service connectionCount: 0 taskCount: 0 queueCount: 0 maxThreadCount: 800 maxTaskCount: 800
2016-10-09 13:45:39,531 DEBUG [org.apache.zookeeper.ClientCnxn] - Got ping response for sessionid: 0x157a21e1f58000f after 1ms
2016-10-09 13:45:52,866 DEBUG [org.apache.zookeeper.ClientCnxn] - Got ping response for sessionid: 0x157a21e1f58000f after 1ms

客户端配置:
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:motan="http://api.weibo.com/schema/motan"
    xsi:schemaLocation="http://www.springframework.org/schema/beans 
        http://www.springframework.org/schema/beans/spring-beans-2.5.xsd
        http://api.weibo.com/schema/motan http://api.weibo.com/schema/motan.xsd">

```
    <motan:registry regProtocol="zookeeper" name="mmm_zk"
    address="10.0.10.241:2181" />

<motan:protocol default="true" name="motan" haStrategy="failover"
    loadbalance="roundrobin" maxClientConnection="10" minClientConnection="2" />

<motan:basicReferer requestTimeout="5000" accessLog="false"
    connectTimeout="3000" retries="2" group="mmm_remote_service_rpc"
    application="motan_server_benchmark_application" protocol="motan"
    registry="mmm_zk" id="motan_client_basic_config" throwException="true"
    check="true" />

<motan:referer id="testService" interface="com.xyz.TestService"
    basicReferer="motan_client_basic_config" />
```

</beans>
客户端启动信息:
Caused by: com.weibo.api.motan.exception.MotanFrameworkException: error_message: ClusterSupport No service urls for the refer:motan://10.0.20.239:0/mmm_remote_service_rpc/com.xyz.TestService/1.0/referer, registries:[zookeeper://10.0.10.241:2181/com.weibo.api.motan.registry.RegistryService?group=default_rpc], status: 404, error_code: 10101,r=null
    at com.weibo.api.motan.cluster.support.ClusterSupport.init(ClusterSupport.java:102)
    at com.weibo.api.motan.config.handler.SimpleConfigHandler.buildClusterSupport(SimpleConfigHandler.java:55)
    at com.weibo.api.motan.config.RefererConfig.createClusterSupport(RefererConfig.java:184)
    at com.weibo.api.motan.config.RefererConfig.initRef(RefererConfig.java:128)
    at com.weibo.api.motan.config.RefererConfig.getRef(RefererConfig.java:85)
    at com.weibo.api.motan.config.springsupport.RefererConfigBean.getObject(RefererConfigBean.java:44)
    at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.doGetObjectFromFactoryBean(FactoryBeanRegistrySupport.java:166)
    ... 50 more

如果在客户端指定directUrl启动则正常, 有原因的吗?

**Comment by kividii** [comment]
ClusterSupport No service urls for the refer:motan://10.0.20.239:0/mmm_remote_service_rpc/com.xyz.TestService/1.0/referer, registries:[zookeeper://10.0.10.241:2181/com.weibo.api.motan.registry.RegistryService?group=default_rpc], status: 404, error_code: 10101,r=null
其中motan://10.0.20.239:0, 端口号没有找到!!!

**Comment by rayzhang0603** [comment]
你的server端加上和client端相同的group配置试试。服务发现需要service名、group、version一致才行，也可以从manage后台看一下服务是否正确注册了。

另外referer中的端口号固定是0，这个是client端的信息，只有server端才会有提供服务的端口号。

**Comment by kividii** [comment]
@rayzhang0603 , 不行, 还是一样的错误, 配置就那么几行配置, 一直不成功, 是否与网段, 网卡之类的有关系呀?　服务端已经启动成功了，客户端用我上面的配置不能成功调用，　但是在客户端配置上，　如果对应的加上directUrl，　是可以调用成功的，　如：
motan:referer id="testService"interface="com.xyz.TestService"directUrl＝＂10.0.20.239:8002＂basicReferer="motan_client_basic_config"

**Comment by rayzhang0603** [comment]
请确认：
1、server端的提供服务开关是否打开了。 

```
MotanSwitcherUtil.setSwitcherValue(MotanConstants.REGISTRY_HEARTBEAT_SWITCHER, true);
```

2、确认server是否在zk注册中心注册成功了。

**Comment by lxlbarnett** [comment]
@rayzhang0603 
MotanSwitcherUtil.setSwitcherValue(MotanConstants.REGISTRY_HEARTBEAT_SWITCHER, true);
这个你要放置在那个地方，是启动main方法中？我们配置是使用spring的配置，还需要这个吗？

**Comment by rayzhang0603** [comment]
这个是提供服务的开关，打开开关后server才会对外提供服务，从注册中心才能查询到。这个功能是为了方便验证服务及优雅停机。放置在哪里执行都可以，一般是系统启动，验证服务正常后，在操作开关提供服务

**Comment by liuyb02** [comment]
@rayzhang0603 请问在motan-manager中服务显示为unavailableserver是因为这个开关没正常打开造成的吗？

**Comment by rayzhang0603** [comment]
是。能够提供服务的状态是working

**Comment by kividii** [comment]
问题解决, 的确是服务端启动的时候没有执行MotanSwitcherUtil.setSwitcherValue(MotanConstants.REGISTRY_HEARTBEAT_SWITCHER, true);
导致客户端调用不到!
谢谢# @rayzhang0603

**Comment by mark988** [comment]
我用的是spring 配置。
MotanSwitcherUtil.setSwitcherValue(MotanConstants.REGISTRY_HEARTBEAT_SWITCHER, true); 可以写到配置文件里吗？ 如果不能写到配置文件里，可以直接写到service代码里吗？？？

**Comment by gaoke966** [comment]
我是这样解决的，写一个监听类，等待spring初始化后调用，代码如下：
public class HeartBeatSwitcher implements ApplicationListener<ContextRefreshedEvent> {
    private Logger logger = Logger.getLogger(HeartBeatSwitcher.class);
    private boolean switcherValue;

```
public void setSwitcherValue(boolean switcherValue) {
    this.switcherValue = switcherValue;
}

@Override
public void onApplicationEvent(ContextRefreshedEvent contextRefreshedEvent) {
    if(contextRefreshedEvent.getApplicationContext().getParent() != null) {//root application context 没有parent，这里需要projectName-servlet  context（作为root application context的子容器）之后执行
        MotanSwitcherUtil.setSwitcherValue(MotanConstants.REGISTRY_HEARTBEAT_SWITCHER, switcherValue);
        logger.info("rpc server start.switcherValue ====== " + switcherValue + ".");
    }
}
```

}
不知道有没有潜在问题，或者有没有更好的办法
