### ISSUE TITLE
motan使用zookeeper注册模式在客户端获取服务报ClusterSupport No service urls for the refer错误

### ISSUE THREAD

**Issue by lxlbarnett** [weibocom/motan#218]
> 客户端的具体问题：

2016-10-10 11:08:34,053 INFO [org.I0Itec.zkclient.ZkEventThread] - Starting ZkClient event thread.
2016-10-10 11:08:34,058 INFO [org.apache.zookeeper.ZooKeeper] - Client environment:zookeeper.version=3.4.8--1, built on 02/06/2016 03:18 GMT
2016-10-10 11:08:34,059 INFO [org.apache.zookeeper.ZooKeeper] - Client environment:host.name=007-PC
2016-10-10 11:08:34,059 INFO [org.apache.zookeeper.ZooKeeper] - Client environment:java.version=1.7.0_80
2016-10-10 11:08:34,059 INFO [org.apache.zookeeper.ZooKeeper] - Client environment:java.vendor=Oracle Corporation
2016-10-10 11:08:34,059 INFO [org.apache.zookeeper.ZooKeeper] - Client environment:java.home=C:\Program Files\Java\jdk1.7.0_80\jre
2016-10-10 11:08:34,059 INFO [org.apache.zookeeper.ZooKeeper] - Client environment:java.class.path=E:\myself_data\motan-pro-clicent\target\classes;D:\apps\maven\repository\org\springframework\spring-context\3.2.11.RELEASE\spring-context-3.2.11.RELEASE.jar;D:\apps\maven\repository\org\springframework\spring-aop\3.2.11.RELEASE\spring-aop-3.2.11.RELEASE.jar;D:\apps\maven\repository\aopalliance\aopalliance\1.0\aopalliance-1.0.jar;D:\apps\maven\repository\org\springframework\spring-beans\3.2.11.RELEASE\spring-beans-3.2.11.RELEASE.jar;D:\apps\maven\repository\org\springframework\spring-core\3.2.11.RELEASE\spring-core-3.2.11.RELEASE.jar;D:\apps\maven\repository\commons-logging\commons-logging\1.1.3\commons-logging-1.1.3.jar;D:\apps\maven\repository\org\springframework\spring-expression\3.2.11.RELEASE\spring-expression-3.2.11.RELEASE.jar;D:\apps\maven\repository\org\springframework\spring-context-support\3.2.11.RELEASE\spring-context-support-3.2.11.RELEASE.jar;D:\apps\maven\repository\com\weibo\motan-core\0.2.1\motan-core-0.2.1.jar;D:\apps\maven\repository\commons-pool\commons-pool\1.6\commons-pool-1.6.jar;D:\apps\maven\repository\com\caucho\hessian\4.0.38\hessian-4.0.38.jar;D:\apps\maven\repository\com\alibaba\fastjson\1.1.30\fastjson-1.1.30.jar;D:\apps\maven\repository\com\codahale\metrics\metrics-core\3.0.1\metrics-core-3.0.1.jar;D:\apps\maven\repository\com\google\guava\guava\18.0\guava-18.0.jar;D:\apps\maven\repository\org\apache\commons\commons-lang3\3.1\commons-lang3-3.1.jar;D:\apps\maven\repository\commons-codec\commons-codec\1.4\commons-codec-1.4.jar;D:\apps\maven\repository\com\weibo\motan-transport-netty\0.2.1\motan-transport-netty-0.2.1.jar;D:\apps\maven\repository\org\jboss\netty\netty\3.2.5.Final\netty-3.2.5.Final.jar;D:\apps\maven\repository\com\weibo\motan-springsupport\0.2.1\motan-springsupport-0.2.1.jar;D:\apps\maven\repository\com\weibo\motan-registry-zookeeper\0.2.1\motan-registry-zookeeper-0.2.1.jar;D:\apps\maven\repository\org\apache\zookeeper\zookeeper\3.4.8\zookeeper-3.4.8.jar;D:\apps\maven\repository\jline\jline\0.9.94\jline-0.9.94.jar;D:\apps\maven\repository\io\netty\netty\3.7.0.Final\netty-3.7.0.Final.jar;D:\apps\maven\repository\com\101tec\zkclient\0.3\zkclient-0.3.jar;D:\apps\maven\repository\org\slf4j\slf4j-api\1.5.8\slf4j-api-1.5.8.jar;D:\apps\maven\repository\org\slf4j\slf4j-log4j12\1.5.8\slf4j-log4j12-1.5.8.jar;D:\apps\maven\repository\log4j\log4j\1.2.14\log4j-1.2.14.jar
2016-10-10 11:08:34,059 INFO [org.apache.zookeeper.ZooKeeper] - Client environment:java.library.path=C:\Program Files\Java\jdk1.7.0_80\bin;C:\Windows\Sun\Java\bin;C:\Windows\system32;C:\Windows;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\Java\jdk1.7.0_80\bin;C:\Program Files\Java\jdk1.7.0_80\jre\bin;C:\Program Files (x86)\SSH Communications Security\SSH Secure Shell;.
2016-10-10 11:08:34,059 INFO [org.apache.zookeeper.ZooKeeper] - Client environment:java.io.tmpdir=C:\Users\007\AppData\Local\Temp\
2016-10-10 11:08:34,059 INFO [org.apache.zookeeper.ZooKeeper] - Client environment:java.compiler=<NA>
2016-10-10 11:08:34,059 INFO [org.apache.zookeeper.ZooKeeper] - Client environment:os.name=Windows 7
2016-10-10 11:08:34,059 INFO [org.apache.zookeeper.ZooKeeper] - Client environment:os.arch=amd64
2016-10-10 11:08:34,059 INFO [org.apache.zookeeper.ZooKeeper] - Client environment:os.version=6.1
2016-10-10 11:08:34,059 INFO [org.apache.zookeeper.ZooKeeper] - Client environment:user.name=007
2016-10-10 11:08:34,059 INFO [org.apache.zookeeper.ZooKeeper] - Client environment:user.home=C:\Users\007
2016-10-10 11:08:34,059 INFO [org.apache.zookeeper.ZooKeeper] - Client environment:user.dir=E:\myself_data\motan-pro-clicent
2016-10-10 11:08:34,059 INFO [org.apache.zookeeper.ZooKeeper] - Initiating client connection, connectString=10.0.20.236:2181 sessionTimeout=60000 watcher=org.I0Itec.zkclient.ZkClient@5c8f9ca4
2016-10-10 11:08:34,062 DEBUG [org.apache.zookeeper.ClientCnxn] - zookeeper.disableAutoWatchReset is false
2016-10-10 11:08:34,088 DEBUG [org.I0Itec.zkclient.ZkClient] - Awaiting connection to Zookeeper server
2016-10-10 11:08:34,088 DEBUG [org.I0Itec.zkclient.ZkClient] - Waiting for keeper state SyncConnected
2016-10-10 11:08:34,090 INFO [org.apache.zookeeper.ClientCnxn] - Opening socket connection to server 10.0.20.236/10.0.20.236:2181. Will not attempt to authenticate using SASL (unknown error)
2016-10-10 11:08:34,091 INFO [org.apache.zookeeper.ClientCnxn] - Socket connection established to 10.0.20.236/10.0.20.236:2181, initiating session
2016-10-10 11:08:34,092 DEBUG [org.apache.zookeeper.ClientCnxn] - Session establishment request sent on 10.0.20.236/10.0.20.236:2181
2016-10-10 11:08:34,245 INFO [org.apache.zookeeper.ClientCnxn] - Session establishment complete on server 10.0.20.236/10.0.20.236:2181, sessionid = 0x157ac67e2950003, negotiated timeout = 40000
2016-10-10 11:08:34,248 DEBUG [org.I0Itec.zkclient.ZkClient] - Received event: WatchedEvent state:SyncConnected type:None path:null
2016-10-10 11:08:34,248 INFO [org.I0Itec.zkclient.ZkClient] - zookeeper state changed (SyncConnected)
2016-10-10 11:08:34,248 DEBUG [org.I0Itec.zkclient.ZkClient] - Leaving process event
2016-10-10 11:08:34,248 DEBUG [org.I0Itec.zkclient.ZkClient] - State is SyncConnected
2016-10-10 11:08:34,264 INFO [info] - CommandFailbackRegistry init. url: zookeeper://10.0.20.236:2181/com.weibo.api.motan.registry.RegistryService?group=default_rpc
2016-10-10 11:08:34,270 INFO [info] - [ZookeeperRegistry] Listener (com.weibo.api.motan.cluster.support.ClusterSupport@7f90166) will subscribe to url (motan://10.0.20.236:0/com.lvxl.motan.service.AreaService?group=default_rpc) in Registry [zookeeper://10.0.20.236:2181/default_rpc/com.weibo.api.motan.registry.RegistryService/1.0/service]
2016-10-10 11:08:34,270 INFO [info] - CommandFailbackRegistry subscribe. url: motan://10.0.20.236:0/com.lvxl.motan.service.AreaService?group=default_rpc
2016-10-10 11:08:34,271 INFO [info] - CommandServiceManager init url:motan://10.0.20.236:0/com.lvxl.motan.service.AreaService?id=areaService&maxClientConnection=10&protocol=motan&isDefault=true&singleton=true&minClientConnection=2&refreshTimestamp=1476068914032&haStrategy=failover&nodeType=service&loadbalance=localFirst&version=1.0&
2016-10-10 11:08:34,278 DEBUG [org.apache.zookeeper.ClientCnxn] - Reading reply sessionid:0x157ac67e2950003, packet:: clientPath:null serverPath:null finished:false header:: 1,3  replyHeader:: 1,17,-101  request:: '/motan/default_rpc/com.lvxl.motan.service.AreaService/client/10.0.20.236,F  response::  
2016-10-10 11:08:34,281 DEBUG [org.apache.zookeeper.ClientCnxn] - Reading reply sessionid:0x157ac67e2950003, packet:: clientPath:null serverPath:null finished:false header:: 2,3  replyHeader:: 2,17,0  request:: '/motan/default_rpc/com.lvxl.motan.service.AreaService/client,F  response:: s{11,11,1476066908872,1476066908872,0,2,0,0,0,0,13} 
2016-10-10 11:08:34,299 DEBUG [org.apache.zookeeper.ClientCnxn] - Reading reply sessionid:0x157ac67e2950003, packet:: clientPath:null serverPath:null finished:false header:: 3,1  replyHeader:: 3,18,0  request:: '/motan/default_rpc/com.lvxl.motan.service.AreaService/client/10.0.20.236,#ffffffacffffffed0574196d6f74616e3a2f2f31302e302e32302e3233363a302f636f6d2e6c76786c2e6d6f74616e2e736572766963652e41726561536572766963653f69643d6172656153657276696365266d6178436c69656e74436f6e6e656374696f6e3d31302670726f746f636f6c3d6d6f74616e26697344656661756c743d747275652673696e676c65746f6e3d74727565266d696e436c69656e74436f6e6e656374696f6e3d32267265667265736854696d657374616d703d3134373630363839313430333226686153747261746567793d6661696c6f766572266e6f6465547970653d73657276696365266c6f616462616c616e63653d6c6f63616c46697273742676657273696f6e3d312e3026,v{s{31,s{'world,'anyone}}},1  response:: '/motan/default_rpc/com.lvxl.motan.service.AreaService/client/10.0.20.236 
2016-10-10 11:08:34,301 DEBUG [org.apache.zookeeper.ClientCnxn] - Reading reply sessionid:0x157ac67e2950003, packet:: clientPath:null serverPath:null finished:false header:: 4,3  replyHeader:: 4,18,-101  request:: '/motan/default_rpc/com.lvxl.motan.service.AreaService/server,T  response::  
2016-10-10 11:08:34,303 DEBUG [org.apache.zookeeper.ClientCnxn] - Reading reply sessionid:0x157ac67e2950003, packet:: clientPath:null serverPath:null finished:false header:: 5,8  replyHeader:: 5,18,-101  request:: '/motan/default_rpc/com.lvxl.motan.service.AreaService/server,T  response:: v{} 
2016-10-10 11:08:34,309 INFO [info] - [ZookeeperRegistry] subscribe service: path=/motan/default_rpc/com.lvxl.motan.service.AreaService/server/10.0.20.236, info=motan://10.0.20.236:0/com.lvxl.motan.service.AreaService?id=areaService&maxClientConnection=10&protocol=motan&isDefault=true&singleton=true&minClientConnection=2&refreshTimestamp=1476068914032&haStrategy=failover&nodeType=service&loadbalance=localFirst&version=1.0&
2016-10-10 11:08:34,311 DEBUG [org.apache.zookeeper.ClientCnxn] - Reading reply sessionid:0x157ac67e2950003, packet:: clientPath:null serverPath:null finished:false header:: 6,3  replyHeader:: 6,18,-101  request:: '/motan/default_rpc/command,T  response::  
2016-10-10 11:08:34,311 DEBUG [org.I0Itec.zkclient.ZkClient] - Subscribed data changes for /motan/default_rpc/command
2016-10-10 11:08:34,311 INFO [info] - [ZookeeperRegistry] subscribe command: path=/motan/default_rpc/command, info=motan://10.0.20.236:0/com.lvxl.motan.service.AreaService?id=areaService&maxClientConnection=10&protocol=motan&isDefault=true&singleton=true&minClientConnection=2&refreshTimestamp=1476068914032&haStrategy=failover&nodeType=service&loadbalance=localFirst&version=1.0&
2016-10-10 11:08:34,311 INFO [info] - CommandFailbackRegistry discover. url: motan://10.0.20.236:0/com.lvxl.motan.service.AreaService?group=default_rpc
2016-10-10 11:08:34,312 DEBUG [org.apache.zookeeper.ClientCnxn] - Reading reply sessionid:0x157ac67e2950003, packet:: clientPath:null serverPath:null finished:false header:: 7,3  replyHeader:: 7,18,-101  request:: '/motan/default_rpc/command,T  response::  
2016-10-10 11:08:34,312 INFO [info] - CommandFailbackRegistry discover command. commandStr: , rpccommand is null.
2016-10-10 11:08:34,313 DEBUG [org.apache.zookeeper.ClientCnxn] - Reading reply sessionid:0x157ac67e2950003, packet:: clientPath:null serverPath:null finished:false header:: 8,3  replyHeader:: 8,18,-101  request:: '/motan/default_rpc/com.lvxl.motan.service.AreaService/server,T  response::  
2016-10-10 11:08:34,313 INFO [info] - CommandFailbackRegistry discover size: 0, result:[]
Exception in thread "main" org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'areaService': FactoryBean threw exception on object creation; nested exception is com.weibo.api.motan.exception.MotanFrameworkException: error_message: ClusterSupport No service urls for the refer:motan://10.0.20.236:0/default_rpc/com.lvxl.motan.service.AreaService/1.0/referer, registries:[zookeeper://10.0.20.236:2181/com.weibo.api.motan.registry.RegistryService?group=default_rpc], status: 404, error_code: 10101,r=null
    at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.doGetObjectFromFactoryBean(FactoryBeanRegistrySupport.java:173)
    at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.getObjectFromFactoryBean(FactoryBeanRegistrySupport.java:102)
    at org.springframework.beans.factory.support.AbstractBeanFactory.getObjectForBeanInstance(AbstractBeanFactory.java:1465)
    at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:246)
    at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:191)
    at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1119)
    at com.lvxl.motan.main.App.main(App.java:17)
Caused by: com.weibo.api.motan.exception.MotanFrameworkException: error_message: ClusterSupport No service urls for the refer:motan://10.0.20.236:0/default_rpc/com.lvxl.motan.service.AreaService/1.0/referer, registries:[zookeeper://10.0.20.236:2181/com.weibo.api.motan.registry.RegistryService?group=default_rpc], status: 404, error_code: 10101,r=null
    at com.weibo.api.motan.cluster.support.ClusterSupport.init(ClusterSupport.java:102)
    at com.weibo.api.motan.config.handler.SimpleConfigHandler.buildClusterSupport(SimpleConfigHandler.java:55)
    at com.weibo.api.motan.config.RefererConfig.createClusterSupport(RefererConfig.java:184)
    at com.weibo.api.motan.config.RefererConfig.initRef(RefererConfig.java:128)
    at com.weibo.api.motan.config.RefererConfig.getRef(RefererConfig.java:85)
    at com.weibo.api.motan.config.springsupport.RefererConfigBean.getObject(RefererConfigBean.java:44)
    at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.doGetObjectFromFactoryBean(FactoryBeanRegistrySupport.java:166)
    ... 6 more
2016-10-10 11:08:47,646 DEBUG [org.apache.zookeeper.ClientCnxn] - Got ping response for sessionid: 0x157ac67e2950003 after 0ms

**Comment by rayzhang0603** [comment]
server端没有正确注册。请确认
1、server端的提供服务开关是否打开了。

MotanSwitcherUtil.setSwitcherValue(MotanConstants.REGISTRY_HEARTBEAT_SWITCHER, true);
2、确认server端配置的group、version、protocol是否与client端一致。

3、确认server端是否正确注册到zk注册中心
通过manage后台，或者直接查看zk的/motan/${group}/${service}/server路径下看是否有提供服务的节点。

**Comment by lxlbarnett** [comment]
### server配置：

<motan:registry regProtocol="zookeeper" name="my_zookeeper" address="10.0.20.236:2181"/>
<bean id="areaServiceImpl" class="com.lvxl.motan.service.impl.AreaServiceImpl" />
<motan:protocol id="demoMotan" loadbalance="localFirst" name="motan" maxWorkerThread="800" 
   minWorkerThread="20" maxClientConnection="10" minClientConnection="2"/>
<motan:basicService id="serviceBasicConfig" export="demoMotan:8002" registry="my_zookeeper"/> <motan:service interface="com.lvxl.motan.service.AreaService" ref="areaServiceImpl" basicService="serviceBasicConfig"/>

###客服端配置：
<motan:registry regProtocol="zookeeper"  name="my_zookeeper" address="10.0.20.236:2181" />
<motan:protocol default="true" name="motan" haStrategy="failover"
 loadbalance="localFirst" maxClientConnection="10" minClientConnection="2" />
 <motan:basicReferer id="clientBasicConfig"  protocol="motan" registry="my_zookeeper"  />
 <motan:referer id="areaService" interface="com.lvxl.motan.service.AreaService"  basicReferer="clientBasicConfig"/>
@rayzhang0603

**Comment by rayzhang0603** [comment]
从你的日志看，server并没有注册到注册中心，检查zk的/motan/default_rpc/com.lvxl.motan.service.AreaService/server路径下是否有server的ip

**Comment by lxlbarnett** [comment]
@rayzhang0603 从检测工具可以看到服务的motan有服务注册呀
[
![qq 20161010144520](https://cloud.githubusercontent.com/assets/9713658/19228479/455eeac0-8ef8-11e6-8411-5bf1cb5585ad.png)
](url)

**Comment by caipanjin** [comment]
遇到同样的问题，版本0.2.1！zk服务下有unavailableServer, client节点，没有server节点，到底啥原因啊？

**Comment by rayzhang0603** [comment]
server端启动完成后，需要打开心跳开关，之后server的状态会从unavailable状态变更为working状态。
打开心跳方式：

    MotanSwitcherUtil.setSwitcherValue(MotanConstants.REGISTRY_HEARTBEAT_SWITCHER, true);

**Comment by caipanjin** [comment]
@rayzhang0603 是打开的：
```java
public static void main(String[] args) {

        ConfigurableApplicationContext ctx = new ClassPathXmlApplicationContext("classpath:META-INF/spring/context_cds_comments.xml");
        ctx.addApplicationListener(new ApplicationListener<ContextRefreshedEvent>(){

            public void onApplicationEvent(ContextRefreshedEvent event) {
                MotanSwitcherUtil.setSwitcherValue(MotanConstants.REGISTRY_HEARTBEAT_SWITCHER, true);
            }
        });
        ctx.registerShutdownHook();
    }
```

**Comment by caipanjin** [comment]
@rayzhang0603 刚试了一下，这样写就没问题了：
```java
ConfigurableApplicationContext ctx = new ClassPathXmlApplicationContext("classpath:META-INF/spring/context_cds_comments.xml");
        MotanSwitcherUtil.setSwitcherValue(MotanConstants.REGISTRY_HEARTBEAT_SWITCHER, true);
        ctx.registerShutdownHook();
```

**Comment by rayzhang0603** [comment]
应该是开关打开的时机的问题，现在是初始化server完成后监听开关状态变化的，需要在spring初始化后打开开关。后续会优化一下这里，先检查一下开关状态。
