### ISSUE TITLE
使用zookeeper注册中心，客户端报error_message: NettyResponseFuture request timeout，再次调用正常

### ISSUE THREAD

**Issue by lbhuanggua** [weibocom/motan#219]
第一次调用接口时报下面的错误信息，返回值null，服务端被调用，再一次调用正常了。下面是客户端日志，服务端正常。不知道怎么回事？是配置问题吗？

服务端配置：
 `<motan:registry regProtocol="zookeeper" name="registry" address="127.0.0.1:2181" connectTimeout="2000"/>
 <motan:protocol id="demoMotan" default="true" name="motan"
                    maxServerConnection="80000" maxContentLength="1048576"
                    maxWorkerThread="800" minWorkerThread="20"/>
<motan:basicService id="serviceBasicConfig" export="demoMotan:8001"
                        group="motan-demo-rpc" accessLog="false" shareChannel="true" module="motan-demo-rpc"
                        application="myMotanDemo" registry="registry" />
<motan:service interface="com.lb.framework.api.service.DemoService" ref="demoService" registry="registry" export="demoMotan:8002" basicService="serviceBasicConfig"/>`
客户端配置：
`<motan:registry regProtocol="zookeeper" name="registry" address="127.0.0.1:2181" connectTimeout="2000"/>
<motan:protocol default="true" name="motan" haStrategy="failover"
                    loadbalance="roundrobin" maxClientConnection="10" minClientConnection="2"/>
    <motan:basicReferer id="motantestClientBasicConfig" requestTimeout="200" connectTimeout="300" accessLog="true"
                        retries="2" group="motan-demo-rpc" module="motan-demo-rpc"
                        application="myMotanDemo" protocol="motan" registry="registry"
                        throwException="false" check="true"/>
<motan:referer id="demoService" interface="com.lb.framework.api.service.DemoService" 
        basicReferer="motantestClientBasicConfig" />`
客户端日志：
`
2016-10-10 11:13:46,325 WARN[com.weibo.api.motan.log.DefaultLogService:67]- FailoverHaStrategy Call false for request:com.lb.framework.api.service.DemoService.sayHello(void) requestId=1547770764727418881 error=error_message: NettyResponseFuture request timeout: serverPort=169.254.80.80:8002 requestId=1547770764727418881 interface=com.lb.framework.api.service.DemoService method=sayHello(void) cost=303, status: 503, error_code: 10003,r=null
2016-10-10 11:13:46,627 WARN[com.weibo.api.motan.log.DefaultLogService:67]- FailoverHaStrategy Call false for request:com.lb.framework.api.service.DemoService.sayHello(void) requestId=1547770764727418881 error=error_message: NettyResponseFuture request timeout: serverPort=169.254.80.80:8002 requestId=1547770764727418881 interface=com.lb.framework.api.service.DemoService method=sayHello(void) cost=300, status: 503, error_code: 10003,r=null
2016-10-10 11:13:46,931 WARN[com.weibo.api.motan.log.DefaultLogService:75]- RefererInvocationHandler invoke false, so return default value: uri=motan://169.254.80.80:0/com.lb.framework.api.service.DemoService requestId=1547770764727418881 interface=com.lb.framework.api.service.DemoService method=sayHello(void)
com.weibo.api.motan.exception.MotanServiceException: error_message: NettyResponseFuture request timeout: serverPort=169.254.80.80:8002 requestId=1547770764727418881 interface=com.lb.framework.api.service.DemoService method=sayHello(void) cost=300, status: 503, error_code: 10003,r=null
    at com.weibo.api.motan.transport.netty.NettyResponseFuture.timeoutSoCancel(NettyResponseFuture.java:234)
    at com.weibo.api.motan.transport.netty.NettyResponseFuture.getValue(NettyResponseFuture.java:137)
    at com.weibo.api.motan.rpc.DefaultResponse.<init>(DefaultResponse.java:54)
    at com.weibo.api.motan.transport.netty.NettyClient.asyncResponse(NettyClient.java:204)
    at com.weibo.api.motan.transport.netty.NettyClient.request(NettyClient.java:187)
    at com.weibo.api.motan.transport.netty.NettyClient.request(NettyClient.java:116)
    at com.weibo.api.motan.protocol.rpc.DefaultRpcProtocol$DefaultRpcReferer.doCall(DefaultRpcProtocol.java:171)
    at com.weibo.api.motan.rpc.AbstractReferer.call(AbstractReferer.java:64)
    at com.weibo.api.motan.cluster.ha.FailoverHaStrategy.call(FailoverHaStrategy.java:72)
    at com.weibo.api.motan.cluster.support.ClusterSpi.call(ClusterSpi.java:73)
    at com.weibo.api.motan.proxy.RefererInvocationHandler.invoke(RefererInvocationHandler.java:108)
    at com.sun.proxy.$Proxy17.sayHello(Unknown Source)
    at com.lb.framework.client.controller.ClientController.demo(ClientController.java:53)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:221)
    at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:137)
    at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:111)
    at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:806)
    at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:729)
    at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
    at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:959)
    at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:893)
    at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
    at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:620)
    at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
    at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
    at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:85)
    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:503)
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
    at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950)
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:421)
    at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1070)
    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:611)
    at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:314)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
    at java.lang.Thread.run(Thread.java:745)
2016-10-10 11:13:55,437 WARN[com.weibo.api.motan.log.DefaultLogService:71]- NettyClient has response from server, but resonseFuture not exist,  requestId=1547770764727418881
2016-10-10 11:13:55,439 WARN[com.weibo.api.motan.log.DefaultLogService:71]- NettyClient has response from server, but resonseFuture not exist,  requestId=1547770764727418881
2016-10-10 11:13:55,440 WARN[com.weibo.api.motan.log.DefaultLogService:71]- NettyClient has response from server, but resonseFuture not exist,  requestId=1547770764727418881`

**Comment by rayzhang0603** [comment]
配置超时时间为300ms，首次调用超时了。从日志看11:13:46,325发出的请求，11:13:55,437 才收到server端回复。
如果server端没有耗时逻辑的话，可能跟client端和server端初始化、类加载、网络状况等有关。可以打开server端accesslog日志确认server端纯业务耗时情况。

**Comment by lbhuanggua** [comment]
日志如下：
`2016-10-11 18:16:30,276 INFO[com.lb.framework.client.controller.ClientController:43]- 客户端开始
2016-10-11 18:16:39,457 INFO[com.weibo.api.motan.log.DefaultLogService:91]- referer|myMotanDemo|motan-demo-rpc|169.254.80.80|com.lb.framework.api.service.UserService|selectUserList|int%2Cint|169.254.80.80|myMotanDemo|motan-demo-rpc|true|0|9173
2016-10-11 18:16:39,747 INFO[com.lb.framework.client.controller.ClientController:47]- 客户端结束,用时：9470 ms`

`2016-10-11 18:16:39,396 INFO[com.lb.framework.core.UserServiceImpl:29]- 服务端开始
2016-10-11 18:16:39,398 DEBUG[org.apache.ibatis.logging.jdbc.BaseJdbcLogger:145]- ==>  Preparing: SELECT \* FROM _user limit ?,? 
2016-10-11 18:16:39,400 DEBUG[org.apache.ibatis.logging.jdbc.BaseJdbcLogger:145]- ==> Parameters: 0(Integer), 50(Integer)
2016-10-11 18:16:39,413 DEBUG[org.apache.ibatis.logging.jdbc.BaseJdbcLogger:145]- <==      Total: 26
2016-10-11 18:16:39,415 INFO[com.lb.framework.core.UserServiceImpl:33]- 服务端结束,用时：18 ms

客户端代码：
`LOG.info("客户端开始");
            long start = System.currentTimeMillis();
            String str = JSON.toJSONString(userService.selectUserList(offset, limit));
            long ss = System.currentTimeMillis() - start;
            LOG.info("客户端结束,用时：" + ss + " ms" );`
我现在把客户端修改成requestTimeout="30000"，第一次调用用时较长，第二次调用就正常了。

**Comment by rayzhang0603** [comment]
估计跟server端首次请求初始化类加载有关，你可以用个最简单的demo测试一下，或者把server端实现改成直接返回一个固定对象试试

**Comment by lbhuanggua** [comment]
我把配置修改成点对点直连的方式却很快。

**Comment by rayzhang0603** [comment]
服务在注册中心注册的ip和直连使用的ip一样吗？按说client启动后就会从注册中心拿到serverip，调用时跟直连是没有区别的。是不是自动注册的ip是公网ip，直连使用的内网IP？

**Comment by lbhuanggua** [comment]
`已经解决，是电脑有2个虚拟交换机（win8系统），项目启动时默认加载序号最小的那个虚拟交换机，而这个虚拟交换机的状态是“未识别的网络”，禁用它，再次启动server，注册到zookeeper的serverip是网络链接正常的虚拟交换机的IP，然后就OK了。
        问题终于解决了，非常感谢，再次感谢！！！`

**Comment by lhl4546** [comment]
大兄弟，这问题有解决吗，我在使用Motan过程中偶现request timeout，但是server端的motanAccessLog显示该业务处理又很快完成了，request timeout设置的5秒，使用zookeeper作为注册中心
