### ISSUE TITLE
报错了，是我配置错了吗？

### ISSUE THREAD

**Issue by JianSphere** [weibocom/motan#227]
```
  <motan:registry regProtocol="direct" name="directRegistry" port="8002" address="${motan.address}" />  
    <motan:basicService requestTimeout="5000" export="direct:2800"
        group="meipian-service" accessLog="false" shareChannel="true" module="meipian-service"
        application="meipian-service"   registry="directRegistry"  id="serviceBasicConfig" />
    <bean id="userPushService" class="com.meipian.push.service.impl.UserPushServiceImpl" />
    <motan:service interface="com.meipian.push.service.contract.IUserPushService"
        ref="userPushService"  timeout="5000"    basicService="serviceBasicConfig" />
</beans>
```

报出错误：

```
Caused by: com.weibo.api.motan.exception.MotanFrameworkException: error_message: cann't find direct ProtocolConfig bean! export:direct:2800, status: 500, error_code: 20004,r=null
    at com.weibo.api.motan.config.springsupport.ServiceConfigBean.checkAndConfigExport(ServiceConfigBean.java:152) ~[motan-springsupport-0.2.1.jar:na]
    at com.weibo.api.motan.config.springsupport.ServiceConfigBean.afterPropertiesSet(ServiceConfigBean.java:69) ~[motan-springsupport-0.2.1.jar:na]
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1642) ~[spring-beans-4.3.3.RELEASE.jar:4.3.3.RELEASE]
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1579) ~[spring-beans-4.3.3.RELEASE.jar:4.3.3.RELEASE]
    ... 13 common frames omitted
```

**Comment by JianSphere** [comment]
我有点蒙圈了。请问export="direct:2800" 中的协议是不是就是motan:registry中的 regProtocol?
我已经指定了注册中心，注册中心已经指定了协议。为什么还要指定一遍？

**Comment by rayzhang0603** [comment]
注册中心协议指zookeeper、consul这种。export中的协议指rpc通信协议，例如motan。需要配置motan:protocol标签。
export中指定协议是为了支持一个服务实现对外提供多种协议的服务。例如export="motan:8002,yar:8003"
配置请参考用户指南 https://github.com/weibocom/motan/wiki/zh_userguide 以及motan-demo模块

**Comment by JianSphere** [comment]
服务器配置了motan:registry 与Protocol，是不是客户端还需要配置一遍？
