### ISSUE TITLE
做远程调用的时候服务端报错：sun.nio.ch.SocketDispatcher.read0

### ISSUE THREAD

**Issue by mark988** [weibocom/motan#238]
客户端调用服务端时后，报错信息如下：
2016-10-18 15:10:06,898 ERROR New I/O server worker #1-5 (error:87) - NettyChannelHandler exceptionCaught: remote=/172.29.32.168:58384 local=/172.29.32.168:9000 event=java.io.IOException: 远程主机强迫关闭了一个现有的连接。
java.io.IOException: 远程主机强迫关闭了一个现有的连接。
    at sun.nio.ch.SocketDispatcher.read0(Native Method) ~[?:1.8.0_101]
    at sun.nio.ch.SocketDispatcher.read(Unknown Source) ~[?:1.8.0_101]
    at sun.nio.ch.IOUtil.readIntoNativeBuffer(Unknown Source) ~[?:1.8.0_101]
    at sun.nio.ch.IOUtil.read(Unknown Source) ~[?:1.8.0_101]
    at sun.nio.ch.SocketChannelImpl.read(Unknown Source) ~[?:1.8.0_101]
    at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:321) ~[netty-3.2.5.Final.jar:?]
    at org.jboss.netty.channel.socket.nio.NioWorker.processSelectedKeys(NioWorker.java:280) ~[netty-3.2.5.Final.jar:?]
    at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:200) ~[netty-3.2.5.Final.jar:?]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_101]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_101]
    at java.lang.Thread.run(Unknown Source) [?:1.8.0_101]
这个什么原因？怎么解决？

**Comment by mark988** [comment]
我用的tomcat服务器。

**Comment by mark988** [comment]
麻烦这边的支持人员，能不能留下QQ啊？或者创建一个QQ群？互相讨论一下

**Comment by rayzhang0603** [comment]
应该是client端主动关闭了链接。可以查看一下client端的日志，看是不是因为client端超时，导致回收了channel

**Comment by mark988** [comment]
客户端可以设置超时时间吗？
