### ISSUE TITLE
远程调用报错

### ISSUE THREAD

**Issue by mark988** [weibocom/motan#239]
服务方、客户端修改成了zookeeper注册服务方式（单个zookeeper） .
服务方配置文件：

```
<motan:registry regProtocol="zookeeper" name="my_zookeeper" address="172.28.70.47:2181"/>
<motan:service interface="com.mxg.base.service.users.UsersServiceI" ref="usersSerice" registry="my_zookeeper" export="9000" />
```

客户端配置文件：
<motan:registry regProtocol="zookeeper" name="my_zookeeper" address="172.28.70.47:2181"/>

```
<motan:referer id="usersSerice" interface="com.mxg.base.service.users.UsersServiceI" registry="my_zookeeper" />
```

服务端启动正常。客户端启动报错如下：
十月 18, 2016 4:20:50 下午 com.weibo.api.motan.log.DefaultLogService info
信息: CommandFailbackRegistry discover. url: motan://172.29.32.168:0/com.mxg.base.service.users.UsersServiceI?group=default_rpc
[org.I0Itec.zkclient.ZkClient]Subscribed data changes for /motan/default_rpc/command
十月 18, 2016 4:20:50 下午 com.weibo.api.motan.log.DefaultLogService info
信息: CommandFailbackRegistry discover command. commandStr: , rpccommand is null.
十月 18, 2016 4:20:50 下午 com.weibo.api.motan.log.DefaultLogService info
信息: CommandFailbackRegistry discover size: 0, result:[]
[org.springframework.web.context.support.XmlWebApplicationContext]Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'testController': Unsatisfied dependency expressed through field 'usersServiceI'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'usersSerice': FactoryBean threw exception on object creation; nested exception is com.weibo.api.motan.exception.MotanFrameworkException: error_message: ClusterSupport No service urls for the refer:motan://172.29.32.168:0/default_rpc/com.mxg.base.service.users.UsersServiceI/1.0/referer, registries:[zookeeper://172.28.70.47:2181/com.weibo.api.motan.registry.RegistryService?group=default_rpc], status: 404, error_code: 10101,r=null
[org.springframework.beans.factory.support.DefaultListableBeanFactory]Destroying singletons in org.springframework.beans.factory.support.DefaultListableBeanFactory@a41638e: defining beans [org.springframework.beans.factory.config.PropertyPlaceholderConfigurer#0,testController,org.springframework.context.annotation.internalConfigurationAnnotationProcessor,org.springframework.context.annotation.internalAutowiredAnnotationProcessor,org.springframework.context.annotation.internalRequiredAnnotationProcessor,org.springframework.context.annotation.internalCommonAnnotationProcessor,org.springframework.context.event.internalEventListenerProcessor,org.springframework.context.event.internalEventListenerFactory,my_zookeeper,usersSerice,org.springframework.context.annotation.ConfigurationClassPostProcessor.importAwareProcessor,org.springframework.context.annotation.ConfigurationClassPostProcessor.enhancedConfigurationProcessor]; root of factory hierarchy
[org.springframework.beans.factory.support.DisposableBeanAdapter]Invoking destroy() on bean with name 'usersSerice'
[org.springframework.web.context.ContextLoader]Context initialization failed
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'testController': Unsatisfied dependency expressed through field 'usersServiceI'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'usersSerice': FactoryBean threw exception on object creation; nested exception is com.weibo.api.motan.exception.MotanFrameworkException: error_message: ClusterSupport No service urls for the refer:motan://172.29.32.168:0/default_rpc/com.mxg.base.service.users.UsersServiceI/1.0/referer, registries:[zookeeper://172.28.70.47:2181/com.weibo.api.motan.registry.RegistryService?group=default_rpc], status: 404, error_code: 10101,r=null
    at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:569)
    at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:88)
    at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:349)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1219)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:543)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
    at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
    at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
    at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
    at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
    at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:751)
    at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:861)
    at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:541)
    at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:444)
    at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:326)
    at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:107)
    at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4842)
    at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5303)
    at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:147)
    at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:725)
    at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:701)
    at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717)
    at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1092)
    at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1834)
    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
    at java.util.concurrent.FutureTask.run(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)

**Comment by rayzhang0603** [comment]
是不是server端没有打开心跳开关？
    MotanSwitcherUtil.setSwitcherValue(MotanConstants.REGISTRY_HEARTBEAT_SWITCHER, true)

参见https://github.com/weibocom/motan/wiki/zh_quickstart#使用zookeeper作为注册中心  第四步

**Comment by mark988** [comment]
打开心跳开关，必须写道代码里吗？？？？

**Comment by mark988** [comment]
我把心跳开关这个代码写道了这个服务里，代码如下：
我直接在UsersServiceImpl.java 文件列这样写的。  
static {
        MotanSwitcherUtil.initSwitcher(MotanConstants.REGISTRY_HEARTBEAT_SWITCHER, true);
    }

**Comment by mark988** [comment]
你好，可以留下你的QQ吗？ 或者你加我一下行吗？QQ：80692072

**Comment by rayzhang0603** [comment]
可以下载源代码，参考motan-demo模块的motan_demo_server.xml、motan_demo_client.xml配置方式。可以运行DemoRpcServer、DemoRpcClient来进行测试。
参数的说明请参考https://github.com/weibocom/motan/wiki/zh_userguide#配置说明  及https://github.com/weibocom/motan/wiki/zh_configuration

**Comment by mark988** [comment]
我按源码提供的例子配置的zookeeper， 客户端一直无法启动。
zookeeper配置信息和例子完全相同。

**Comment by sun152121** [comment]
问题解决了吗，我跑demo也是这个报错！
