### ISSUE TITLE
motan客户端应用调试（断点）过程中，控制台会输出接口类Service method not exist：toString（）异常，开发工具是intelliJidea 15

### ISSUE THREAD

**Issue by gaoke966** [weibocom/motan#248]
报如下错误
com.weibo.api.motan.exception.MotanServiceException: error_message: Service method not exist: com.XXXApi.toString(void), status: 404, error_code: 10101,r=null
at com.weibo.api.motan.rpc.DefaultProvider.invoke(DefaultProvider.java:48)
    at com.weibo.api.motan.rpc.AbstractProvider.call(AbstractProvider.java:47)
    at com.weibo.api.motan.transport.ProviderMessageRouter.call(ProviderMessageRouter.java:96)
    at com.weibo.api.motan.transport.ProviderProtectedMessageRouter.call(ProviderProtectedMessageRouter.java:82)
    at com.weibo.api.motan.transport.ProviderMessageRouter.handle(ProviderMessageRouter.java:91)
    at com.weibo.api.motan.transport.support.DefaultRpcHeartbeatFactory$HeartMessageHandleWrapper.handle(DefaultRpcHeartbeatFactory.java:82)
    at com.weibo.api.motan.transport.netty.NettyChannelHandler.processRequest(NettyChannelHandler.java:139)
    at com.weibo.api.motan.transport.netty.NettyChannelHandler.access$000(NettyChannelHandler.java:47)
    at com.weibo.api.motan.transport.netty.NettyChannelHandler$1.run(NettyChannelHandler.java:116)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:744)
请问有没有遇到的，该如何解决

**Comment by rayzhang0603** [comment]
这个是因为idea调试时调用了rpc对象的toString方法，导致tostirng方法调用到了远程。
这块应该对要进行远程调用的方法进行判断，例如toString、equals等方法，如果接口中没有声明就不在进行远程调用。
后续版本会修正这个问题，也欢迎PR

**Comment by gaoke966** [comment]
我在DefaultProvider类的invoke方法体内第二行加上了下面的判断，有点简单粗暴，但可以作为临时方案解决问题：if("toString".equals(request.getMethodName())) {
            //这里仅仅是粗暴的将toString过滤掉，直接返回，可以简单解决问题，但是对于接口中有用到toString方法等情况（或其他未知情况）时会有影响
            return response;
        }

**Comment by rayzhang0603** [comment]
可以在RefererInvocationHandler中的invoke方法中做是否远程方法的判断，这样请求不会发送到server端。
我提交了一个branch，你可以试用一下，主要的修改在RefererInvocationHandler类
https://github.com/weibocom/motan/tree/feature/localMethodInvoke

**Comment by rayzhang0603** [comment]
0.2.2版本已经修复，欢迎使用
