### ISSUE TITLE
在IDEA 16下调试消费端时,打断点会多一次toString()方法的请求，出现status: 404, error_code: 10101

### ISSUE THREAD

**Issue by estn** [weibocom/motan#276]
```java
@RestController
public class DeviceController {

    @MotanReferer(basicReferer = "basicRefererFoundation")
    private DeviceService deviceService;

    @RequestMapping
    public Device getById() {
        return deviceService.getById(15L);
    }

}
```
在" return deviceService.getById(15L);" 这行打断点后，从日志看出要多一次请求，会去请求toString()方法。但是在服务端并没有toString()方法.结果就出现了以下异常信息

2016-11-09 10:16:03 [pool-5-thread-1] INFO  [serviceStatsLog:99] -[motan-accessStatistic] app: foundation-client module: cd-foundation-rpc-client item: motan://cd-foundation-rpc_com.zuoliubo.service.foundation.service.DeviceService.getById(java.lang.Long) total_count: 2 slow_count: 2 p75: 114.00 p95: 132.00 p98: 132.00 p99: 132.00 p999: 132.00 biz_excp: 0 other_excp: 0 avg_time: 63.00ms biz_time: 61.00ms avg_tps: 0 max_tps: 1 min_tps: 0 
2016-11-09 10:16:03 [pool-5-thread-1] INFO  [serviceStatsLog:95] <strong>-[motan-accessStatistic] app: foundation-client module: cd-foundation-rpc-client item: motan://cd-foundation-rpc_com.zuoliubo.service.foundation.service.DeviceService.toString(void) total_count: 0 slow_count: 0 biz_excp: 0 other_excp: 0 avg_time: 0.00ms biz_time: 0.00ms avg_tps: 0 max_tps: 0 min_tps: 0</strong>
2016-11-09 10:16:03 [pool-5-thread-1] INFO  [serviceStatsLog:99] -[motan-totalAccessStatistic] app: foundation-client module: cd-foundation-rpc-client total_count: 2 slow_count: 2 p75: 114.00 p95: 201.00 p98: 201.00 p99: 201.00 p999: 201.00 biz_excp: 0 other_excp: 0 avg_time: 63.00ms biz_time: 61.00ms avg_tps: 0
2016-11-09 10:16:03 [pool-5-thread-1] INFO  [serviceStatsLog:99] -[motan-memoryStatistic] 52.83MB of 1820.50 MB (2.9%) used 
2016-11-09 10:16:03 [http-nio-8082-exec-5] DEBUG [org.springframework.boot.web.filter.OrderedRequestContextFilter:114] -Bound request context to thread: org.apache.catalina.connector.RequestFacade@21d940a6
2016-11-09 10:16:03 [http-nio-8082-exec-5] DEBUG [org.springframework.web.servlet.DispatcherServlet:865] -DispatcherServlet with name 'dispatcherServlet' processing GET request for [/]
2016-11-09 10:16:03 [http-nio-8082-exec-5] DEBUG [org.springframework.boot.actuate.endpoint.mvc.EndpointHandlerMapping:310] -Looking up handler method for path /
2016-11-09 10:16:03 [http-nio-8082-exec-5] DEBUG [org.springframework.boot.actuate.endpoint.mvc.EndpointHandlerMapping:320] -Did not find handler method for [/]
2016-11-09 10:16:03 [http-nio-8082-exec-5] DEBUG [org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping:310] -Looking up handler method for path /
2016-11-09 10:16:03 [http-nio-8082-exec-5] DEBUG [org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping:317] -Returning handler method [public con.zuoliubo.service.foundation.domain.jpa.Device com.zuoliubo.service.motan.client.rest.DeviceController.getById()]
2016-11-09 10:16:03 [http-nio-8082-exec-5] DEBUG [org.springframework.beans.factory.support.DefaultListableBeanFactory:251] -Returning cached instance of singleton bean 'deviceController'
2016-11-09 10:16:03 [http-nio-8082-exec-5] DEBUG [org.springframework.web.servlet.DispatcherServlet:951] -Last-Modified value for [/] is: -1
2016-11-09 10:16:03 [http-nio-8082-exec-5] INFO  [accessLog:91] -referer|foundation|cd-foundation-rpc|192.168.199.103|com.zuoliubo.service.foundation.service.DeviceService|toString|void|192.168.199.103|foundation|cd-foundation-rpc|false|0|4
2016-11-09 10:16:03 [http-nio-8082-exec-5] ERROR [error:87] -RefererInvocationHandler invoke Error: uri=motan://192.168.199.103:0/com.zuoliubo.service.foundation.service.DeviceService requestId=1550485043422429194 interface=com.zuoliubo.service.foundation.service.DeviceService method=toString(void)
com.weibo.api.motan.exception.MotanServiceException: error_message: Service method not exist: com.zuoliubo.service.foundation.service.DeviceService.toString(void), status: 404, error_code: 10101,r=null
	at com.weibo.api.motan.rpc.DefaultProvider.invoke(DefaultProvider.java:48)
	at com.weibo.api.motan.rpc.AbstractProvider.call(AbstractProvider.java:47)
	at com.weibo.api.motan.filter.AccessStatisticFilter.filter(AccessStatisticFilter.java:41)
	at com.weibo.api.motan.protocol.support.ProtocolFilterDecorator$2.call(ProtocolFilterDecorator.java:150)
	at com.weibo.api.motan.filter.AccessLogFilter.filter(AccessLogFilter.java:56)
	at com.weibo.api.motan.protocol.support.ProtocolFilterDecorator$2.call(ProtocolFilterDecorator.java:150)
	at com.weibo.api.motan.transport.ProviderMessageRouter.call(ProviderMessageRouter.java:96)
	at com.weibo.api.motan.transport.ProviderProtectedMessageRouter.call(ProviderProtectedMessageRouter.java:82)
	at com.weibo.api.motan.transport.ProviderMessageRouter.handle(ProviderMessageRouter.java:91)
	at com.weibo.api.motan.transport.support.DefaultRpcHeartbeatFactory$HeartMessageHandleWrapper.handle(DefaultRpcHeartbeatFactory.java:82)
	at com.weibo.api.motan.transport.netty.NettyChannelHandler.processRequest(NettyChannelHandler.java:139)
	at com.weibo.api.motan.transport.netty.NettyChannelHandler.access$000(NettyChannelHandler.java:47)
	at com.weibo.api.motan.transport.netty.NettyChannelHandler$1.run(NettyChannelHandler.java:116)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
2016-11-09 10:16:03 [http-nio-8082-exec-5] INFO  [accessLog:91] -referer|foundation|cd-foundation-rpc|192.168.199.103|com.zuoliubo.service.foundation.service.DeviceService|toString|void|192.168.199.103|foundation|cd-foundation-rpc|false|0|4
2016-11-09 10:16:03 [http-nio-8082-exec-5] ERROR [error:87] -RefererInvocationHandler invoke Error: uri=motan://192.168.199.103:0/com.zuoliubo.service.foundation.service.DeviceService requestId=1550485043432914955 interface=com.zuoliubo.service.foundation.service.DeviceService method=toString(void)
com.weibo.api.motan.exception.MotanServiceException: error_message: Service method not exist: com.zuoliubo.service.foundation.service.DeviceService.toString(void), status: 404, error_code: 10101,r=null
	at com.weibo.api.motan.rpc.DefaultProvider.invoke(DefaultProvider.java:48)
	at com.weibo.api.motan.rpc.AbstractProvider.call(AbstractProvider.java:47)
	at com.weibo.api.motan.filter.AccessStatisticFilter.filter(AccessStatisticFilter.java:41)
	at com.weibo.api.motan.protocol.support.ProtocolFilterDecorator$2.call(ProtocolFilterDecorator.java:150)
	at com.weibo.api.motan.filter.AccessLogFilter.filter(AccessLogFilter.java:56)
	at com.weibo.api.motan.protocol.support.ProtocolFilterDecorator$2.call(ProtocolFilterDecorator.java:150)
	at com.weibo.api.motan.transport.ProviderMessageRouter.call(ProviderMessageRouter.java:96)
	at com.weibo.api.motan.transport.ProviderProtectedMessageRouter.call(ProviderProtectedMessageRouter.java:82)
	at com.weibo.api.motan.transport.ProviderMessageRouter.handle(ProviderMessageRouter.java:91)
	at com.weibo.api.motan.transport.support.DefaultRpcHeartbeatFactory$HeartMessageHandleWrapper.handle(DefaultRpcHeartbeatFactory.java:82)
	at com.weibo.api.motan.transport.netty.NettyChannelHandler.processRequest(NettyChannelHandler.java:139)
	at com.weibo.api.motan.transport.netty.NettyChannelHandler.access$000(NettyChannelHandler.java:47)
	at com.weibo.api.motan.transport.netty.NettyChannelHandler$1.run(NettyChannelHandler.java:116)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
2016-11-09 10:16:06 [main-SendThread(127.0.0.1:2181)] DEBUG [org.apache.zookeeper.ClientCnxn:742] -Got ping response for sessionid: 0x15846bfb88d0007 after 0ms
2016-11-09 10:16:07 [http-nio-8082-exec-5] INFO  [accessLog:91] -referer|foundation|cd-foundation-rpc|192.168.199.103|com.zuoliubo.service.foundation.service.DeviceService|getById|java.lang.Long|192.168.199.103|foundation|cd-foundation-rpc|true|0|66
2016-11-09 10:16:07 [http-nio-8082-exec-5] DEBUG [org.springframework.web.servlet.mvc.method.annotation.RequestResponseBodyMethodProcessor:235] -Written [con.zuoliubo.service.foundation.domain.jpa.Device@539137a] as "application/json" using [org.springframework.http.converter.json.MappingJackson2HttpMessageConverter@6dd36ab6]
2016-11-09 10:16:07 [http-nio-8082-exec-5] DEBUG [org.springframework.web.servlet.DispatcherServlet:1044] -Null ModelAndView returned to DispatcherServlet with name 'dispatcherServlet': assuming HandlerAdapter completed request handling
2016-11-09 10:16:07 [http-nio-8082-exec-5] DEBUG [org.springframework.web.servlet.DispatcherServlet:1000] -Successfully completed request
2016-11-09 10:16:07 [http-nio-8082-exec-5] DEBUG [org.springframework.boot.web.filter.OrderedRequestContextFilter:104] -Cleared thread-bound request context: org.apache.catalina.connector.RequestFacade@21d940a6
2016-11-09 10:16:07 [http-nio-8082-exec-7] DEBUG [org.springframework.boot.web.filter.OrderedRequestContextFilter:114] -Bound request context to thread: org.apache.catalina.connector.RequestFacade@6229e7b5
2016-11-09 10:16:07 [http-nio-8082-exec-7] DEBUG [org.springframework.web.servlet.DispatcherServlet:865] -DispatcherServlet with name 'dispatcherServlet' processing GET request for [/favicon.ico]
2016-11-09 10:16:07 [http-nio-8082-exec-7] DEBUG [org.springframework.web.servlet.handler.SimpleUrlHandlerMapping:190] -Matching patterns for request [/favicon.ico] are [/**/favicon.ico]
2016-11-09 10:16:07 [http-nio-8082-exec-7] DEBUG [org.springframework.web.servlet.handler.SimpleUrlHandlerMapping:219] -URI Template variables for request [/favicon.ico] are {}
2016-11-09 10:16:07 [http-nio-8082-exec-7] DEBUG [org.springframework.web.servlet.handler.SimpleUrlHandlerMapping:140] -Mapping [/favicon.ico] to HandlerExecutionChain with handler [ResourceHttpRequestHandler [locations=[ServletContext resource [/], class path resource [META-INF/resources/], class path resource [resources/], class path resource [static/], class path resource [public/], class path resource []], resolvers=[org.springframework.web.servlet.resource.PathResourceResolver@3830b06c]]] and 1 interceptor
2016-11-09 10:16:07 [http-nio-8082-exec-7] DEBUG [org.springframework.web.servlet.DispatcherServlet:951] -Last-Modified value for [/favicon.ico] is: -1
2016-11-09 10:16:07 [http-nio-8082-exec-7] DEBUG [org.springframework.web.servlet.DispatcherServlet:1044] -Null ModelAndView returned to DispatcherServlet with name 'dispatcherServlet': assuming HandlerAdapter completed request handling
2016-11-09 10:16:07 [http-nio-8082-exec-7] DEBUG [org.springframework.web.servlet.DispatcherServlet:1000] -Successfully completed request
2016-11-09 10:16:07 [http-nio-8082-exec-7] DEBUG [org.springframework.boot.web.filter.OrderedRequestContextFilter:104] -Cleared thread-bound request context: org.apache.catalina.connector.RequestFacade@6229e7b5
2016-11-09 10:16:20 [main-SendThread(127.0.0.1:2181)] DEBUG [org.apache.zookeeper.ClientCnxn:742] -Got ping response for sessionid: 0x15846bfb88d0007 after 0ms
2016-11-09 10:16:33 [pool-5-thread-1] INFO  [serviceStatsLog:99] -[motan-accessStatistic] app: foundation-client module: cd-foundation-rpc-client item: motan://cd-foundation-rpc_com.zuoliubo.service.foundation.service.DeviceService.getById(java.lang.Long) total_count: 1 slow_count: 1 p75: 105.00 p95: 132.00 p98: 132.00 p99: 132.00 p999: 132.00 biz_excp: 0 other_excp: 0 avg_time: 66.00ms biz_time: 64.00ms avg_tps: 0 max_tps: 1 min_tps: 0 
2016-11-09 10:16:33 [pool-5-thread-1] INFO  [serviceStatsLog:99] -[motan-accessStatistic] <strong>app: foundation-client module: cd-foundation-rpc-client item: motan://cd-foundation-rpc_com.zuoliubo.service.foundation.service.DeviceService.toString(void) total_count: 2 slow_count: 0 p75: 55.50 p95: 201.00 p98: 201.00 p99: 201.00 p999: 201.00 biz_excp: 0 other_excp: 2 avg_time: 3.00ms biz_time: 3.00ms avg_tps: 0 max_tps: 2 min_tps: 0 </strong>
2016-11-09 10:16:33 [pool-5-thread-1] INFO  [serviceStatsLog:99] -[motan-totalAccessStatistic] app: foundation-client module: cd-foundation-rpc-client total_count: 3 slow_count: 1 p75: 89.50 p95: 201.00 p98: 201.00 p99: 201.00 p999: 201.00 biz_excp: 0 other_excp: 2 avg_time: 24.00ms biz_time: 23.33ms avg_tps: 0
2016-11-09 10:16:33 [pool-5-thread-1] INFO  [serviceStatsLog:99] -[motan-memoryStatistic] 54.00MB of 1820.50 MB (3.0%) used 
2016-11-09 10:16:33 [main-SendThread(127.0.0.1:2181)] DEBUG [org.apache.zookeeper.ClientCnxn:742] -Got ping response for sessionid: 0x15846bfb88d0007 after 0ms
2016-11-09 10:16:46 [main-SendThread(127.0.0.1:2181)] DEBUG [org.apache.zookeeper.ClientCnxn:742] -Got ping response for sessionid: 0x15846bfb88d0007 after 1ms
2016-11-09 10:17:00 [main-SendThread(127.0.0.1:2181)] DEBUG [org.apache.zookeeper.ClientCnxn:742] -Got ping response for sessionid: 0x15846bfb88d0007 after 0ms
2016-11-09 10:17:03 [pool-5-thread-1] INFO  [serviceStatsLog:95] -[motan-accessStatistic] app: foundation-client module: cd-foundation-rpc-client item: motan://cd-foundation-rpc_com.zuoliubo.service.foundation.service.DeviceService.getById(java.lang.Long) total_count: 0 slow_count: 0 biz_excp: 0 other_excp: 0 avg_time: 0.00ms biz_time: 0.00ms avg_tps: 0 max_tps: 0 min_tps: 0
2016-11-09 10:17:03 [pool-5-thread-1] INFO  [serviceStatsLog:95] -[motan-accessStatistic] app: foundation-client module: cd-foundation-rpc-client item: motan://cd-foundation-rpc_com.zuoliubo.service.foundation.service.DeviceService.toString(void) total_count: 0 slow_count: 0 biz_excp: 0 other_excp: 0 avg_time: 0.00ms biz_time: 0.00ms avg_tps: 0 max_tps: 0 min_tps: 0
2016-11-09 10:17:03 [pool-5-thread-1] INFO  [serviceStatsLog:95] -[motan-totalAccessStatistic] app: foundation-client module: cd-foundation-rpc-client total_count: 0 slow_count: 0 biz_excp: 0 other_excp: 0 avg_time: 0.00ms biz_time: 0.00ms avg_tps: 0
2016-11-09 10:17:03 [pool-5-thread-1] INFO  [serviceStatsLog:99] -[motan-memoryStatistic] 54.00MB of 1820.50 MB (3.0%) used 
2016-11-09 10:17:13 [main-SendThread(127.0.0.1:2181)] DEBUG [org.apache.zookeeper.ClientCnxn:742] -Got ping response for sessionid: 0x15846bfb88d0007 after 0ms

**Comment by estn** [comment]
不打断点的情况下，又是正常的只进行一次请求

**Comment by gaoke966** [comment]
参考#248

**Comment by gaoke966** [comment]
https://github.com/weibocom/motan/issues/248

**Comment by estn** [comment]
哦 好的 谢谢

**Comment by gaoke966** [comment]
我在DefaultProvider类的invoke方法体内第二行加上了下面的判断，有点简单粗暴，但可以作为临时方案解决问题：if("toString".equals(request.getMethodName())) {
//这里仅仅是粗暴的将toString过滤掉，直接返回，可以简单解决问题，但是对于接口中有用到toString方法等情况（或其他未知情况）时会有影响
return response;
}

**Comment by rayzhang0603** [comment]
0.2.2版本已经修复这个问题
