### ISSUE TITLE
通过zookeeper配置，第一次调用报错，后面调用就好了

### ISSUE THREAD

**Issue by slivercb** [weibocom/motan#287]
Server代码：
 
        ApplicationContext applicationContext = new ClassPathXmlApplicationContext(
                "classpath:motan_server.xml");
        MotanSwitcherUtil.setSwitcherValue(
                MotanConstants.REGISTRY_HEARTBEAT_SWITCHER, true);
          System.out.println("server start...");

motan_server.xml：

	<bean id="serviceImpl" class="matan.FooServiceImpl" />
	<motan:registry regProtocol="zookeeper" name="my_zookeeper"
		address="10.74.203.138:2181" />
	<motan:service interface="matan.FooService"
		ref="serviceImpl" registry="my_zookeeper" export="8002" />

Client代码：

      ApplicationContext ctx = new ClassPathXmlApplicationContext(
                "classpath:motan_client.xml");
        FooService service = (FooService) ctx.getBean("remoteService");
        System.out.println(service.hello("motan"));

motan_client.xml：

         <motan:registry regProtocol="zookeeper" name="my_zookeeper"
		address="10.74.203.138:2181" />
	<motan:referer id="remoteService" interface="matan.FooService"
		registry="my_zookeeper" />

第一次客户端调用时报错：

   2016-11-17 17:30:24,929||||RefererInvocationHandler invoke Error: uri=motan://10.74.203.138:0/matan.FooService requestId=1551237145914507265 interface=matan.FooService method=hello(java.lang.String)|||  
com.weibo.api.motan.exception.MotanServiceException: error_message: NettyResponseFuture request timeout: serverPort=10.74.203.138:8002 requestId=1551237145914507265 interface=matan.FooService method=hello(java.lang.String) cost=201, status: 503, error_code: 10003,r=null
	at com.weibo.api.motan.transport.netty.NettyResponseFuture.timeoutSoCancel(NettyResponseFuture.java:234)
	at com.weibo.api.motan.transport.netty.NettyResponseFuture.getValue(NettyResponseFuture.java:137)
	at com.weibo.api.motan.rpc.DefaultResponse.<init>(DefaultResponse.java:54)
	at com.weibo.api.motan.transport.netty.NettyClient.asyncResponse(NettyClient.java:204)
	at com.weibo.api.motan.transport.netty.NettyClient.request(NettyClient.java:187)
	at com.weibo.api.motan.transport.netty.NettyClient.request(NettyClient.java:116)
	at com.weibo.api.motan.protocol.rpc.DefaultRpcProtocol$DefaultRpcReferer.doCall(DefaultRpcProtocol.java:171)
	at com.weibo.api.motan.rpc.AbstractReferer.call(AbstractReferer.java:64)
	at com.weibo.api.motan.cluster.ha.FailoverHaStrategy.call(FailoverHaStrategy.java:72)
	at com.weibo.api.motan.cluster.support.ClusterSpi.call(ClusterSpi.java:73)
	at com.weibo.api.motan.proxy.RefererInvocationHandler.invoke(RefererInvocationHandler.java:108)

**Comment by slivercb** [comment]
已经解决了，少了请求超时时间配置：
<motan:referer id="remoteService" interface="com.huawei.baas.bdf.matan.FooService"
        registry="my_zookeeper" requestTimeout="10000"/>

应该是第一次调用需要连到zookeeper时间超长导致，默认的requestTimeout 200ms时间太短了
