### ISSUE TITLE
motan No route to host

### ISSUE THREAD

**Issue by ZhouXunYou** [weibocom/motan#289]
见以下BUG，三台主机 IP 分别为 192.168.1.54，192.168.1.55，192.168.1.56，请问有什么配置限制了远程主机的访问吗
[QC] ERROR [pool-2-thread-1] com.weibo.api.motan.log.DefaultLogService.error(87) | NettyClient heartbeat Error: url=motan://192.168.1.55:8002/mmc.api.storage.CollectDataStorageService
com.weibo.api.motan.exception.MotanServiceException: error_message: NettyChannel failed to connect to server, url: motan://192.168.1.55:8002/mmc.api.storage.CollectDataStorageService, result: true, success: false, connected: false, status: 503, error_code: 10001,r=null
        at com.weibo.api.motan.transport.netty.NettyChannel.open(NettyChannel.java:150)
        at com.weibo.api.motan.transport.netty.NettyChannelFactory.makeObject(NettyChannelFactory.java:53)
        at org.apache.commons.pool.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:1188)
        at com.weibo.api.motan.transport.AbstractPoolClient.borrowObject(AbstractPoolClient.java:75)
        at com.weibo.api.motan.transport.netty.NettyClient.request(NettyClient.java:160)
        at com.weibo.api.motan.transport.netty.NettyClient.heartbeat(NettyClient.java:132)
        at com.weibo.api.motan.transport.support.HeartbeatClientEndpointManager$1.run(HeartbeatClientEndpointManager.java:68)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.NoRouteToHostException: No route to host
        at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
        at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
        at org.jboss.netty.channel.socket.nio.NioClientSocketPipelineSink$Boss.connect(NioClientSocketPipelineSink.java:384)
        at org.jboss.netty.channel.socket.nio.NioClientSocketPipelineSink$Boss.processSelectedKeys(NioClientSocketPipelineSink.java:354)
        at org.jboss.netty.channel.socket.nio.NioClientSocketPipelineSink$Boss.run(NioClientSocketPipelineSink.java:276)

**Comment by ZhouXunYou** [comment]
sorry,防火墙问题
