### ISSUE TITLE
增加新的服务节点时，client 报出连接新节点超时

### ISSUE THREAD

**Issue by yelllowhat** [weibocom/motan#295]
标题： 增加新的服务节点时，client 报出连接新节点超时
场景： 
1. 发布一个服务，启动 client 调用服务 ok
2. 增加同样一个服务节点
3.  client 发现有的新的服务，建立连接超时

说明：
1.  consul-registry 
2.  超时配置 , 这里配置的是 10s ，但 netty init 新连接 1s 就 timeOut 了

<motan:basicReferer id="clientBasicConfig" registry="consul-registry"
		connectTimeout="10000" requestTimeout="10000" protocol="motan-protocol"
		throwException="true" check="true" accessLog="false" group="${app_group_name}"
		module="${app_module_name}" application="${app_name}" version="1.0"
		retries="2" />

日志如下： 

2016-11-24 17:06:01,523 ERROR error:87 - NettyClient init pool create connect Error: url=motan://192.168.0.199:7003/com.csf.service.user.service.IPlatformService
com.weibo.api.motan.exception.MotanServiceException: error_message: NettyChannel connect to server timeout url: motan://192.168.0.199:7003/com.csf.service.user.service.IPlatformService, cost: 1001, result: false, success: false, connected: false, status: 503, error_code: 10001,r=null
	at com.weibo.api.motan.transport.netty.NettyChannel.open(NettyChannel.java:154)
	at com.weibo.api.motan.transport.netty.NettyChannelFactory.makeObject(NettyChannelFactory.java:53)
	at org.apache.commons.pool.impl.GenericObjectPool.addObject(GenericObjectPool.java:1691)
	at com.weibo.api.motan.transport.AbstractPoolClient.initPool(AbstractPoolClient.java:64)
	at com.weibo.api.motan.transport.netty.NettyClient.open(NettyClient.java:217)
	at com.weibo.api.motan.protocol.rpc.DefaultRpcProtocol$DefaultRpcReferer.doInit(DefaultRpcProtocol.java:196)
	at com.weibo.api.motan.rpc.AbstractNode.init(AbstractNode.java:46)
	at com.weibo.api.motan.protocol.AbstractProtocol.refer(AbstractProtocol.java:100)
	at com.weibo.api.motan.protocol.support.ProtocolFilterDecorator.refer(ProtocolFilterDecorator.java:70)
	at com.weibo.api.motan.cluster.support.ClusterSupport.notify(ClusterSupport.java:175)
	at com.weibo.api.motan.registry.support.command.CommandServiceManager.notifyService(CommandServiceManager.java:91)
	at com.weibo.api.motan.registry.consul.ConsulRegistry$NotifyService.run(ConsulRegistry.java:389)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

Exception in thread "pool-4-thread-1" java.lang.NullPointerException
	at com.weibo.api.motan.registry.consul.ConsulRegistry$NotifyService.run(ConsulRegistry.java:386)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

    请修改:  com.weibo.api.motan.registry.consul.ConsulRegistry 385 
       public void run() {
            ConcurrentHashMap<URL, ServiceListener> listeners = serviceListeners.get(service);
           **//  listeners = null 时  synchronized  报出 NullPointerException**
            synchronized (listeners) {
                for (Map.Entry<URL, ServiceListener> entry : listeners.entrySet()) {
                    ServiceListener serviceListener = entry.getValue();
                    serviceListener.notifyService(entry.getKey(), getUrl(), urls);
                }
            }
       }

排查分析：

很明显是服务还没有初始化好，client 就连接上来了.
查看错误码：

503	10001	NettyChannel failed to connect to server	服务使用方初始化netty中，无法连接到服务端，确认服务提供方是否正确提供服务

疑问：
1.  新节点上架，为什么会影响 client 连接？即使有新连接加入本地连接池中即可 他的超进时间如何设置?
2.  新节点在启动的时，既然还没有启动好 port ，为什么又急于发布到 注册中心呢? ( consul )

**Comment by rayzhang0603** [comment]
非常感谢反馈！connectTimeout没有生效的问题、空指针异常这两个问题将在下个小版本修复，预计本周内发布。
关于两个疑问：
1、新server节点上线，client端感知后会预先建立链接，成功后才会发起调用。
2、新server节点启动的注册时间是在完成server初始化后（SimpleConfigHandler line77），按说server应该启动成功了，你可以确认一下server端口是否能正常链接。线上服务一般是通过心跳开关的机制进行限制，启动后先验证服务正常，然后在打开心跳开关。

**Comment by rayzhang0603** [comment]
0.2.2版本修复了这两个问题，可以在测试一下。

**Comment by yelllowhat** [comment]
好的，谢谢 @rayzhang0603 答复

1.  timeout 我后面跟踪了一下代码，发现原有在建立 client 时采用的 sys 的默认值，没有取 配置的值，导致参
     数没有启用
2.   np 问题，我在本地修改了代码，timeout ( 5000)  测试了一下，OK了

测试： 
原有  新server节点上线 /  client端感知后建立连接 timeOut 的一部分原因是 “连接数过多” 导致的，我在测试频率切换服务节点，观察业务动行的状态

结果:
1. 发现一个问题, 在 client 启动的时候，同机器的 server , 不会被优先调用，配置上是启动 localhost 优先的
loadbalance="localFirst" 

此配置项有被启用吗？
 
现在 motan 已经在我们的业务上运行起来了， 后面我们将结合 motan + docker 实现微服务化

**Comment by rayzhang0603** [comment]
赞一个～

loadbalance配置项是启用的，配置了loadbalance="localFirst"时，请求时会根据本机ip与serverip是否一致（LocalFirstLoadBalance.searchLocalReferer()），优先调用本机的。看是不是docker环境使用的ip不是同一个导致的。

**Comment by yelllowhat** [comment]
@rayzhang0603  你好

我们现在还没有在 docker 环境下运行, ip 也是在发布服务时通过配置  host 指定了 ip 

Q:  motan 获取IP 
通过您以前的介绍的步骤，获取IP ，我实际的测试中发现不配置 host 还是会获取IP 不对的情况，即使你把 hostname 都配置好 单网卡物理机测试,  还是会出问题

所以我们现在服务发布，都会强制的指定 host 配置选项,  docker 环境我们会以 app的方式设置此 host ip

**Comment by rayzhang0603** [comment]
我们线上的docker环境也是使用host ip方式。
hostname是通过java.net.InetAddress.getLocalHost()方式获取的，在我们测试中是可以通过配置hostname获取到指定ip的，是不是跟设置hostname的时机有关？

**Comment by yelllowhat** [comment]
谢谢 @rayzhang0603  
现在的解决方案还是指定明确的IP地址，  java.net.InetAddress.getLocalHost()方式获取存在不准的情况（具体体现在多内网IP的情况下，比如启动了 docker, 或虚拟 bind了多IP等情况）
