### ISSUE TITLE
消费者（客户端）请求服务器，出现：error_message: NettyResponseFuture task cancel 错误，实际上是客户端请求服务是成功的

### ISSUE THREAD

**Issue by huangruisheng** [weibocom/motan#3]
12:20:00.989 [main] INFO  info - NettyClient finish Open: url=motan://172.13.80.68:8002/com.zdmoney.assets.api.motan.FooService?group=default_rpc
12:20:00.992 [main] INFO  info - DefaultRpcReferer node init Success: [DefaultRpcReferer] url=motan://172.13.80.68:8002/com.zdmoney.assets.api.motan.FooService?group=default_rpc
12:20:00.992 [main] INFO  info - DefaultRpcProtocol refer Success: url=motan://172.13.80.68:8002/com.zdmoney.assets.api.motan.FooService?group=default_rpc
Exception in thread "main" com.weibo.api.motan.exception.MotanServiceException: error_message: NettyResponseFuture task cancel: serverPort=172.13.80.68:8002 requestId=146147160103200001 interface=com.zdmoney.assets.api.motan.FooService method=hello(java.lang.String) cost=249, status: 503, error_code: 10001,r=
    at com.weibo.api.motan.transport.netty.NettyResponseFuture.cancel(NettyResponseFuture.java:151)
    at com.weibo.api.motan.transport.netty.NettyClient$TimeoutMonitor.run(NettyClient.java:482)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
12:20:01.397 [main] ERROR error - RefererInvocationHandler invoke Error: uri=motan://172.13.80.68:0/com.zdmoney.assets.api.motan.FooService requestId=146147160103200001 interface=com.zdmoney.assets.api.motan.FooService method=hello(java.lang.String)
com.weibo.api.motan.exception.MotanServiceException: error_message: NettyResponseFuture task cancel: serverPort=172.13.80.68:8002 requestId=146147160103200001 interface=com.zdmoney.assets.api.motan.FooService method=hello(java.lang.String) cost=249, status: 503, error_code: 10001,r=
    at com.weibo.api.motan.transport.netty.NettyResponseFuture.cancel(NettyResponseFuture.java:151) ~[motan-transport-netty-0.0.1.jar:na]
    at com.weibo.api.motan.transport.netty.NettyClient$TimeoutMonitor.run(NettyClient.java:482) ~[motan-transport-netty-0.0.1.jar:na]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_25]
    at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) ~[na:1.8.0_25]
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) ~[na:1.8.0_25]
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) ~[na:1.8.0_25]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_25]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_25]
    at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_25]
    at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
12:20:01.467 [New I/O client worker #1-2] WARN  warn - NettyClient has response from server, but resonseFuture not exist,  requestId=146147160103200001

**Comment by qdaxb** [comment]
这种一般是由于client默认为200ms超时，调用超时会抛出异常。如果要调大超时时间，可以在referer配置中增加requestTimeout属性：

```
<motan:referer id="remoteService" interface="quickstart.FooService" directUrl="localhost:8002" requestTimeout="500" >
```

详细的属性清单可以参考：
https://github.com/weibocom/motan/wiki/zh_configuration
