### ISSUE TITLE
注册多个service出错

### ISSUE THREAD

**Issue by Satangelsx** [weibocom/motan#300]
你好， 当我注册两个service的时候就报错
java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:463)
	at sun.nio.ch.Net.bind(Net.java:455)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
	at io.netty.channel.socket.nio.NioServerSocketChannel.doBind(NioServerSocketChannel.java:125)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:498)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1271)
	at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:413)
	at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:399)
	at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:1019)
	at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:198)
	at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:349)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:358)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:374)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:745)
但是只注册一个service时就正常，能麻烦给看一下吗
配置文件如下：
<motan:registry regProtocol="zookeeper" name="motan" address="${zk.address}" default="true" connectTimeout="5000"/>

    <motan:protocol id="yarProtocol" name="yar" default="true"/>

    <motan:basicService id="yarBasicService" group="goods-service" module="goods-service" registry="motan" export="yarProtocol:8002"/>

    <motan:service interface="com.test.service.IGoodsService" ref="goodsService" basicService="yarBasicService" />

    <motan:service interface="com.test.service.IBrandService" ref="brandService" basicService="yarBasicService"/>

**Comment by feilaoda** [comment]
在motan:basicService中加 shareChannel="true"

**Comment by Satangelsx** [comment]
谢谢！
