### ISSUE TITLE
请问如何更换序列化方式为"hprose"

### ISSUE THREAD

**Issue by estn** [weibocom/motan#306]
现在想将序列化方式更换为hprose，但是在client端报异常信息
环境
1.motan版本0.2.2
2.server和client端均引入了"hprose-java"和"serialization-extension" 这两个jar

server端配置
```java
    @Bean(name = "motan")
    public ProtocolConfigBean protocolConfig() {
        ProtocolConfigBean protocol = new ProtocolConfigBean();
        protocol.setDefault(true);
        protocol.setName("motan");
        protocol.setMaxServerConnection(80000);
        protocol.setMaxContentLength(1048576);
        protocol.setMaxWorkerThread(800);
        protocol.setMinWorkerThread(20);
        protocol.setMaxContentLength(1048576);
        protocol.setSerialization("hprose");
        return protocol;
    }
```

client端配置
```java
    @Bean(name = "motan")
    public ProtocolConfigBean protocolConfig() {
        ProtocolConfigBean protocol = new ProtocolConfigBean();
        protocol.setDefault(true);
        protocol.setName("motan");
        protocol.setHaStrategy("failfast");
        protocol.setMaxClientConnection(10);
        protocol.setMinClientConnection(2);
        protocol.setFilter("mock");
        protocol.setSerialization("hprose");
        return protocol;
    }
```
当client端调用server端时，client端出现以下异常信息
```
com.weibo.api.motan.exception.MotanFrameworkException: error_message: decode error: isResponse=true, status: 503, error_code: 20003,r=null
	at com.weibo.api.motan.protocol.rpc.DefaultRpcCodec.decode(DefaultRpcCodec.java:136)
	at com.weibo.api.motan.transport.netty.NettyDecoder.decode(NettyDecoder.java:105)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:282)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:216)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:80)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:274)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:261)
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:349)
	at org.jboss.netty.channel.socket.nio.NioWorker.processSelectedKeys(NioWorker.java:280)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:200)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:44)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException: null
	at com.weibo.api.motan.codec.AbstractCodec.deserialize(AbstractCodec.java:50)
	at com.weibo.api.motan.protocol.rpc.DefaultRpcCodec.decodeResponse(DefaultRpcCodec.java:373)
	at com.weibo.api.motan.protocol.rpc.DefaultRpcCodec.decode(DefaultRpcCodec.java:125)
	... 16 common frames omitted
```

**Comment by rayzhang0603** [comment]
从异常上看是server端返回了response，client端在decode时没有获取到hprose这个扩展。可以在check 一下client端实际打好的包中是否有serialization-extension

**Comment by andot** [comment]
你看一下你的 pom 文件中是否有：

```xml
<dependency>
    <groupId>org.hprose</groupId>
    <artifactId>hprose-java</artifactId>
    <version>[2.0.29,)</version>
</dependency>
<dependency>
    <groupId>com.weibo</groupId>
    <artifactId>motan-extension</artifactId>
    <version>0.2.2</version>
</dependency>
```

**Comment by estn** [comment]
谢谢两位的解答，确实自己大意了 Server端添加了这两个JAR，Client端忘了添加

**Comment by allenwtl** [comment]
你好  我也改为了 hprose  client 调用的时候  出现了 类型转换异常  不知道 你出现了没 
 hprose.util.LinkedCaseInsensitiveMap cannot be cast
