### ISSUE TITLE
Unable to connect to zookeeper server within timeout: 5000

### ISSUE THREAD

**Issue by stevehu** [weibocom/motan#333]
master branch zookeeper module test case fails with the following error. I am using Oracle Java 8 on Mac Book Pro. Thanks.

```
subAndUnsubService(com.weibo.api.motan.registry.zookeeper.ZookeeperRegistryTest)  Time elapsed: 30.255 sec  <<< ERROR!
org.I0Itec.zkclient.exception.ZkTimeoutException: Unable to connect to zookeeper server within timeout: 5000
	at org.I0Itec.zkclient.ZkClient.connect(ZkClient.java:880)
	at org.I0Itec.zkclient.ZkClient.<init>(ZkClient.java:98)
	at org.I0Itec.zkclient.ZkClient.<init>(ZkClient.java:92)
	at org.I0Itec.zkclient.ZkClient.<init>(ZkClient.java:76)
	at com.weibo.api.motan.registry.zookeeper.ZookeeperRegistryTest.setUp(ZookeeperRegistryTest.java:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.internal.runners.MethodRoadie.runBefores(MethodRoadie.java:122)
	at org.junit.internal.runners.MethodRoadie.runBeforesThenTestThenAfters(MethodRoadie.java:86)
	at org.junit.internal.runners.MethodRoadie.runTest(MethodRoadie.java:77)
	at org.junit.internal.runners.MethodRoadie.run(MethodRoadie.java:42)
	at org.junit.internal.runners.JUnit4ClassRunner.invokeTestMethod(JUnit4ClassRunner.java:88)
	at org.junit.internal.runners.JUnit4ClassRunner.runMethods(JUnit4ClassRunner.java:51)
	at org.junit.internal.runners.JUnit4ClassRunner$1.run(JUnit4ClassRunner.java:44)
	at org.junit.internal.runners.ClassRoadie.runUnprotected(ClassRoadie.java:27)
	at org.junit.internal.runners.ClassRoadie.runProtected(ClassRoadie.java:37)
	at org.junit.internal.runners.JUnit4ClassRunner.run(JUnit4ClassRunner.java:42)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75) 

```

**Comment by sunnights** [comment]
the zookeeper unit test relies on an embedded zookeeper server, you can find the zk config in src/test/resources/zoo.cfg.
maybe you should find out why the zk client can't connect to the embedded server within 5s

**Comment by stevehu** [comment]
Thanks for the quick reply. It only happens occasionally so i guess it is timing or thread synching issue. Sometime, I also saw address already used (not exact message as I did make a copy). 

The setUp and tearDown are using @Before and @After. Should they be @BeforeClass and @AfterClass and made them as static? Currently, every test case in the file will start a brand new zookeeper instance.

Is there any reason we don't use TestingServer from curator?

**Comment by sunnights** [comment]
Thanks for your advice and attention on motan~

Use @Before in this test is mainly for init a brand new zk server. Add the @BeforeClass and init server in  @Before maybe better for this case.

There is nothing special for using zkclient, curator is a better choice for unit test. 
We will rewrite this ut later
Thanks again!
