### ISSUE TITLE
client调用server错误

### ISSUE THREAD

**Issue by winner1207** [weibocom/motan#339]
异常如下：
Caused by: java.lang.NullPointerException
	at com.weibo.api.motan.codec.AbstractCodec.serialize(AbstractCodec.java:42)
	at com.weibo.api.motan.protocol.rpc.DefaultRpcCodec.encodeRequest(DefaultRpcCodec.java:177)
	at com.weibo.api.motan.protocol.rpc.DefaultRpcCodec.encode(DefaultRpcCodec.java:59)
	... 50 more
跟踪断点发现是：
![image](https://cloud.githubusercontent.com/assets/15061547/22012755/a8c70662-dcd0-11e6-80c9-c59e35400b0f.png)
序列化两个实现类：fastjson、hession为空，版本0.2.1和0.2.2都试过了，都不行，请问是什么原因呢？

**Comment by winner1207** [comment]
已解决，主要classloader引起的，在应用启动时调用ExtensionLoader.initExtensionLoader(Serialization.class);即可
