### ISSUE TITLE
使用git中简单示例 报错。是否遗漏什么配置参数了？

### ISSUE THREAD

**Issue by abudula** [weibocom/motan#34]
Exception in thread "main" com.weibo.api.motan.exception.MotanServiceException: error_message: NettyResponseFuture task cancel: serverPort=localhost:8002 requestId=146285695919400002 interface=com.huateng.xxx.service.FooService method=hello(java.lang.String) cost=212, status: 503, error_code: 10001,r=
    at com.weibo.api.motan.transport.netty.NettyResponseFuture.cancel(NettyResponseFuture.java:151)
    at com.weibo.api.motan.transport.netty.NettyClient$TimeoutMonitor.run(NettyClient.java:482)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)

**Comment by qdaxb** [comment]
调用超时了，默认超时是200ms，如果要调整超时的话可以在client配置里增加requestTimeout参数（单位ms）。

**Comment by abudula** [comment]
嗯，我下载了demo，看到了具体参数。谢谢

---

------------------ 原始邮件 ------------------

 发件人: axb  notifications@github.com

 发送时间: 2016-05-10 13:25:05

 收件人:weibocom/motan motan@noreply.github.com 

 抄送:陆 13916477609@139.com,Author author@noreply.github.com 

 主题: Re: [weibocom/motan] 使用git中简单示例 报错。是否遗漏什么配置参数了？ (#34)

调用超时了，默认超时是200ms，如果要调整超时的话可以在client配置里增加requestTimeout参数（单位ms）。
