### ISSUE TITLE
client端初始化META-INF/services/配置文件的问题

### ISSUE THREAD

**Issue by winner1207** [weibocom/motan#340]
查看源码发现没有初始化com.weibo.api.motan.codec.Serialization这个文件，而是在调用时检查是否init，但是有可能第一次调用是异步Thread发起的，导致classloader无法正确获取getResources路径，导致无法将序列化的实现类加载到jvm中，下面贴上源码
![image](https://cloud.githubusercontent.com/assets/15061547/22063618/a691365c-ddba-11e6-87fa-9e816edd3d5a.png)
![image](https://cloud.githubusercontent.com/assets/15061547/22063585/86baf5c0-ddba-11e6-9384-af072f78fec8.png)

**Comment by winner1207** [comment]
补充下，以上问题会导致如下报错：
Caused by: java.lang.NullPointerException
at com.weibo.api.motan.codec.AbstractCodec.serialize(AbstractCodec.java:42)
at com.weibo.api.motan.protocol.rpc.DefaultRpcCodec.encodeRequest(DefaultRpcCodec.java:177)
at com.weibo.api.motan.protocol.rpc.DefaultRpcCodec.encode(DefaultRpcCodec.java:59)

**Comment by rayzhang0603** [comment]
非常感谢您的反馈，在异步调用使用不同classloader的情况下是存在这种可能。后续版本会修复这个bug。

**Comment by winner1207** [comment]
不客气，那我就把这个问题关闭了
