### ISSUE TITLE
Connection reset by peer

### ISSUE THREAD

**Issue by srmsh** [weibocom/motan#360]
NettyChannelHandler exceptionCaught: remote=/****:58400 local=/****:**** event=java.io.IOException: Connection reset by peer
或者Connection timed out

服务总是报这个错误
timed out 是不是check的时候没有链接上　我把防火墙关了就报Connection reset by peer

**Comment by srmsh** [comment]
@andot @feilaoda 帮忙看一下，谢谢

**Comment by rayzhang0603** [comment]
估计是跟网络有关，可以确认一下server注册时自动获取的ip是否正确，有无配置虚拟网卡，或者直接使用telnet在client端直连一下试试看网络是否正常
另外可以确认一下是完全无法建立链接，还是定期出现这样的异常？如果是偶发异常client端调用应该是可以成功的

**Comment by srmsh** [comment]
１、注册时是没有问题的
２、也没有配置虚拟网
３、直接链接是可以链接的上的

Connection timed out　这个应该是“检查服务提供者是否存在”时　使用了随机端口　client和server在不同的机器　这个随机端口没有开放
但是Connection reset by peer就不知道是什么原因了　　是不是连接数太多了？
@rayzhang0603

**Comment by rayzhang0603** [comment]
client端只会链接server端在注册中心注册的端口，Connection timed out这个异常应该是client端与server端建立链接时发生的吧？可以配置一下connectTimeout试试，默认是1s
Connection reset by peer一般来讲是对端关闭了链接，可以确认一下client端有没有关闭链接的记录。如果网络状况不好，可以把requestTimeout调大一些试试。

**Comment by srmsh** [comment]
我看报错信息里面remote=/ip:58400 local=/ip:port
local是没问题的　　remote的端口一直在变

client也没有关闭链接的记录　差不多20-30分钟报错一次

@rayzhang0603

**Comment by rayzhang0603** [comment]
remote是指client端与server建立链接的端口，这个没有影响。你可以按照我上面说的把那两个超时调大点试试

**Comment by srmsh** [comment]
已经设置为５秒还是Connection reset by peer
@rayzhang0603

**Comment by rayzhang0603** [comment]
Connection reset by peer应该是client已经断开的链接，server端仍有写入，可以在client端debug一下netty，看看链接的建立与关闭有没有什么可疑的地方吧。偶发下这种情况对client端的请求应该不会造成影响

**Comment by lytofb** [comment]
连接被reset了，感觉和motan没有关系。端口没有打开，或者响应超时，或者zero window了

**Comment by lights8080** [comment]
这个问题有结论吗，我的也是这样。客户端一个链接断开，马上会有一个新的端口链接进来。未测试不知道会不会有丢数据的情况。

**Comment by ivancxj** [comment]
我也是时不时报这个异常,大家有解决方案吗?

**Comment by lgoodbook** [comment]
我也是时不时报这个异常,大家有解决方案吗?

**Comment by daringyun** [comment]
https://github.com/mrniko/netty-socketio/issues/143

**Comment by winner1207** [comment]
以前一直没有问题，最近几天服务器都在报这个错，怀疑是阿里云的工程师调整了某个网络参数导致的，业务使用正常没发现有丢消息的情况，但是每个几十分钟就会有这个报错
@srmsh 请问问题是否已解决了呢？谢谢。

**Comment by HeMing16** [comment]
问题解决了吗？我也遇到这种问题了，间隔一分钟就报错。
2018-08-12 22:27:19.346 ERROR [New I/O server worker #1-4]error 87 error - NettyChannelHandler exceptionCaught: remote=/172.31.178.85:35262 local=/172.31.178.82:15601 event=java.io.IOException: Connection reset by peer java.io.IOException: Connection reset by peer
        at sun.nio.ch.FileDispatcherImpl.read0(Native Method) ~[?:1.8.0_111]
        at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39) ~[?:1.8.0_111]
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[?:1.8.0_111]
        at sun.nio.ch.IOUtil.read(IOUtil.java:192) ~[?:1.8.0_111]
        at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380) ~[?:1.8.0_111]
        at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:321) ~[netty-3.2.5.Final.jar:?]
        at org.jboss.netty.channel.socket.nio.NioWorker.processSelectedKeys(NioWorker.java:280) ~[netty-3.2.5.Final.jar:?]
        at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:200) ~[netty-3.2.5.Final.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_111]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_111]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]

2018-08-12 22:27:21.021 ERROR [New I/O server worker #1-1]error 87 error - NettyChannelHandler exceptionCaught: remote=/172.31.178.85:35260 local=/172.31.178.82:15601 event=java.io.IOException: Connection reset by peer java.io.IOException: Connection reset by peer
        at sun.nio.ch.FileDispatcherImpl.read0(Native Method) ~[?:1.8.0_111]
        at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39) ~[?:1.8.0_111]
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[?:1.8.0_111]
        at sun.nio.ch.IOUtil.read(IOUtil.java:192) ~[?:1.8.0_111]
        at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380) ~[?:1.8.0_111]
        at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:321) ~[netty-3.2.5.Final.jar:?]
        at org.jboss.netty.channel.socket.nio.NioWorker.processSelectedKeys(NioWorker.java:280) ~[netty-3.2.5.Final.jar:?]
        at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:200) ~[netty-3.2.5.Final.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_111]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_111]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]

2018-08-12 22:27:38.722 ERROR [New I/O server worker #1-2]error 87 error - NettyChannelHandler exceptionCaught: remote=/172.31.178.85:35610 local=/172.31.178.82:15601 event=java.io.IOException: Connection reset by peer java.io.IOException: Connection reset by peer
        at sun.nio.ch.FileDispatcherImpl.read0(Native Method) ~[?:1.8.0_111]
        at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39) ~[?:1.8.0_111]
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[?:1.8.0_111]
        at sun.nio.ch.IOUtil.read(IOUtil.java:192) ~[?:1.8.0_111]
        at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380) ~[?:1.8.0_111]
        at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:321) ~[netty-3.2.5.Final.jar:?]
        at org.jboss.netty.channel.socket.nio.NioWorker.processSelectedKeys(NioWorker.java:280) ~[netty-3.2.5.Final.jar:?]
        at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:200) ~[netty-3.2.5.Final.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_111]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_111]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]

**Comment by shiyuHou** [comment]
赐教啊，这个问题有没有什么好的解决方案啊？

**Comment by shiyuHou** [comment]
赐教啊，这个问题有没有什么好的解决方案啊？
An exception '{}' [enable DEBUG level for full stacktrace] was thrown by a user handler's exceptionCaught() method while handling the following exception:
java.io.IOException: Connection reset by peer
 at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
 at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
 at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
 at sun.nio.ch.IOUtil.read(IOUtil.java:192)
 at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)

**Comment by shiyuHou** [comment]
@srmsh @ @rayzhang0603 @lytofb @ @lihaipeng0417  @ivancxj 
请问有了解决方案了吗？ 我的也是一直出现这种问题，求解！

**Comment by ecoSakuraSou** [comment]
大佬们啊，俺也一样~
