### ISSUE TITLE
客户端在调用服务端时 服务端关闭服务后（反注册） 客户端连接3次后 无限重连 控制台刷丢失连接心跳信息

### ISSUE THREAD

**Issue by kevin2f** [weibocom/motan#383]
如题
com.weibo.api.motan.exception.MotanServiceException: error_message: NettyChannel failed to connect to server
at com.weibo.api.motan.transport.netty.NettyChannel.open(NettyChannel.java:150)
	at com.weibo.api.motan.transport.netty.NettyChannelFactory.makeObject(NettyChannelFactory.java:53)
	at org.apache.commons.pool.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:1188)
	at com.weibo.api.motan.transport.AbstractPoolClient.borrowObject(AbstractPoolClient.java:75)
	at com.weibo.api.motan.transport.netty.NettyClient.request(NettyClient.java:160)
	at com.weibo.api.motan.transport.netty.NettyClient.heartbeat(NettyClient.java:132)
	at com.weibo.api.motan.transport.support.HeartbeatClientEndpointManager$1.run(HeartbeatClientEndpointManager.java:68)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:744)
	at org.jboss.netty.channel.socket.nio.NioClientSocketPipelineSink$Boss.connect(NioClientSocketPipelineSink.java:384)
	at org.jboss.netty.channel.socket.nio.NioClientSocketPipelineSink$Boss.processSelectedKeys(NioClientSocketPipelineSink.java:354)
	at org.jboss.netty.channel.socket.nio.NioClientSocketPipelineSink$Boss.run(NioClientSocketPipelineSink.java:276)
	... 3 common frames omitted

**Comment by kevin2f** [comment]
motan监控中看到 该服务只有客户端 没有服务端

**Comment by rayzhang0603** [comment]
这是motan client的自我保护机制，如果注册中心通知的server节点为空，client会忽略通知，继续使用上一次的服务节点信息。
一般线上服务不允许在client未下线前所有服务都下线。如果要下掉服务，需要先停掉所有client端，然后才能下线服务的server。

**Comment by kevin2f** [comment]
了解  ~  3Q~

**Comment by kevin2f** [comment]
这个问题能不能改成报错就可以  无限重连 这个地方可否修改下~？

**Comment by kevin2f** [comment]
这个问题能不能改成报错就可以 netty 无限重连 这个地方可否修改下~？ @rayzhang0603

**Comment by rayzhang0603** [comment]
其实这个地方触发了另外一个机制，client认为server是可用的，但是实际上不能使用，于是client会把server放在探测列表，每隔500ms就发一个心跳试试server是否可用，因此每次探测都会失败。
这个地方可以改成类似指数退避的逐步延长探测周期，例如 500ms,1s,2s,4s,这样对失败的节点逐步延长探测周期，不过实现起来太过复杂，对于这种情况最好还是可以从其他层面来规避我觉得会更好些。
