### ISSUE TITLE
demo中MotanApiClientDemo使用的协议不匹配？

### ISSUE THREAD

**Issue by ghost** [weibocom/motan#45]
你好，
还不是很清楚配置，在IDE中调试demo程序，基于spring配置的demo运行正常：
`Hello motan0!
Hello motan1!
Hello motan2!
Hello motan3!
Hello motan4!
Hello motan5!
Hello motan6!
Hello motan7!`
非spring启动失败，步骤如下：
运行MotanApiExportDemo，启动成功。
运行MotanApiClientDemo，异常堆栈信息：

```
Exception in thread "main" com.weibo.api.motan.exception.MotanFrameworkException: error_message: ClusterSupport No service urls for the refer:motan://192.168.1.100:0/motan-demo-rpc/com.weibo.motan.demo.service.MotanDemoService/1.0/referer, registries:[local://127.0.0.1:0/com.weibo.api.motan.registry.RegistryService?group=default_rpc], status: 404, error_code: 10101,r=
    at com.weibo.api.motan.cluster.support.ClusterSupport.init(ClusterSupport.java:102)
    at com.weibo.api.motan.config.handler.SimpleConfigHandler.buildClusterSupport(SimpleConfigHandler.java:52)
    at com.weibo.api.motan.config.RefererConfig.createClusterSupport(RefererConfig.java:184)
    at com.weibo.api.motan.config.RefererConfig.initRef(RefererConfig.java:128)
    at com.weibo.api.motan.config.RefererConfig.getRef(RefererConfig.java:85)
    at com.weibo.motan.demo.client.MotanApiClientDemo.main(MotanApiClientDemo.java:49)

```

定位到ClusterSupport类

```
throw new MotanFrameworkException(String.format("ClusterSupport No service urls for the refer:%s, registries:%s",
                this.url.getIdentity(), registryUrls), MotanErrorMsgConstant.SERVICE_UNFOUND);
```

猜测是client寻找的服务refer与server注册的服务协议不一致？

希望尽快提供develop guide以便参与维护。

**Comment by qdaxb** [comment]
如果不使用注册中心，那么需要在referer中配置directUrl：

```
motanDemoServiceReferer.setDirectUrl("localhost:8002");
```

develop guide正在努力编写中……

**Comment by ghost** [comment]
: ) thx
