### ISSUE TITLE
DefaultLogService生产环境运行报错，请帮忙分析原因

### ISSUE THREAD

**Issue by iFighter** [weibocom/motan#480]
DefaultLogService.java:87][DefaultLogService.java:error:com.weibo.api.motan.log.DefaultLogService.error(DefaultLogService.java:87)] - NettyChannelHandler exceptionCaught: remote=/119.23.140.191:52498 local=/120.77.11.75:8004 event=java.io.IOException: Connection reset by peer
java.io.IOException: Connection reset by peer
        at sun.nio.ch.FileDispatcherImpl.read0(Native Method) ~[?:1.8.0_111]
        at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39) ~[?:1.8.0_111]
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[?:1.8.0_111]
        at sun.nio.ch.IOUtil.read(IOUtil.java:192) ~[?:1.8.0_111]
        at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380) ~[?:1.8.0_111]
        at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:321) ~[netty-3.2.5.Final.jar:?]
        at org.jboss.netty.channel.socket.nio.NioWorker.processSelectedKeys(NioWorker.java:280) ~[netty-3.2.5.Final.jar:?]
        at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:200) ~[netty-3.2.5.Final.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_111]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_111]

**Comment by rayzhang0603** [comment]
这个异常是链接断开异常，如果不频繁的话不会有影响

**Comment by iFighter** [comment]
请问如何减少或避免这个异常呢？

**Comment by hxliujing** [comment]
非常频繁

**Comment by hxliujing** [comment]
NettyChannelHandler exceptionCaught: remote=/100.116.165.3:13999 local=/10.168.168.65:8201 event=java.io.IOException: Connection reset by peer

java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:64)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:109)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:312)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:90)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by aqiangsoft** [comment]
java.io.IOException: Connection reset by peer异常比较频繁 有一种可能是你服务部署在阿里云上并且暴露的服务ip是外网 建议所有rpc服务在内网通讯就ok 可以减少带宽和性能损耗 同时也能在一定程度上减缓网络超时异常
