### ISSUE TITLE
Unable to connect to zookeeper server

### ISSUE THREAD

**Issue by vishal2232** [weibocom/motan#492]
Prepare to shutdown (kafka.server.KafkaServerStartable)
org.I0Itec.zkclient.exception.ZkTimeoutException: Unable to connect to zookeeper server within timeout: 6000
	at org.I0Itec.zkclient.ZkClient.connect(ZkClient.java:880)
	at org.I0Itec.zkclient.ZkClient.<init>(ZkClient.java:98)
	at org.I0Itec.zkclient.ZkClient.<init>(ZkClient.java:84)
	at kafka.server.KafkaServer.initZk(KafkaServer.scala:157)
	at kafka.server.KafkaServer.startup(KafkaServer.scala:82)
	at kafka.server.KafkaServerStartable.startup(KafkaServerStartable.scala:29)
	at kafka.Kafka$.main(Kafka.scala:46)
	at kafka.Kafka.main(Kafka.scala)
[2017-07-28 13:32:34,145] INFO EventThread shut down (org.apache.zookeeper.ClientCnxn)
[2017-07-28 13:32:34,150] INFO [Kafka Server 0], shutting down (kafka.server.KafkaServer)

**Comment by rayzhang0603** [comment]
zkclient无法链接zk server。可以检查一下zkserver的ip配置是否正确、与zk server直接的网络是否可以正常联通。或者在报错的服务器直接用zk客户端连接zkserver试试

**Comment by vishal2232** [comment]
谢谢我配置成功
