### ISSUE TITLE
motan client 在与注册中心交互时 read timed out 

### ISSUE THREAD

**Issue by lomelee** [weibocom/motan#511]
使用 consul 作为注册中心时， motan client 不定时（报错）

11:16:27.450 [Thread-11] ERROR error - group lookup thread fail!
com.ecwid.consul.transport.TransportException: java.net.SocketTimeoutException: Read timed out
	at com.ecwid.consul.transport.AbstractHttpTransport.executeRequest(AbstractHttpTransport.java:96)
	at com.ecwid.consul.transport.AbstractHttpTransport.makeGetRequest(AbstractHttpTransport.java:55)
	at com.ecwid.consul.v1.ConsulRawClient.makeGetRequest(ConsulRawClient.java:81)
	at com.ecwid.consul.v1.health.HealthConsulClient.getHealthServices(HealthConsulClient.java:99)
	at com.ecwid.consul.v1.health.HealthConsulClient.getHealthServices(HealthConsulClient.java:80)
	at com.ecwid.consul.v1.ConsulClient.getHealthServices(ConsulClient.java:399)
	at com.weibo.api.motan.registry.consul.client.ConsulEcwidClient.lookupHealthService(ConsulEcwidClient.java:50)
	at com.weibo.api.motan.registry.consul.ConsulRegistry.lookupConsulService(ConsulRegistry.java:258)
	at com.weibo.api.motan.registry.consul.ConsulRegistry.lookupServiceUpdate(ConsulRegistry.java:216)
	at com.weibo.api.motan.registry.consul.ConsulRegistry.access$100(ConsulRegistry.java:21)
	at com.weibo.api.motan.registry.consul.ConsulRegistry$ServiceLookupThread.run(ConsulRegistry.java:343)
Caused by: java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:170)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:137)
	at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:153)
	at org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:282)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:140)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:57)
	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259)
	at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:163)
	at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:167)
	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:273)
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:271)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:71)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:220)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:164)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:139)
	at com.ecwid.consul.transport.AbstractHttpTransport.executeRequest(AbstractHttpTransport.java:80)
	... 10 common frames omitted

但是 consul 再这个时间点有确实有回复消息

![image](https://user-images.githubusercontent.com/12658216/29394640-3dafcb24-833e-11e7-84ec-5af333284b3d.png)

跟踪代码，或者 断点调试，又不在再现

![image](https://user-images.githubusercontent.com/12658216/29394717-b83a3aa0-833e-11e7-90fe-ffec9a942502.png)

**Comment by rayzhang0603** [comment]
看异常信息应该是ecwid的consulclient调用超时了，可以适当调大超时时间看看。另外偶发的consul查询失败不会对服务产生影响

**Comment by wangwei418** [comment]
@icerleer  不知道楼主解决了没。我感觉这个不是偶尔报错 是过一段就必然read timeout
。只有一个模块这样不知道是jar 依赖问题 还是怎么弄的

**Comment by woshizhouqiang** [comment]
@rayzhang0603  
motan 设置consul的阻塞时间是10min,  
 

        /**
	 * consul block 查询时 block的最长时间,单位，分钟
	 */
	public static int CONSUL_BLOCK_TIME_MINUTES = 10;


用的http的方式查询， http的 设置响应的超时时间也是10min， 


          // 10 minutes for read timeout due to blocking queries timeout  
	  // https://www.consul.io/api/index.html#blocking-queries  
	  static final int DEFAULT_READ_TIMEOUT = 60000 * 10; // 10 min


所以过10分钟有时候会打印这种日志出来。 
consul 指定的阻塞时间少于10min应该就不会有这种日志了。 
motan 的这个参数并不可配。
现在我们环境基本上每隔10分钟必现这个日志，error级别的日志， 不喜欢在线上看到这样的日志。


        while (true) {
                try {
                    sleep(lookupInterval);
                    ConcurrentHashMap<String, List<URL>> groupUrls = lookupServiceUpdate(group);
                    updateServiceCache(group, groupUrls, true);
                } catch (Throwable e) {
                    LoggerUtil.error("group lookup thread fail!", e);
                    try {
                        Thread.sleep(2000);
                    } catch (InterruptedException ignored) {
                    }
                }
            }





是不是可以指定consul 的阻塞时间少于10分钟？

**Comment by rayzhang0603** [comment]
@woshizhouqiang 非常感谢反馈 ，我们尽快确认一下这个问题，可以考虑降低block的时间。
