### ISSUE TITLE
heartbeat 会一直在尝试已经注销的节点

### ISSUE THREAD

**Issue by hebo1982** [weibocom/motan#526]
不知道是不是bug，使用的zookeeper发现节点。
这边是k8s管理的，重启后client 部分会报异常。然而在zookeeper内已经删除了这个节点。

172.30.39.6 节点已经销毁，而且zookeeper已经更新。但heartbeat错误一直存在。日志如下：

19:09:23.942 [pool-3-thread-1] ERROR error - NettyClient heartbeat Error: url=motan://172.30.39.6:8002/rose.gen.api.com.chaoxing.iclassstar.dao.ICourseSVC
com.weibo.api.motan.exception.MotanServiceException: error_message: NettyChannel connect to server timeout url: motan://172.30.39.6:8002/rose.gen.api.com.chaoxing.iclassstar.dao.ICourseSVC, cost: 1000, result: false, success: false, connected: false, status: 503, error_code: 10001,r=null
        at com.weibo.api.motan.transport.netty.NettyChannel.open(NettyChannel.java:155) ~[motan-transport-netty-0.3.1.jar:?]
        at com.weibo.api.motan.transport.netty.NettyChannelFactory.makeObject(NettyChannelFactory.java:53) ~[motan-transport-netty-0.3.1.jar:?]
        at org.apache.commons.pool.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:1148) ~[com.springsource.org.apache.commons.pool-1.5.3.jar:1.5.3]
        at com.weibo.api.motan.transport.AbstractPoolClient.borrowObject(AbstractPoolClient.java:75) ~[motan-core-0.3.1.jar:?]
        at com.weibo.api.motan.transport.netty.NettyClient.request(NettyClient.java:164) ~[motan-transport-netty-0.3.1.jar:?]
        at com.weibo.api.motan.transport.netty.NettyClient.heartbeat(NettyClient.java:136) [motan-transport-netty-0.3.1.jar:?]
        at com.weibo.api.motan.transport.support.HeartbeatClientEndpointManager$1.run(HeartbeatClientEndpointManager.java:70) [motan-core-0.3.1.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_131]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_131]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_131]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_131]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_131]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_131]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]

**Comment by hebo1982** [comment]
日志好像是旧的，再观察一下。

**Comment by hanzhihua** [comment]
我也遇到同样的问题，不知道你有没有解决呢？

**Comment by rayzhang0603** [comment]
@hanzhihua 可以确认一下：
1、zk中是否已经没有server节点信息
2、在client端info日志搜索关键词`ClusterSupport config change notify` 看看最后一次从注册中心收到的通知中有没有对应的server节点。
3、如果注册中心的通知日志中没有这个server节点，但是仍然有该节点的调用异常，请提供一些异常栈信息

**Comment by hanzhihua** [comment]
![image](https://user-images.githubusercontent.com/1732108/42496398-7b06aa58-8458-11e8-92a7-e22ca0fa50d6.png)
很容易重现的，就是节点全部下线，只有一个注册中心的情况，心跳一直在尝试

**Comment by rayzhang0603** [comment]
@hanzhihua 这个是预期行为。

client端有保护策略，会忽略注册中心的0节点的通知。当注册中心没有server节点时，除了所有server节点确实不可用外，还有可能是注册中心异常或者server到注册中心的网络异常。这种情况下继续使用最后一次可用节点可以起到一定的保护作用。

此时，如果节点确实不可用，会触发client端的自动摘除策略，并启动心跳机制。这时的心跳异常，不会造成额外的问题。

**Comment by hanzhihua** [comment]
有两个问题，
首先心跳出错的，错误日志实在太多了，监控异常会太多
第二个，如果注册中心告诉client端server没有节点了，说明注册中心与client连接是正常的，那只有一种异常情况（server与注册中心连接异常，但与client连接正常），这种情况如果要服务框架去处理，是不是设计过度了
另外这种smartclient的架构，还是相信注册中心的推送，这个是基础，而且工作会简单很多

**Comment by hanzhihua** [comment]
谢谢你的快速回复！
motan heartbeat好像与普通rpc的heartbeat不太一样，并不对idle连接的check,你们设计主要初衷是什么？
另外为什么你们不对idle的连接做check呢？全部交给了pool吗？

**Comment by rayzhang0603** [comment]
@hanzhihua motan的心跳机制主要作用是网络故障探测、恢复，并不是链接保活。链接层面交由tcp的keepalive管理
