### ISSUE TITLE
maxContentLength参数不生效

### ISSUE THREAD

**Issue by 89333367** [weibocom/motan#563]
```
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xmlns:motan="http://api.weibo.com/schema/motan" xmlns="http://www.springframework.org/schema/beans"
       xmlns:context="http://www.springframework.org/schema/context"
       xsi:schemaLocation="http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans.xsd http://api.weibo.com/schema/motan http://api.weibo.com/schema/motan.xsd http://www.springframework.org/schema/context http://www.springframework.org/schema/context/spring-context.xsd">

    <context:property-placeholder location="classpath*:spring-hbase.properties" ignore-unresolvable="true"/>

    <motan:registry regProtocol="zookeeper" name="motan_zookeeper" address="${spring.hbase.zookeeper}"/>

    <motan:protocol maxWorkerThread="1500" maxClientConnection="500" maxContentLength="104857600" name="motan"/>

    <motan:service interface="uml.api.bigdata.BigDataApi" ref="bigDataApi" export="motan:8002"
                   registry="motan_zookeeper" retries="3"/>

    <motan:service interface="uml.api.bigdata.CommandApi" ref="commandApi" export="motan:8003"
                   registry="motan_zookeeper" retries="3" />

</beans>
```

报错
```
[umltech]WARN 2017-10-31 14:44:11 warn com.weibo.api.motan.log.DefaultLogService.warn(DefaultLogService.java:71) NettyDecoder transport data content length over of limit, size: 10766852  > 10485760. remote=/172.16.1.14:8004 local=/172.16.1.151:63974
[umltech]ERROR 2017-10-31 14:44:11 error com.weibo.api.motan.log.DefaultLogService.error(DefaultLogService.java:87) NettyChannelHandler exceptionCaught: remote=/172.16.1.14:8004 local=/172.16.1.151:63974 event=com.weibo.api.motan.exception.MotanServiceException: error_message: NettyDecoder transport data content length over of limit, size: 10766852 > 10485760, status: 503, error_code: 10001,r=null
com.weibo.api.motan.exception.MotanServiceException: error_message: NettyDecoder transport data content length over of limit, size: 10766852 > 10485760, status: 503, error_code: 10001,r=null
  at com.weibo.api.motan.transport.netty.NettyDecoder.decode(NettyDecoder.java:86)
  at org.jboss.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:282)
  at org.jboss.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:214)
  at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:274)
  at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:261)
  at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:349)
  at org.jboss.netty.channel.socket.nio.NioWorker.processSelectedKeys(NioWorker.java:280)
  at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:200)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  at java.lang.Thread.run(Thread.java:745)
[umltech]INFO 2017-10-31 14:44:11 info com.weibo.api.motan.log.DefaultLogService.info(DefaultLogService.java:55) NettyChannelHandler channelDisconnected: remote=/172.16.1.14:8004 local=/172.16.1.151:63974 event=UpstreamChannelStateEvent
[umltech]ERROR 2017-10-31 14:44:11 error com.weibo.api.motan.log.DefaultLogService.error(DefaultLogService.java:87) NettyChannelHandler exceptionCaught: remote=/172.16.1.14:8004 local=/172.16.1.151:63974 event=com.weibo.api.motan.exception.MotanFrameworkException: error_message: NettyDecoder transport header not support, type: -3856, status: 503, error_code: 20001,r=null
com.weibo.api.motan.exception.MotanFrameworkException: error_message: NettyDecoder transport header not support, type: -3856, status: 503, error_code: 20001,r=null
  at com.weibo.api.motan.transport.netty.NettyDecoder.decode(NettyDecoder.java:67)
  at org.jboss.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:282)
  at org.jboss.netty.handler.codec.frame.FrameDecoder.cleanup(FrameDecoder.java:333)
  at org.jboss.netty.handler.codec.frame.FrameDecoder.channelDisconnected(FrameDecoder.java:226)
  at org.jboss.netty.channel.Channels.fireChannelDisconnected(Channels.java:360)
  at org.jboss.netty.channel.socket.nio.NioWorker.close(NioWorker.java:593)
  at org.jboss.netty.channel.socket.nio.NioClientSocketPipelineSink.eventSunk(NioClientSocketPipelineSink.java:91)
  at org.jboss.netty.handler.codec.oneone.OneToOneEncoder.handleDownstream(OneToOneEncoder.java:60)
  at org.jboss.netty.channel.Channels.close(Channels.java:720)
  at org.jboss.netty.channel.AbstractChannel.close(AbstractChannel.java:200)
  at com.weibo.api.motan.transport.netty.NettyChannelHandler.exceptionCaught(NettyChannelHandler.java:166)
  at org.jboss.netty.handler.codec.frame.FrameDecoder.exceptionCaught(FrameDecoder.java:238)
  at org.jboss.netty.channel.Channels.fireExceptionCaught(Channels.java:432)
  at org.jboss.netty.channel.AbstractChannelSink.exceptionCaught(AbstractChannelSink.java:52)
  at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:274)
  at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:261)
  at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:349)
  at org.jboss.netty.channel.socket.nio.NioWorker.processSelectedKeys(NioWorker.java:280)
  at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:200)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  at java.lang.Thread.run(Thread.java:745)
```

```
NettyDecoder transport data content length over of limit, size: 10766852  > 10485760. remote=/172.16.1.14:8004 
```

这里应该是说超过10M了。

**Comment by sunnights** [comment]
看报错是decode时候报的错，应该是client收到的response大小超过了默认maxContentLength限制  
可以检查一下client端的maxContentLength参数是否也更改了

**Comment by 89333367** [comment]
https://github.com/weibocom/motan/wiki/zh_configuration
这里面没有说clent端可以设置maxContentLength的参数啊

**Comment by sunnights** [comment]
protocol配置是server、client共用的
