### ISSUE TITLE
motan-jar冲突问题：spring4.2.4+motan0.3.0启动报错，版本依赖有什么要求吗

### ISSUE THREAD

**Issue by zhang1025** [weibocom/motan#569]

**Comment by zhang1025** [comment]
@rayzhang0603

**Comment by rayzhang0603** [comment]
对版本应该没有什么特殊要求，看看具体的报错信息吧

**Comment by zhang1025** [comment]
@rayzhang0603    
用motan 0.2.1版本没报错，换成0.3.1报如下的错误：
Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name com.weibo.api.motan.config.springsupport.ServiceConfigBean: BeanPostProcessor before instantiation of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name org.springframework.transaction.config.internalTransactionAdvisor: Cannot resolve reference to bean org.springframework.transaction.annotation.AnnotationTransactionAttributeSource#0 while setting bean property transactionAttributeSource; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name org.springframework.transaction.annotation.AnnotationTransactionAttributeSource#0: BeanPostProcessor before instantiation of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name org.springframework.aop.support.DefaultBeanFactoryPointcutAdvisor#0: Initialization of bean failed; nested exception is java.lang.NoSuchMethodError: org.springframework.beans.factory.config.ConfigurableBeanFactory.getSingletonMutex()Ljava/lang/Object;
ERROR | Context initialization failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name com.weibo.api.motan.config.springsupport.ServiceConfigBean: BeanPostProcessor before instantiation of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name org.springframework.transaction.config.internalTransactionAdvisor: Cannot resolve reference to bean org.springframework.transaction.annotation.AnnotationTransactionAttributeSource#0 while setting bean property transactionAttributeSource; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name org.springframework.transaction.annotation.AnnotationTransactionAttributeSource#0: BeanPostProcessor before instantiation of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name org.springframework.aop.support.DefaultBeanFactoryPointcutAdvisor#0: Initialization of bean failed; nested exception is java.lang.NoSuchMethodError: org.springframework.beans.factory.config.ConfigurableBeanFactory.getSingletonMutex()Ljava/lang/Object;
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:472)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:303)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:299)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.registerBeanPostProcessors(PostProcessorRegistrationDelegate.java:232)
	at org.springframework.context.support.AbstractApplicationContext.registerBeanPostProcessors(AbstractApplicationContext.java:619)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:465)
	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:444)
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:326)
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:107)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:5118)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5634)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:145)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1571)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1561)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name org.springframework.transaction.config.internalTransactionAdvisor: Cannot resolve reference to bean org.springframework.transaction.annotation.AnnotationTransactionAttributeSource#0 while setting bean property transactionAttributeSource; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name org.springframework.transaction.annotation.AnnotationTransactionAttributeSource#0: BeanPostProcessor before instantiation of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name org.springframework.aop.support.DefaultBeanFactoryPointcutAdvisor#0: Initialization of bean failed; nested exception is java.lang.NoSuchMethodError: org.springframework.beans.factory.config.ConfigurableBeanFactory.getSingletonMutex()Ljava/lang/Object;
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:359)
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveValueIfNecessary(BeanDefinitionValueResolver.java:108)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1475)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1220)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:537)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:476)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:303)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:299)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.aop.framework.autoproxy.BeanFactoryAdvisorRetrievalHelper.findAdvisorBeans(BeanFactoryAdvisorRetrievalHelper.java:92)
	at org.springframework.aop.framework.autoproxy.AbstractAdvisorAutoProxyCreator.findCandidateAdvisors(AbstractAdvisorAutoProxyCreator.java:101)
	at org.springframework.aop.aspectj.autoproxy.AspectJAwareAdvisorAutoProxyCreator.shouldSkip(AspectJAwareAdvisorAutoProxyCreator.java:103)
	at org.springframework.aop.framework.autoproxy.AbstractAutoProxyCreator.postProcessBeforeInstantiation(AbstractAutoProxyCreator.java:249)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInstantiation(AbstractAutowireCapableBeanFactory.java:982)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.resolveBeforeInstantiation(AbstractAutowireCapableBeanFactory.java:953)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:466)
	... 19 more
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name org.springframework.transaction.annotation.AnnotationTransactionAttributeSource#0: BeanPostProcessor before instantiation of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name org.springframework.aop.support.DefaultBeanFactoryPointcutAdvisor#0: Initialization of bean failed; nested exception is java.lang.NoSuchMethodError: org.springframework.beans.factory.config.ConfigurableBeanFactory.getSingletonMutex()Ljava/lang/Object;
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:472)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:303)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:299)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:194)
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:351)
	... 35 more

**Comment by rayzhang0603** [comment]
这个应该跟spring的版本冲突有关，看看这个有帮助没有https://stackoverflow.com/questions/34191085/upgrade-to-spring-boot-1-3-causes-java-lang-nosuchmethoderror-org-springframewo

**Comment by zhang1025** [comment]
感谢 ，是我项目中mybatis-spring 的版本与 引用的spring的核心版本冲突了，mybatis-spring 的版本太低了，再次感谢

**Comment by zhang1025** [comment]
@rayzhang0603  麻烦请教一下   tomcat启动报这个错误怎么解决
Nov 07, 2017 7:01:08 PM org.apache.catalina.loader.WebappClassLoaderBase clearReferencesThreads
SEVERE: The web application [] appears to have started a thread named [nettyServerBoss-1-thread-1] but has failed to stop it. This is very likely to create a memory leak.
Nov 07, 2017 7:01:08 PM org.apache.catalina.loader.WebappClassLoaderBase clearReferencesThreads
SEVERE: The web application [] appears to have started a thread named [pool-2-thread-1] but has failed to stop it. This is very likely to create a memory leak.
Nov 07, 2017 7:01:08 PM org.apache.catalina.loader.WebappClassLoaderBase clearReferencesThreads
SEVERE: The web application [] appears to have started a thread named [ZkClient-EventThread-50-10.137.88.16:2181,10.137.88.16:2182,10.137.88.16:2183] but has failed to stop it. This is very likely to create a memory leak.
Nov 07, 2017 7:01:08 PM org.apache.catalina.loader.WebappClassLoaderBase clearReferencesThreads
SEVERE: The web application [] appears to have started a thread named [localhost-startStop-1-SendThread(10.137.88.16:2183)] but has failed to stop it. This is very likely to create a memory leak.
Nov 07, 2017 7:01:08 PM org.apache.catalina.loader.WebappClassLoaderBase clearReferencesThreads
SEVERE: The web application [] appears to have started a thread named [localhost-startStop-1-EventThread] but has failed to stop it. This is very likely to create a memory leak.
Nov 07, 2017 7:01:08 PM org.apache.catalina.loader.WebappClassLoaderBase clearReferencesThreads
SEVERE: The web application [] appears to have started a thread named [pool-3-thread-1] but has failed to stop it. This is very likely to create a memory leak.
Nov 07, 2017 7:01:08 PM org.apache.catalina.loader.WebappClassLoaderBase clearReferencesThreads
SEVERE: The web application [] appears to have started a thread named [MySQL Statement Cancellation Timer] but has failed to stop it. This is very likely to create a memory leak.
Nov 07, 2017 7:01:08 PM org.apache.catalina.loader.WebappClassLoaderBase checkThreadLocalMapForLeaks
SEVERE: The web application [] created a ThreadLocal with key of type [com.weibo.api.motan.rpc.RpcContext$1] (value [com.weibo.api.motan.rpc.RpcContext$1@382bb151]) and a value of type [com.weibo.api.motan.rpc.RpcContext] (value [com.weibo.api.motan.rpc.RpcContext@64d55c00]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
Nov 07, 2017 7:01:08 PM org.apache.coyote.AbstractProtocol start
INFO: Starting ProtocolHandler ["http-bio-8084"]
Nov 07, 2017 7:01:08 PM org.apache.coyote.AbstractProtocol start
INFO: Starting ProtocolHandler ["ajp-bio-7084"]
Nov 07, 2017 7:01:08 PM org.apache.catalina.startup.Catalina start
INFO: Server startup in 4522 ms
Nov 07, 2017 7:01:37 PM org.apache.catalina.loader.WebappClassLoaderBase loadClass
INFO: Illegal access: this web application instance has been stopped already.  Could not load java.text.DecimalFormat.  The eventual following stack trace is caused by an error thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access, and has no functional impact.
java.lang.IllegalStateException
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1777)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1735)
	at com.weibo.api.motan.util.StatsUtil.logAccessStatistic(StatsUtil.java:185)
	at com.weibo.api.motan.util.StatsUtil$1.run(StatsUtil.java:55)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by rayzhang0603** [comment]
这个不是导致启动失败的原因，这个是tomcat启动失败后，停止服务时产生的异常。看看localhost.**的日志，看看有没有导致tomcat启动失败的原因吧

**Comment by zhang1025** [comment]
@rayzhang0603  在启动motan服务的时候出现这个错误 
configService is malformed, for same service (%s) already exists
我看服务异常给出的错误提示是：暴露的服务已经存在，需要检查暴露的服务是否存在重复定义，服务的唯一标志：group/interface/version
我检查了相应服务配置的group  interface  以及 export 都没有重复的，其他接口服务都正常，就某一个死活不行，把这个服务注释掉就启动成功了。实在找不出哪里有问题，请教~~~

**Comment by rayzhang0603** [comment]
应该还是配置的问题，可以贴一下具体的xml配置。
按说错误日志会把service相关信息打印出来，但是你给出的日志中没有，这个问题最好debug一下确定原因

**Comment by zhang1025** [comment]
@rayzhang0603  应该是motan版本的问题  ，我换成0.2.0就没有问题  用0.3.1就会出现上面的错误，这个很奇怪，版本问题难道不兼容还是配置有什么大的区别？我看给出的配置没有啥大区别啊

**Comment by rayzhang0603** [comment]
0.3.1与0.2.0不存在版本兼容问题。建议debug调试一下确定原因。

**Comment by zhang1025** [comment]
配置信息：

    <motan:protocol id="motan" name="motan" default="true" loadbalance="random"
                    maxClientConnection="500" minClientConnection="5"
                    maxServerConnection="80000" maxContentLength="1048576"
                    maxWorkerThread="800" minWorkerThread="20"/>

    
    <motan:registry regProtocol="zookeeper" name="zkRegistry" address="${zookeeper.address}"
                    connectTimeout="5000" requestTimeout="10000"
                    check="true" register="true"/>
<motan:basicService id="config"
                        application="bc-server" group="bc-server"
                        registry="zkRegistry"
                        export="motan:9001" shareChannel="true"/>

anchorServiceImpl这个服务没有问题
<bean id="anchorServiceImpl" class="com.test.bc.anchor.service.AnchorServiceImpl"/>
	<motan:service group="bc-anchor" export="motan:9003"
                   interface="com.test.bc.api.anchor.AnchorService" ref="anchorServiceImpl"
                   basicService="config"/>
但是 authentication 一直报上面我说的configService is malformed, for same service (%s) already exists错误
 <bean id="authenticationImpl" class="com.test.bc.authentication.service.AuthenticationServiceImpl"/>
  <motan:service group="bc-authc" export="motan:9002"
                   interface="com.test.bc.api.authentication.AuthenticationService" ref="authenticationImpl"
                   basicService="config"/>

jar版本信息
<properties>
        
        <spring.version>4.3.3.RELEASE</spring.version>
        
        <mybatis.version>3.2.4</mybatis.version>
        <mybatis-spring.version>1.3.0</mybatis-spring.version>
        
        <slf4j.version>1.6.6</slf4j.version>
        <log4j.version>1.2.8</log4j.version>
        
        <motan.version>0.3.1</motan.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

**Comment by zhang1025** [comment]
@rayzhang0603  上面的配置有什么问题吗
