### ISSUE TITLE
com.weibo.api.motan.config.handler.SimpleConfigHandler.register Exception!

### ISSUE THREAD

**Issue by thisxulz** [weibocom/motan#57]
Hello，
我在本地Eclipse上运行没有问题，打成架包以后放到linux服务器上运行就报如下错误？是什么问题？
Exception in thread "main" java.lang.NullPointerException
    at com.weibo.api.motan.config.handler.SimpleConfigHandler.register(SimpleConfigHandler.java:102)
    at com.weibo.api.motan.config.handler.SimpleConfigHandler.export(SimpleConfigHandler.java:77)
    at com.weibo.api.motan.config.ServiceConfig.doExport(ServiceConfig.java:211)
    at com.weibo.api.motan.config.ServiceConfig.export(ServiceConfig.java:129)
    at com.weibo.api.motan.config.springsupport.ServiceConfigBean.onApplicationEvent(ServiceConfigBean.java:90)
    at com.weibo.api.motan.config.springsupport.ServiceConfigBean.onApplicationEvent(ServiceConfigBean.java:42)
    at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:98)
    at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:333)
    at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:776)
    at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:485)
    at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:139)
    at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:83)

**Comment by XuJun0909** [comment]
jar在windows下运行有问题吗

**Comment by qdaxb** [comment]
应该是classpath下没有对应registry的jar包。

**Comment by thisxulz** [comment]
确实是我打包的问题。。已成功
