### ISSUE TITLE
not support java.time.LocalDateTime

### ISSUE THREAD

**Issue by hank-whu** [weibocom/motan#577]
the default config cannot support java.time.LocalDateTime

**Comment by rayzhang0603** [comment]
hessian2 do not support java.time.LocalDateTime, you can use hprose as Serialization. config like this:

    <motan:protocol id="***" name="motan" serialization="hprose" ....

**Comment by hank-whu** [comment]
cannot work,

com.weibo.api.motan.exception.MotanFrameworkException: error_message: encode error: isResponse=true, status: 503, error_code: 20002,r=1584007805187130080
	at com.weibo.api.motan.protocol.rpc.DefaultRpcCodec.encode(DefaultRpcCodec.java:67)
	at com.weibo.api.motan.transport.netty.NettyEncoder.encodeMessage(NettyEncoder.java:78)
	at com.weibo.api.motan.transport.netty.NettyEncoder.encodev1(NettyEncoder.java:63)
	at com.weibo.api.motan.transport.netty.NettyEncoder.encode(NettyEncoder.java:52)
	at org.jboss.netty.handler.codec.oneone.OneToOneEncoder.handleDownstream(OneToOneEncoder.java:66)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:591)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendDownstream(DefaultChannelPipeline.java:776)
	at org.jboss.netty.channel.SimpleChannelHandler.writeRequested(SimpleChannelHandler.java:304)
	at org.jboss.netty.channel.SimpleChannelHandler.handleDownstream(SimpleChannelHandler.java:266)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:591)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:582)
	at org.jboss.netty.channel.Channels.write(Channels.java:611)
	at org.jboss.netty.channel.Channels.write(Channels.java:578)
	at org.jboss.netty.channel.AbstractChannel.write(AbstractChannel.java:251)
	at com.weibo.api.motan.transport.netty.NettyChannelHandler.processRequest(NettyChannelHandler.java:155)
	at com.weibo.api.motan.transport.netty.NettyChannelHandler.access$000(NettyChannelHandler.java:43)
	at com.weibo.api.motan.transport.netty.NettyChannelHandler$1.run(NettyChannelHandler.java:112)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException: null
	at com.weibo.api.motan.codec.AbstractCodec.serialize(AbstractCodec.java:44)
	at com.weibo.api.motan.protocol.rpc.DefaultRpcCodec.encodeResponse(DefaultRpcCodec.java:237)
	at com.weibo.api.motan.protocol.rpc.DefaultRpcCodec.encode(DefaultRpcCodec.java:61)
	... 19 common frames omitted

**Comment by hank-whu** [comment]
the motan version is 1.0.0

**Comment by rayzhang0603** [comment]
hprose是motan的spi扩展，使用spi扩展时需要保证已经依赖了对应的jar包。motan-extension包下是一些扩展的SPI实现。
使用hprose 需要引入下面依赖

    <dependency>
      <groupId>com.weibo</groupId>
      <artifactId>serialization-extension</artifactId>
      <version>1.0.0</version>
    </dependency>

**Comment by allenwtl** [comment]
使用 hprose 出现 类型转换 异常  为啥
