### ISSUE TITLE
hot to graceful shutdown the client ? 

### ISSUE THREAD

**Issue by hank-whu** [weibocom/motan#578]
at sun.misc.Unsafe.park(Native Method)
  at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
  at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
  at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1088)
  at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:809)
  at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1067)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  at java.lang.Thread.run(Thread.java:745)

**Comment by rayzhang0603** [comment]
you can register a ShutdownHook to call `com.weibo.api.motan.closable.ShutDownHook.runHook(boolean sync)` .
or add `com.weibo.api.motan.closable.ShutDownHookListener`  if you start motan by using a webcontainer like tomcat.

**Comment by hank-whu** [comment]
thanks
