### ISSUE TITLE
版本升级到1.0.0后出现的问题

### ISSUE THREAD

**Issue by winner1207** [weibocom/motan#599]
motan版本从0.2.1升级到1.0.0，代码没做任何变动，在motan-manager里面查询server端和client端都是正常的，但是就是无法获取到server，报错信息如下：
2017-12-01 16:59:02,207 pool-4-thread-4 [ERROR][error] RefererInvocationHandler invoke Error: uri=motan://192.168.2.1:0/com.yichat.rpc.motan.MotanWechatService requestId=1585571422228447236 interface=com.yichat.rpc.motan.MotanWechatService method=sendChatMsg(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String)
com.weibo.api.motan.exception.MotanServiceException: error_message: ActiveWeightLoadBalance No available referers for call : referers_size= 0 requestId=1585571422228447236 interface=com.yichat.rpc.motan.MotanWechatService method=sendChatMsg(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String), status: 503, error_code: 10001,r=null
	at com.weibo.api.motan.cluster.loadbalance.AbstractLoadBalance.selectToHolder(AbstractLoadBalance.java:70)
	at com.weibo.api.motan.cluster.ha.FailoverHaStrategy.selectReferers(FailoverHaStrategy.java:90)

**Comment by winner1207** [comment]
补充一下，maven的版本如下：
motan-core-version：1.0.0
motan-transport-netty-version：1.0.0
motan-springsupport-version：1.0.0
motan-registry-zookeeper-version：1.0.0

**Comment by winner1207** [comment]
是我自己配置的问题哈，已解决
