### ISSUE TITLE
MotanFrameworkException

### ISSUE THREAD

**Issue by ZhouXunYou** [weibocom/motan#601]
hello Ray:
我在启动服务时抛出异常：
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'databaseServiceExport' defined in file [D:\workspace\default.workspace\platform\platform-service\platform-service-database\target\classes\platform\service\database\export\DatabaseServiceExport.class]: Initialization of bean failed; nested exception is com.weibo.api.motan.exception.MotanFrameworkException: error_message: Protocol is null when construct ProtocolFilterDecorator, status: 500, error_code: 20004,r=null
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:564) ~[spring-beans-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483) ~[spring-beans-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306) ~[spring-beans-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) ~[spring-beans-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302) ~[spring-beans-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197) ~[spring-beans-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:761) ~[spring-beans-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:867) ~[spring-context-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:543) ~[spring-context-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:693) ~[spring-boot-1.5.9.RELEASE.jar:1.5.9.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:360) ~[spring-boot-1.5.9.RELEASE.jar:1.5.9.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303) ~[spring-boot-1.5.9.RELEASE.jar:1.5.9.RELEASE]
	at platform.service.database.Launcher.main(Launcher.java:14) [classes/:na]
Caused by: com.weibo.api.motan.exception.MotanFrameworkException: error_message: Protocol is null when construct ProtocolFilterDecorator, status: 500, error_code: 20004,r=null
	at com.weibo.api.motan.protocol.support.ProtocolFilterDecorator.<init>(ProtocolFilterDecorator.java:50) ~[motan-core-1.0.0.jar:na]
	at com.weibo.api.motan.config.handler.SimpleConfigHandler.export(SimpleConfigHandler.java:78) ~[motan-core-1.0.0.jar:na]
	at com.weibo.api.motan.config.ServiceConfig.doExport(ServiceConfig.java:211) ~[motan-core-1.0.0.jar:na]
	at com.weibo.api.motan.config.ServiceConfig.export(ServiceConfig.java:129) ~[motan-core-1.0.0.jar:na]
	at com.weibo.api.motan.config.springsupport.AnnotationBean.postProcessAfterInitialization(AnnotationBean.java:324) ~[motan-springsupport-1.0.0.jar:na]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsAfterInitialization(AbstractAutowireCapableBeanFactory.java:423) ~[spring-beans-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1633) ~[spring-beans-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555) ~[spring-beans-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	... 12 common frames omitted

具体代码如下：
@Bean
	public AnnotationBean motanAnnotationBean() {
		AnnotationBean motanAnnotationBean = new AnnotationBean();
		motanAnnotationBean.setPackage("platform.service.database.export");
		return motanAnnotationBean;
	}
	@Bean(name = ServiceDatabaseProperties.appName+"MotanProtocol")
	public ProtocolConfigBean getMotanProtocol() {
		ProtocolConfigBean config = new ProtocolConfigBean();
		config.setName("motan");
		config.setHaStrategy("failover");
		config.setRequestTimeout(ServiceDatabaseProperties.timeout);
		config.setLoadbalance(ServiceDatabaseProperties.loadbalance);
		config.setRetries(ServiceDatabaseProperties.retries);
		return config;
	}
	@Bean(name = ServiceDatabaseProperties.appName+"RestfulProtocol")
	public ProtocolConfigBean getRestfulProtocol() {
		ProtocolConfigBean config = new ProtocolConfigBean();
		config.setName("restful");
		config.setEndpointFactory("netty");
		config.setHaStrategy("failover");
		config.setRequestTimeout(ServiceDatabaseProperties.timeout);
		config.setLoadbalance(ServiceDatabaseProperties.loadbalance);
		config.setRetries(ServiceDatabaseProperties.retries);
		return config;
	}

	@Bean(name = ServiceDatabaseProperties.appName+"Registry")
	public RegistryConfigBean registryConfig() {
		RegistryConfigBean config = new RegistryConfigBean();
		config.setRegProtocol(ServiceDatabaseProperties.registry);
		config.setName(ServiceDatabaseProperties.appName+"Registry");
		config.setAddress(ServiceDatabaseProperties.registryServers);
		config.setRegister(true);
		config.setSubscribe(true);
		config.setConnectTimeout(ServiceDatabaseProperties.timeout);
		return config;
	}

	@Bean
	public BasicServiceConfigBean baseServiceConfig() {
		BasicServiceConfigBean config = new BasicServiceConfigBean();
		config.setHost(ServiceDatabaseProperties.exportHost);
		config.setRequestTimeout(ServiceDatabaseProperties.timeout);
		if(ServiceDatabaseProperties.enableRestfulProtocol){
			config.setExport(ServiceDatabaseProperties.appName+"MotanProtocol:" + ServiceDatabaseProperties.exportMotanProtocolPort+","+ServiceDatabaseProperties.appName+"RestfulProtocol:"+ServiceDatabaseProperties.exportRestfulProtocolPort);
		}else{
			config.setExport(ServiceDatabaseProperties.appName+"MotanProtocol:" + ServiceDatabaseProperties.exportMotanProtocolPort);
		}
		config.setGroup(ServiceDatabaseProperties.appName+"Group");
		config.setModule(ServiceDatabaseProperties.appName+"Module");
		config.setApplication(ServiceDatabaseProperties.appName+"Application");
		config.setRegistry(ServiceDatabaseProperties.appName+"Registry");
		config.setRegister(true);
		config.setRetries(ServiceDatabaseProperties.retries);
		config.setShareChannel(true);
		return config;
	}

**Comment by ZhouXunYou** [comment]
已经解决
未引入依赖
<dependency>
	<groupId>com.weibo</groupId>
	<artifactId>motan-protocol-restful</artifactId>
</dependency>
