### ISSUE TITLE
Client关闭的不干净

### ISSUE THREAD

**Issue by hank-whu** [weibocom/motan#643]
Non-finished threads:

Thread[pool-3-thread-2,5,main]
  at sun.misc.Unsafe.park(Native Method)
  at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
  at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
  at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1081)
  at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:809)
  at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1067)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  at java.lang.Thread.run(Thread.java:745)

**Comment by hank-whu** [comment]
如果用netty4的话，还会有另一个线程池未关闭：

Thread[nioEventLoopGroup-2-6,10,main]
  at sun.nio.ch.WindowsSelectorImpl$SubSelector.poll0(Native Method)
  at sun.nio.ch.WindowsSelectorImpl$SubSelector.poll(WindowsSelectorImpl.java:296)
  at sun.nio.ch.WindowsSelectorImpl$SubSelector.access$400(WindowsSelectorImpl.java:278)
  at sun.nio.ch.WindowsSelectorImpl.doSelect(WindowsSelectorImpl.java:159)
  at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
  at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
  at io.netty.channel.nio.SelectedSelectionKeySetSelector.select(SelectedSelectionKeySetSelector.java:62)
  at io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:753)
  at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:409)
  at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
  at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
  at java.lang.Thread.run(Thread.java:745)

**Comment by rayzhang0603** [comment]
如果使用tomcat之类的web容器启动服务的话，可以配置下面这个listener关闭scheduledThreadPool

    com.weibo.api.motan.closable.ShutDownHookListener

如果没有使用的话，可以在系统启动后注册一个ShutdownHook来调用下面的方法：

    com.weibo.api.motan.closable.ShutDownHook.runHook(boolean sync)

**Comment by rayzhang0603** [comment]
@hank-whu transport实现中确实有定时线程池没有加入到shutdownhook中，我们会在下一个小版本fix掉这个问题，感谢反馈！
