### ISSUE TITLE
使用maven-assembly-plugin打包后无法启动

### ISSUE THREAD

**Issue by hank-whu** [weibocom/motan#647]
打包后无法正确加载spi

```java
com.weibo.api.motan.exception.MotanServiceException: error_message: NettyChannel send request to server Error: url=motan://benchmark-server:8080/benchmark.service.UserService local=/127.0.0.1:59206 requestId=1590897288815837200 interface=benchmark.service.UserService method=getUser(long), status: 503, error_code: 10001,r=null
        at com.weibo.api.motan.transport.netty.NettyChannel.request(NettyChannel.java:96)
        at com.weibo.api.motan.transport.netty.NettyClient.request(NettyClient.java:163)
        at com.weibo.api.motan.transport.netty.NettyClient.request(NettyClient.java:110)
        at com.weibo.api.motan.protocol.rpc.DefaultRpcReferer.doCall(DefaultRpcReferer.java:52)
        at com.weibo.api.motan.rpc.AbstractReferer.call(AbstractReferer.java:64)
        at com.weibo.api.motan.cluster.ha.FailfastHaStrategy.call(FailfastHaStrategy.java:38)
        at com.weibo.api.motan.cluster.support.ClusterSpi.call(ClusterSpi.java:73)
        at com.weibo.api.motan.proxy.RefererInvocationHandler.invoke(RefererInvocationHandler.java:132)
        at com.sun.proxy.$Proxy10.getUser(Unknown Source)
        at benchmark.rpc.AbstractClient.getUser(AbstractClient.java:29)
        at benchmark.rpc.Client.getUser(Client.java:75)
        at benchmark.rpc.Client.main(Client.java:91)
Caused by: com.weibo.api.motan.exception.MotanFrameworkException: error_message: encode error: isResponse=false, status: 503, error_code: 20002,r=null
        at com.weibo.api.motan.protocol.rpc.DefaultRpcCodec.encode(DefaultRpcCodec.java:67)
        at com.weibo.api.motan.transport.netty.NettyEncoder.encodeMessage(NettyEncoder.java:86)
        at com.weibo.api.motan.transport.netty.NettyEncoder.encodev1(NettyEncoder.java:63)
        at com.weibo.api.motan.transport.netty.NettyEncoder.encode(NettyEncoder.java:52)
        at org.jboss.netty.handler.codec.oneone.OneToOneEncoder.handleDownstream(OneToOneEncoder.java:66)
        at org.jboss.netty.channel.Channels.write(Channels.java:611)
        at org.jboss.netty.channel.Channels.write(Channels.java:578)
        at org.jboss.netty.channel.AbstractChannel.write(AbstractChannel.java:251)
        at com.weibo.api.motan.transport.netty.NettyChannel.request(NettyChannel.java:65)
        ... 11 common frames omitted
Caused by: java.lang.NullPointerException: null
        at com.weibo.api.motan.codec.AbstractCodec.serialize(AbstractCodec.java:44)
        at com.weibo.api.motan.protocol.rpc.DefaultRpcCodec.encodeRequest(DefaultRpcCodec.java:177)
        at com.weibo.api.motan.protocol.rpc.DefaultRpcCodec.encode(DefaultRpcCodec.java:59)
        ... 19 common frames omitted
java.lang.NullPointerException
        at benchmark.rpc.Client.main(Client.java:91)
```

**Comment by rayzhang0603** [comment]
看这个报错应该是spi扩展的jar没有打包到classpath。可以看一下打包后的结果，所依赖的spi扩展jar包是否一起打包了

**Comment by hank-whu** [comment]
Eclipse中是可以正常运行的，这说明至少是跟maven-assembly-plugin不兼容的.
作为最流行的打包方式，还是有必要兼容一下的.

**Comment by hank-whu** [comment]
![-2](https://user-images.githubusercontent.com/1773861/35502580-6479a372-0518-11e8-97df-80928e8af373.png)
![-1](https://user-images.githubusercontent.com/1773861/35502581-64a8f3a2-0518-11e8-9fc5-0f4dd98fb560.png)

**Comment by hank-whu** [comment]
我检查了下，是你们SPI实现机制有问题导致的，建议参考下Dubbo最新的实现.
区分内部spi 外部spi，内部spi放在META-INF/dubbo/internal下面，以防止冲突.

**Comment by rayzhang0603** [comment]
eclipse中运行正常是因为eclipse的classpath配置了依赖的jar包。你使用assembly打的是一个all-in-one的fat jar，需要把META-INF/services/下的spi配置文件改成追加模式。
区分内外部spi并不能根本解决这个问题，即使外部spi也可能有多个的

**Comment by hank-whu** [comment]
改一下实现方式，扩展配置都放在META-INF/motan目录下，文件名称不做约束以避免冲突，内容里面写明扩展点和实现类？

另外，"spi配置文件改成追加模式"，assembly 还有这高级功能？是说的下面的方式吗？
https://maven.apache.org/plugins/maven-shade-plugin/examples/resource-transformers.html#AppendingTransformer
```xml
<transformers>
  <transformer implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
  <resource>META-INF/com.weibo.api.motan.codec.Serialization</resource>
  </transformer>
</transformers>
```

**Comment by hank-whu** [comment]
@rayzhang0603 
spi配置文件改成追加模式不是一个好的方式，这要求使用者必须深入研究motan的扩展实现细节

区分内部外部spi可以解决掉大部分问题
一般而言，我只是想替换一下序列化方式或者传输方式
这些都是明确的需求，我只引入我想要的kryo或者hprose扩展库就行了
这种情况下是不会出现冲突问题的

**Comment by rayzhang0603** [comment]
只有需要打成一个fat jar的场景需要做追加的配置，一般线上业务的打包场景不会连同依赖jar包打成一个jar，大部分的业务场景下不需要感知这件事。
复杂的业务场景下，会有许多不同类型filter的扩展，这种场景下依然需要配置追加。所以我们觉得能够通过配置解决这个场景就可以了

**Comment by hank-whu** [comment]
@rayzhang0603 
我觉得你还是考虑下我说的方案，现在motan对用户不够友好。
我在做几个rpc框架的性能对比，dubbo按照demo一个小时就搞定跑起来了，压测过程中也没任何问题。
motan就总是遇到跳不过的坑，提了好几个issue找你才搞定。

**Comment by noodles-dumplings** [comment]
@rayzhang0603 
storm项目打成一个jar，目前遇到类似NullPointerException，哭晕在厕所。
