### ISSUE TITLE
哥哥们帮忙看下

### ISSUE THREAD

**Issue by targerr** [weibocom/motan#648]
com.weibo.api.motan.exception.MotanServiceException: error_message: NettyChannel connect to server timeout url: motan://192.168.**6.1:8001/com.toltech.pay.service.biz.OrderService, cost: 1000, result: false, success: false, connected: false, status: 503, error_code: 10001,r=null
	at com.weibo.api.motan.transport.netty.NettyChannel.open(NettyChannel.java:149)
	at com.weibo.api.motan.transport.netty.NettyChannelFactory.makeObject(NettyChannelFactory.java:53)
	at org.apache.commons.pool.impl.GenericObjectPool.addObject(GenericObjectPool.java:1691)
	at com.weibo.api.motan.transport.AbstractPoolClient.createConnections(AbstractPoolClient.java:93)
	at com.weibo.api.motan.transport.AbstractPoolClient.access$000(AbstractPoolClient.java:35)
	at com.weibo.api.motan.transport.AbstractPoolClient$1.run(AbstractPoolClient.java:78)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by sunnights** [comment]
这个报错是因为连接server超时了，可以先看看能不能ping通，如果能ping通，再试试把连接超时的时间设置的大一些
