### ISSUE TITLE
java.lang.NoClassDefFoundError: io/netty/buffer/PoolArena$1

### ISSUE THREAD

**Issue by Python-IBM** [weibocom/motan#651]
官方技术人员，麻烦你们帮忙看下这是什么问题，有PoolArena$1.class这个文件，但提示找不到：

com.weibo.api.motan.log.DefaultLogService.error(DefaultLogService.java:83) - NettyChannelHandler exceptionCaught: remote=/192.168.10.3:46508 local=/192.168.10.6:8601 event=io/netty/buffer/PoolArena$1
java.lang.NoClassDefFoundError: io/netty/buffer/PoolArena$1
  at io.netty.buffer.PoolArena.freeChunk(PoolArena.java:293)
  at io.netty.buffer.PoolThreadCache$MemoryRegionCache.freeEntry(PoolThreadCache.java:472)
  at io.netty.buffer.PoolThreadCache$MemoryRegionCache.free(PoolThreadCache.java:442)
  at io.netty.buffer.PoolThreadCache$MemoryRegionCache.trim(PoolThreadCache.java:460)
  at io.netty.buffer.PoolThreadCache.trim(PoolThreadCache.java:316)
  at io.netty.buffer.PoolThreadCache.trim(PoolThreadCache.java:308)
  at io.netty.buffer.PoolThreadCache.trim(PoolThreadCache.java:295)
  at io.netty.buffer.PoolThreadCache.allocate(PoolThreadCache.java:212)
  at io.netty.buffer.PoolThreadCache.allocateTiny(PoolThreadCache.java:186)
  at io.netty.buffer.PoolArena.allocate(PoolArena.java:181)
  at io.netty.buffer.PoolArena.allocate(PoolArena.java:146)
  at io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:324)
  at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:181)
  at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:172)
  at io.netty.buffer.AbstractByteBufAllocator.ioBuffer(AbstractByteBufAllocator.java:133)
  at io.netty.channel.DefaultMaxMessagesRecvByteBufAllocator$MaxMessageHandle.allocate(DefaultMaxMessagesRecvByteBufAllocator.java:80)
  at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:122)
  at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
  at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
  at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
  at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
  at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
  at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
  at java.lang.Thread.run(Thread.java:744)

**Comment by rayzhang0603** [comment]
这个问题看着像依赖冲突或者对应类在gc时被unload了。
你可以看看项目中是否依赖了不同版本的netty-all或者额外依赖了netty-buffer。可以试试强制指定一下netty-buffer的版本。
或者看看有没有发生过fullgc什么的

**Comment by Python-IBM** [comment]
好的，非常感谢
