### ISSUE TITLE
服务端抛业务异常的时候会意外地打异常栈

### ISSUE THREAD

**Issue by xnslong** [weibocom/motan#723]
目前motan服务端抛常规的业务异常的时候，会意外地打一条错误日志，并打相应的异常栈。比如我有如下一个接口，提供RPC服务给其它人使用，它的功能对指定的人打招呼，逻辑如下：

1. 所以如果参数`name`是`"Tom"`，就抛一个`IllegalArgumentException`（可能是跟Tom吵架了，所以拒绝打招呼）。
2. 对其它所有人都返回一个`"hello, " + name`的字符串，

```java
public interface GreetService {
    String sayHello(String name) throws IllegalArgumentException;
}
```

现在client调用该方法的时候传了`Tom`参数，就会在服务端打了一个类似如下的异常栈：

```
error - Exception caught when during method invocation. request:GreetService.sayHello(java.lang.String) requestId=152964379653438725
java.lang.reflect.InvocationTargetException: null
    at sun.reflect.GeneratedMethodAccessor272.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.weibo.api.motan.rpc.DefaultProvider.invoke(DefaultProvider.java:64)
    at com.weibo.api.motan.rpc.AbstractProvider.call(AbstractProvider.java:49)
    at com.weibo.api.motan.filter.AccessLogFilter.filter(AccessLogFilter.java:56)
    at com.weibo.api.motan.protocol.support.ProtocolFilterDecorator$2.call(ProtocolFilterDecorator.java:149)
    at com.weibo.api.motan.weibo.filter.WeiboAccessStatisticFilter.filter(WeiboAccessStatisticFilter.java:110)
    at com.weibo.api.motan.protocol.support.ProtocolFilterDecorator$2.call(ProtocolFilterDecorator.java:149)
    at com.weibo.api.motan.protocol.support.ProtocolFilterDecorator$2.call(ProtocolFilterDecorator.java:149)
    at com.weibo.api.motan.protocol.support.ProtocolFilterDecorator$2.call(ProtocolFilterDecorator.java:149)
    at com.weibo.api.motan.weibo.filter.WeiboContextFilter.filter(WeiboContextFilter.java:56)
    at com.weibo.api.motan.protocol.support.ProtocolFilterDecorator$2.call(ProtocolFilterDecorator.java:149)
    at com.weibo.api.motan.transport.ProviderMessageRouter.call(ProviderMessageRouter.java:98)
    at com.weibo.api.motan.transport.ProviderProtectedMessageRouter.call(ProviderProtectedMessageRouter.java:79)
    at com.weibo.api.motan.transport.ProviderMessageRouter.handle(ProviderMessageRouter.java:93)
    at com.weibo.api.motan.transport.support.DefaultRpcHeartbeatFactory$HeartMessageHandleWrapper.handle(DefaultRpcHeartbeatFactory.java:101)
    at com.weibo.api.motan.transport.netty.NettyChannelHandler.processRequest(NettyChannelHandler.java:137)
    at com.weibo.api.motan.transport.netty.NettyChannelHandler.access$000(NettyChannelHandler.java:43)
    at com.weibo.api.motan.transport.netty.NettyChannelHandler$1.run(NettyChannelHandler.java:112)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: Tom
    at GreetService.sayHello(JerryGreetService.java:32)
    ... 25 more
```

而实际上，这是一个合理的业务异常，日志应该打`INFO`级别或者`DEBUG`级别，而不应该打`ERROR`级别，更不适合打一个很长的异常栈。（想像一下一个有几万的QPS的服务处理的都是这类请求，这个服务将会被打日志打死）

经定位，这个问题是由 #501 这一个PR引入的，问题代码是

```java
try {
    Object value = method.invoke(proxyImpl, request.getArguments());
    response.setValue(value);
} catch (Exception e) {
    if (e.getCause() != null) {
        response.setException(new MotanBizException("provider call process error", e.getCause()));
    } else {
        response.setException(new MotanBizException("provider call process error", e));
    }
    // 问题在这儿，它对所有异常都打了ERROR日志
    LoggerUtil.error("Exception caught when during method invocation. request:" + request.toString(), e);
} catch (Throwable t) {
    if (t.getCause() != null) {
        response.setException(new MotanServiceException("provider has encountered a fatal error!", t.getCause()));
    } else {
        response.setException(new MotanServiceException("provider has encountered a fatal error!", t));
    }
    LoggerUtil.error("Exception caught when during method invocation. request:" + request.toString(), t);
}
```

**Comment by rayzhang0603** [comment]
@xnslong 这里有两个问题，1、如果是合理的业务异常，server端需不需要知道发生过异常。2、如果是非合理的业务异常，server端需不需要知道异常栈定位问题。

我觉得这个地方可以针对接口方法中显示声明的异常（或子类），打印warn信息，但不打印异常栈；非接口声明的异常，打印error信息，并打印异常栈

你觉得是否合理？

ps: 貌似很多方法都有非业务异常的声明，例如IOException或者Exception之类的声明

**Comment by xnslong** [comment]
@rayzhang0603 感谢你的回复，你的意思我已经理解，总体上是异常能分成两类：

* 合理的业务异常
* 其它异常

我认为这个划分没有问题，而且这两类异常应该区别对待，做不同处理。但是有2个问题：

* 怎么界定一个异常是合理的业务异常，还是意外的异常？
* 面对一个异常（比如是合理的业务异常），怎么知道应该怎么处理？是只打一条信息日志，还是打一个异常栈，还是打一个统计信息之类的，还是把相应的异常信息发送到一个分析系统？

我觉得[Spring MVC的异常处理机制](https://docs.spring.io/spring/docs/current/spring-framework-reference/web.html#mvc-ann-exceptionhandler)我们可能可以借鉴。它的整体思想是**让用户自己决定怎么给异常分类和处理**：

* 凡是用户关心的异常，用户可以定义`ExceptionHandler`使用自定义的方式进行处理；
* 用户不关心的异常，不定义相应的`ExceptionHandler`处理，则使用框架的默认处理方式统一处理。

比如：

```java
// 此处定义了MyBizException异常的处理方式，所有这类异常都按照用户指定的方式来处理。
@ExceptionHandler(MyBizException.class)
public Object handleBizException(HttpServletRequest request, MyBizException e) {
    log.info("processing request {} failed: {}", request.getPath(), e.getMessage());
    // only print message, not print exception stack
    return Response.error(e.code(), e.getMessage());
}

// 其它异常则按照框架的默认处理方式来处理。比如向用户发送`4xx`或者`5xx`，打相应的异常栈等。
```

我们的[`Filter`](motan/motan-core/src/main/java/com/weibo/api/motan/filter/Filter.java)其实很适合做这个事情；这样的话，每个使用的人都可以根据自己的诉求，来做合适的处理。

**Comment by rayzhang0603** [comment]
@xnslong 为了减少用户的理解与使用成本，我们内部讨论决定，对于抛出接口方法中明确声明的异常及其子类，可以看作预期行为，不再打印error级别和异常栈，改为info级别；对于接口方法中没有声明的异常，维持error级别和异常栈打印。

此修改准备在下个release版本中生效。

使用方可以通过修改是否在接口进行异常声明，来决定日志打印行为。

**Comment by lhl4546** [comment]
个人觉得服务接口处不宜声明并抛出异常，应统一转换为用返回值表示异常，服务方提供一个全局异常处理切面用于处理意外的异常

**Comment by xnslong** [comment]
@lhl4546 你说的以返回值的方式来返回，这种方式是很好，而且性能一般比抛异常的方式更高。其实go里面基本废弃了java里的exception的方式，而用的是你说的这种方式

```go
if resp, err := fooService.bar(); err != nil {
    // handle response
}
```

但是要让大家都按这个规定使用，估计有些困难。

* java里面原生不支持多返回值的方式，使用起来比较麻烦，没有原生的那种抛异常的方式那么直观。
* 有些工程已经使用了抛异常的方式，要迁移的话，成本会很高，应该不愿意迁移。

所以基于以上的问题，我们这儿应该还是需要保留RPC接口抛异常的方式，并对它做很好的维护。
