### ISSUE TITLE
使用Consul作为注册中心，如何启用TTL

### ISSUE THREAD

**Issue by lordzoucl** [weibocom/motan#73]
1.当使用Consul作为注册中心时，如何启用TTL以及如何修改默认group？
![image](https://cloud.githubusercontent.com/assets/19305539/15321432/f655d29c-1c68-11e6-8c22-9e40568abd6c.png)
2.如何修改默认的group？我尝试做了如下配置：
server:`<motan:registry regProtocol="consul" name="consul" address="127.0.0.1:8500?group=testGroup" check="true" />
<motan:service interface="quickstart.FooService" ref="serviceImpl" export="8002" shareChannel="true" group="testGroup"/>`
client:`<motan:registry regProtocol="consul" name="consul" address="127.0.0.1:8500?group=testGroup"/>
    <motan:referer id="remoteService" interface="quickstart.FooService" group="testGroup"/>`

client堆栈如下：
Exception in thread "main" org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'remoteService': FactoryBean threw exception on object creation; nested exception is com.weibo.api.motan.exception.MotanFrameworkException: error_message: ClusterSupport No service urls for the refer:motan://172.16.69.17:0/testGroup/quickstart.FooService/1.0/referer, registries:[consul://127.0.0.1:8500/com.weibo.api.motan.registry.RegistryService?group=testGroup], status: 404, error_code: 10101,r=
    at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.doGetObjectFromFactoryBean(FactoryBeanRegistrySupport.java:175)
    at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.getObjectFromFactoryBean(FactoryBeanRegistrySupport.java:103)
    at org.springframework.beans.factory.support.AbstractBeanFactory.getObjectForBeanInstance(AbstractBeanFactory.java:1523)
    at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:251)
    at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:194)
    at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:956)
    at quickstart.Client.main(Client.java:12)
Caused by: com.weibo.api.motan.exception.MotanFrameworkException: error_message: ClusterSupport No service urls for the refer:motan://172.16.69.17:0/testGroup/quickstart.FooService/1.0/referer, registries:[consul://127.0.0.1:8500/com.weibo.api.motan.registry.RegistryService?group=testGroup], status: 404, error_code: 10101,r=
    at com.weibo.api.motan.cluster.support.ClusterSupport.init(ClusterSupport.java:102)
    at com.weibo.api.motan.config.handler.SimpleConfigHandler.buildClusterSupport(SimpleConfigHandler.java:55)
    at com.weibo.api.motan.config.RefererConfig.createClusterSupport(RefererConfig.java:184)
    at com.weibo.api.motan.config.RefererConfig.initRef(RefererConfig.java:128)
    at com.weibo.api.motan.config.RefererConfig.getRef(RefererConfig.java:85)
    at com.weibo.api.motan.config.springsupport.RefererConfigBean.getObject(RefererConfigBean.java:41)
    at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.doGetObjectFromFactoryBean(FactoryBeanRegistrySupport.java:168)
    ... 6 more

**Comment by lordzoucl** [comment]
请忽略，我再看一下demo项目
