### ISSUE TITLE
io.netty.channel.socket.nio.NioServerSocketChannel

### ISSUE THREAD

**Issue by dzy5639313** [weibocom/motan#734]
motan版本是1.1.1
项目使用tomcat运行,启动时出现
`at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:351)
 |Context initialization failed
io.netty.channel.ChannelException: Unable to create Channel from class class io.netty.channel.socket.nio.NioServerSocketChannel
  at io.netty.channel.ReflectiveChannelFactory.newChannel(ReflectiveChannelFactory.java:40)
  at io.netty.bootstrap.AbstractBootstrap.initAndRegister(AbstractBootstrap.java:321)
  at io.netty.bootstrap.AbstractBootstrap.doBind(AbstractBootstrap.java:283)
  at io.netty.bootstrap.AbstractBootstrap.bind(AbstractBootstrap.java:279)
  at com.weibo.api.motan.transport.netty4.NettyServer.open(NettyServer.java:100)
  at com.weibo.api.motan.protocol.rpc.DefaultRpcExporter.doInit(DefaultRpcExporter.java:81)
  at com.weibo.api.motan.rpc.AbstractNode.init(AbstractNode.java:46)
  at com.weibo.api.motan.protocol.AbstractProtocol.export(AbstractProtocol.java:66)
  at com.weibo.api.motan.protocol.support.ProtocolFilterDecorator.export(ProtocolFilterDecorator.java:58)
  at com.weibo.api.motan.config.handler.SimpleConfigHandler.export(SimpleConfigHandler.java:78)
  at com.weibo.api.motan.config.ServiceConfig.doExport(ServiceConfig.java:211)
  at com.weibo.api.motan.config.ServiceConfig.export(ServiceConfig.java:129)
  at com.weibo.api.motan.config.springsupport.ServiceConfigBean.onApplicationEvent(ServiceConfigBean.java:95)
  at com.weibo.api.motan.config.springsupport.ServiceConfigBean.onApplicationEvent(ServiceConfigBean.java:47)
  at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:166)
  at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:138)
  at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:382)
  at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:336)
  at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:877)
  at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:544)
  at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:444)
  at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:326)
  at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:107)
  at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4728)
  at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5162)
  at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
  at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:725)
  at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:701)
  at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717)
  at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:917)
  at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1701)
  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.reflect.InvocationTargetException: null
  at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
  at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
  at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
  at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
  at io.netty.channel.ReflectiveChannelFactory.newChannel(ReflectiveChannelFactory.java:38)
  ... 35 common frames omitted
Caused by: java.lang.NoSuchMethodError: io.netty.util.internal.MacAddressUtil.defaultMachineId()[B
  at io.netty.channel.DefaultChannelId.<clinit>(DefaultChannelId.java:99)
  at io.netty.channel.AbstractChannel.newId(AbstractChannel.java:111)
  at io.netty.channel.AbstractChannel.<init>(AbstractChannel.java:83)
  at io.netty.channel.nio.AbstractNioChannel.<init>(AbstractNioChannel.java:84)
  at io.netty.channel.nio.AbstractNioMessageChannel.<init>(AbstractNioMessageChannel.java:42)
  at io.netty.channel.socket.nio.NioServerSocketChannel.<init>(NioServerSocketChannel.java:86)
  at io.netty.channel.socket.nio.NioServerSocketChannel.<init>(NioServerSocketChannel.java:72)`
有没有哪位大神帮忙看看?

**Comment by rayzhang0603** [comment]
看异常可能是netty的版本冲突了，可以确认一下使用的netty版本。如果使用netty4的话，可以使用4.1.16.Final这个版本
