### ISSUE TITLE
motan-demo模块里面motan-server测试类启动报错，Caused by: java.lang.ClassNotFoundException: org.apache.log4j.Level

### ISSUE THREAD

**Issue by freezehe** [weibocom/motan#735]
我在idea上check out出源码，测了下motan-demo模块里面的server模块，启动就报这个错，我怀疑是jar包问题，然后在demo的父pom引用了log4j，还是报错。

Failed to instantiate SLF4J LoggerFactory
Reported exception:
java.lang.NoClassDefFoundError: org/apache/log4j/Level
	at org.slf4j.LoggerFactory.bind(LoggerFactory.java:141)
	at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:120)
	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:331)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:283)
	at org.apache.commons.logging.impl.SLF4JLogFactory.getInstance(SLF4JLogFactory.java:155)
	at org.apache.commons.logging.impl.SLF4JLogFactory.getInstance(SLF4JLogFactory.java:132)
	at org.apache.commons.logging.LogFactory.getLog(LogFactory.java:273)
	at org.springframework.boot.SpringApplication.<init>(SpringApplication.java:160)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:957)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:946)
	at com.weibo.motan.demo.springboot.SpringBootRpcServerDemo.main(SpringBootRpcServerDemo.java:40)
Caused by: java.lang.ClassNotFoundException: org.apache.log4j.Level
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 11 more
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/log4j/Level
	at org.slf4j.LoggerFactory.bind(LoggerFactory.java:141)
	at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:120)
	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:331)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:283)
	at org.apache.commons.logging.impl.SLF4JLogFactory.getInstance(SLF4JLogFactory.java:155)
	at org.apache.commons.logging.impl.SLF4JLogFactory.getInstance(SLF4JLogFactory.java:132)
	at org.apache.commons.logging.LogFactory.getLog(LogFactory.java:273)
	at org.springframework.boot.SpringApplication.<init>(SpringApplication.java:160)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:957)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:946)
	at com.weibo.motan.demo.springboot.SpringBootRpcServerDemo.main(SpringBootRpcServerDemo.java:40)
Caused by: java.lang.ClassNotFoundException: org.apache.log4j.Level
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 11 more

**Comment by rayzhang0603** [comment]
@freezehe 只加上log4j的依赖就可以了，加完pom之后在ide里reimport一下就可以

```xml
        <dependency>
            <groupId>log4j</groupId>
            <artifactId>log4j</artifactId>
            <version>1.2.14</version>
        </dependency>
```
