### ISSUE TITLE
不要使用springboot的spring-boot-devtools

### ISSUE THREAD

**Issue by 89333367** [weibocom/motan#764]
```
<!-- 引入配置文件 -->
    <context:property-placeholder location="classpath*:application.properties" ignore-unresolvable="true"/>

    <!-- https://github.com/weibocom/motan/wiki/zh_configuration -->
    <motan:protocol name="motan" lazyInit="true" maxContentLength="104857600"/>
    <motan:registry name="my_zookeeper" regProtocol="zookeeper" address="${hbase.zookeeper.quorum}" check="false"/>
```
这样配置就不行
```
address="${hbase.zookeeper.quorum}" 
```
必须要这样才行
```
address="cdh0:2181,cdh1:2181,cdh2:2181"
```
否则就报错
```
Caused by: com.weibo.api.motan.exception.MotanFrameworkException: error_message: Create registry false for url:zookeeper://${hbase.zookeeper.quorum}:0/com.weibo.api.motan.registry.RegistryService?group=default_rpc, status: 500, error_code: 20004,r=null
	at com.weibo.api.motan.registry.support.AbstractRegistryFactory.getRegistry(AbstractRegistryFactory.java:63)
	at com.weibo.api.motan.cluster.support.ClusterSupport.getRegistry(ClusterSupport.java:132)
	at com.weibo.api.motan.cluster.support.ClusterSupport.init(ClusterSupport.java:89)
	at com.weibo.api.motan.config.handler.SimpleConfigHandler.buildClusterSupport(SimpleConfigHandler.java:54)
	at com.weibo.api.motan.config.RefererConfig.createClusterSupport(RefererConfig.java:196)
	at com.weibo.api.motan.config.RefererConfig.initRef(RefererConfig.java:138)
	at com.weibo.api.motan.config.RefererConfig.getRef(RefererConfig.java:94)
	at com.weibo.api.motan.config.springsupport.RefererConfigBean.getObject(RefererConfigBean.java:44)
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.doGetObjectFromFactoryBean(FactoryBeanRegistrySupport.java:171)
	... 39 more
Caused by: org.I0Itec.zkclient.exception.ZkException: Unable to connect to ${hbase.zookeeper.quorum}
	at org.I0Itec.zkclient.ZkConnection.connect(ZkConnection.java:66)
	at org.I0Itec.zkclient.ZkClient.connect(ZkClient.java:876)
	at org.I0Itec.zkclient.ZkClient.<init>(ZkClient.java:98)
	at org.I0Itec.zkclient.ZkClient.<init>(ZkClient.java:92)
	at org.I0Itec.zkclient.ZkClient.<init>(ZkClient.java:80)
	at com.weibo.api.motan.registry.zookeeper.ZookeeperRegistryFactory.createRegistry(ZookeeperRegistryFactory.java:38)
	at com.weibo.api.motan.registry.support.AbstractRegistryFactory.getRegistry(AbstractRegistryFactory.java:56)
	... 47 more
Caused by: java.net.UnknownHostException: ${hbase.zookeeper.quorum}
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
	at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928)
	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323)
	at java.net.InetAddress.getAllByName0(InetAddress.java:1276)
	at java.net.InetAddress.getAllByName(InetAddress.java:1192)
	at java.net.InetAddress.getAllByName(InetAddress.java:1126)
	at org.apache.zookeeper.client.StaticHostProvider.<init>(StaticHostProvider.java:61)
	at org.apache.zookeeper.ZooKeeper.<init>(ZooKeeper.java:446)
	at org.apache.zookeeper.ZooKeeper.<init>(ZooKeeper.java:380)
	at org.I0Itec.zkclient.ZkConnection.connect(ZkConnection.java:64)
	... 53 more
```

**Comment by 89333367** [comment]
> 看报错是`${hbase.zookeeper.quorum}`这个占位符没有被替换。可以调试一下spring的placeholder处理的部分（PropertyPlaceholderConfigurer.processProperties()）看看有没有什么问题。

没有问题，在同一项目，还有其他bean，可以获得正确信息

```
<context:property-placeholder location="classpath*:application.properties" ignore-unresolvable="true"/>

    <bean id="kafkaProducerFactory" class="org.springframework.kafka.core.DefaultKafkaProducerFactory">
        <constructor-arg>
            <map>
                <entry key="bootstrap.servers" value="${spring.kafka.bootstrap-servers}"/>
                <entry key="key.serializer" value="${spring.kafka.producer.key-serializer}"/>
                <entry key="value.serializer" value="${spring.kafka.producer.value-serializer}"/>
            </map>
        </constructor-arg>
    </bean>
```
直接就能正确替换。唯独motan:registry不能替换

**Comment by rayzhang0603** [comment]
建议调试一下`${hbase.zookeeper.quorum}`这个placeholder的处理过程，看看有没有什么线索。例如PropertyPlaceholderConfigurer是否处理了对应的RegistryConfig对象，是否在对应的properties中查询到了`${hbase.zookeeper.quorum}`的对应值，是否进行了替换等。

**Comment by 89333367** [comment]
> 建议调试一下`${hbase.zookeeper.quorum}`这个placeholder的处理过程，看看有没有什么线索。例如PropertyPlaceholderConfigurer是否处理了对应的RegistryConfig对象，是否在对应的properties中查询到了`${hbase.zookeeper.quorum}`的对应值，是否进行了替换等。

```
TypedStringValue: value [cdh0:2181,cdh1:2181,cdh2:2181], target type [null]
在判断if (!ObjectUtils.nullSafeEquals(newVal, pv.getValue())) {这句的时候，没有进去
```
不知道怎样调了。跟断点走了一圈。

**Comment by 89333367** [comment]
> 建议调试一下`${hbase.zookeeper.quorum}`这个placeholder的处理过程，看看有没有什么线索。例如PropertyPlaceholderConfigurer是否处理了对应的RegistryConfig对象，是否在对应的properties中查询到了`${hbase.zookeeper.quorum}`的对应值，是否进行了替换等。

我找到问题了。只要注释掉pom.xml中的
```
<!--<dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-devtools</artifactId>
            <scope>runtime</scope>
        </dependency>-->
```
就可以了。奇怪。难道说使用了devtools，那么启动的时候，classpath不是一个？
