### ISSUE TITLE
Error spiName already exist motan, status: 503, error_code: 20001,r=null是怎么回事呢？

### ISSUE THREAD

**Issue by 89333367** [weibocom/motan#765]
```
[umltech]INFO 2018-11-15 02:11:24 org.apache.zookeeper.ClientCnxn org.apache.zookeeper.ClientCnxn$SendThread.logStartConnect(ClientCnxn.java:1032) Opening socket connection to server kafka005/172.16.1.5:2181. Will not attempt to authenticate using SASL (unknown error)
[umltech]INFO 2018-11-15 02:11:24 org.apache.zookeeper.ClientCnxn org.apache.zookeeper.ClientCnxn$SendThread.primeConnection(ClientCnxn.java:876) Socket connection established to kafka005/172.16.1.5:2181, initiating session
[umltech]INFO 2018-11-15 02:11:24 org.apache.zookeeper.ClientCnxn org.apache.zookeeper.ClientCnxn$SendThread.onConnected(ClientCnxn.java:1299) Session establishment complete on server kafka005/172.16.1.5:2181, sessionid = 0x35ea04df415da40, negotiated timeout = 60000
[umltech]INFO 2018-11-15 02:11:24 org.I0Itec.zkclient.ZkClient org.I0Itec.zkclient.ZkClient.processStateChanged(ZkClient.java:449) zookeeper state changed (SyncConnected)
[umltech]INFO 2018-11-15 02:11:24 info com.weibo.api.motan.log.DefaultLogService.info(DefaultLogService.java:55) ShutdownHook is initialized
[umltech]INFO 2018-11-15 02:11:24 info com.weibo.api.motan.log.DefaultLogService.info(DefaultLogService.java:55) add resource class com.weibo.api.motan.registry.support.FailbackRegistry$1 to list
[umltech]INFO 2018-11-15 02:11:24 info com.weibo.api.motan.log.DefaultLogService.info(DefaultLogService.java:55) CommandFailbackRegistry init. url: zookeeper://kafka005:2181/com.weibo.api.motan.registry.RegistryService?group=default_rpc
[umltech]INFO 2018-11-15 02:11:24 info com.weibo.api.motan.log.DefaultLogService.info(DefaultLogService.java:55) add resource class com.weibo.api.motan.registry.zookeeper.ZookeeperRegistry to list
[umltech]INFO 2018-11-15 02:11:24 info com.weibo.api.motan.log.DefaultLogService.info(DefaultLogService.java:59) [ZookeeperRegistry] Listener (com.weibo.api.motan.cluster.support.ClusterSupport@3d3abe9) will subscribe to url (motan://172.16.1.13:0/uml.api.bigdata.BigDataNeApi?group=default_rpc) in Registry [zookeeper://kafka005:2181/default_rpc/com.weibo.api.motan.registry.RegistryService/1.0/service]
[umltech]INFO 2018-11-15 02:11:24 info com.weibo.api.motan.log.DefaultLogService.info(DefaultLogService.java:55) CommandFailbackRegistry subscribe. url: motan://172.16.1.13:0/uml.api.bigdata.BigDataNeApi?group=default_rpc
[umltech]INFO 2018-11-15 02:11:24 info com.weibo.api.motan.log.DefaultLogService.info(DefaultLogService.java:55) CommandServiceManager init url:motan://172.16.1.13:0/uml.api.bigdata.BigDataNeApi?singleton=true&retries=3&protocol=motan&refreshTimestamp=1542219084691&id=bigDataNeApi&nodeType=service&version=1.0&requestTimeout=30000&
[umltech]INFO 2018-11-15 02:11:24 info com.weibo.api.motan.log.DefaultLogService.info(DefaultLogService.java:55) [ZookeeperRegistry] subscribe service: path=/motan/default_rpc/uml.api.bigdata.BigDataNeApi/server/172.16.1.13, info=motan://172.16.1.13:0/uml.api.bigdata.BigDataNeApi?singleton=true&retries=3&protocol=motan&refreshTimestamp=1542219084691&id=bigDataNeApi&nodeType=service&version=1.0&requestTimeout=30000&
[umltech]INFO 2018-11-15 02:11:24 info com.weibo.api.motan.log.DefaultLogService.info(DefaultLogService.java:55) [ZookeeperRegistry] subscribe command: path=/motan/default_rpc/command, info=motan://172.16.1.13:0/uml.api.bigdata.BigDataNeApi?singleton=true&retries=3&protocol=motan&refreshTimestamp=1542219084691&id=bigDataNeApi&nodeType=service&version=1.0&requestTimeout=30000&
[umltech]INFO 2018-11-15 02:11:24 info com.weibo.api.motan.log.DefaultLogService.info(DefaultLogService.java:55) CommandFailbackRegistry discover. url: motan://172.16.1.13:0/uml.api.bigdata.BigDataNeApi?group=default_rpc
[umltech]INFO 2018-11-15 02:11:24 info com.weibo.api.motan.log.DefaultLogService.info(DefaultLogService.java:55) CommandFailbackRegistry discover command. commandStr: , rpccommand is null.
[umltech]INFO 2018-11-15 02:11:24 info com.weibo.api.motan.log.DefaultLogService.info(DefaultLogService.java:55) CommandFailbackRegistry discover size: 2
[umltech]INFO 2018-11-15 02:11:24 info com.weibo.api.motan.log.DefaultLogService.info(DefaultLogService.java:59) ClusterSupport config change notify: registry=zookeeper://kafka005:2181/com.weibo.api.motan.registry.RegistryService service=motan://172.16.1.13:0/default_rpc/uml.api.bigdata.BigDataNeApi/1.0/referer urls=[motan://172.16.1.11:8004/default_rpc/uml.api.bigdata.BigDataNeApi/1.0/service,motan://172.16.1.19:8004/default_rpc/uml.api.bigdata.BigDataNeApi/1.0/service]
[umltech]INFO 2018-11-15 02:11:24 info com.weibo.api.motan.log.DefaultLogService.info(DefaultLogService.java:55) refresh weight. weight=
[umltech]INFO 2018-11-15 02:11:24 info com.weibo.api.motan.log.DefaultLogService.info(DefaultLogService.java:55) ignore weightString:
[umltech]ERROR 2018-11-15 02:11:24 error com.weibo.api.motan.log.DefaultLogService.error(DefaultLogService.java:87) com.weibo.api.motan.transport.EndpointFactory: Error load spi class
com.weibo.api.motan.exception.MotanFrameworkException: error_message: com.weibo.api.motan.transport.netty4.NettyEndpointFactory: :Error spiName already exist motan, status: 503, error_code: 20001,r=null
	at com.weibo.api.motan.core.extension.ExtensionLoader.failThrows(ExtensionLoader.java:458)
	at com.weibo.api.motan.core.extension.ExtensionLoader.loadClass(ExtensionLoader.java:353)
	at com.weibo.api.motan.core.extension.ExtensionLoader.loadExtensionClasses(ExtensionLoader.java:332)
	at com.weibo.api.motan.core.extension.ExtensionLoader.loadExtensionClasses(ExtensionLoader.java:161)
	at com.weibo.api.motan.core.extension.ExtensionLoader.checkInit(ExtensionLoader.java:72)
	at com.weibo.api.motan.core.extension.ExtensionLoader.getExtension(ExtensionLoader.java:83)
	at com.weibo.api.motan.protocol.rpc.DefaultRpcReferer.<init>(DefaultRpcReferer.java:40)
	at com.weibo.api.motan.protocol.rpc.DefaultRpcProtocol.createReferer(DefaultRpcProtocol.java:46)
	at com.weibo.api.motan.protocol.AbstractProtocol.refer(AbstractProtocol.java:94)
	at com.weibo.api.motan.protocol.support.ProtocolFilterDecorator.refer(ProtocolFilterDecorator.java:63)
	at com.weibo.api.motan.cluster.support.ClusterSupport.notify(ClusterSupport.java:178)
	at com.weibo.api.motan.registry.support.AbstractRegistry.notify(AbstractRegistry.java:219)
	at com.weibo.api.motan.registry.support.command.CommandFailbackRegistry.doSubscribe(CommandFailbackRegistry.java:51)
	at com.weibo.api.motan.registry.support.AbstractRegistry.subscribe(AbstractRegistry.java:106)
	at com.weibo.api.motan.registry.support.FailbackRegistry.subscribe(FailbackRegistry.java:119)
	at com.weibo.api.motan.cluster.support.ClusterSupport.init(ClusterSupport.java:90)
	at com.weibo.api.motan.config.handler.SimpleConfigHandler.buildClusterSupport(SimpleConfigHandler.java:54)
	at com.weibo.api.motan.config.RefererConfig.createClusterSupport(RefererConfig.java:196)
	at com.weibo.api.motan.config.RefererConfig.initRef(RefererConfig.java:138)
	at com.weibo.api.motan.config.RefererConfig.getRef(RefererConfig.java:94)
	at com.weibo.api.motan.config.springsupport.RefererConfigBean.getObject(RefererConfigBean.java:44)
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.doGetObjectFromFactoryBean(FactoryBeanRegistrySupport.java:168)
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.getObjectFromFactoryBean(FactoryBeanRegistrySupport.java:103)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getObjectForBeanInstance(AbstractBeanFactory.java:1634)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:254)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:208)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.addCandidateEntry(DefaultListableBeanFactory.java:1309)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.findAutowireCandidates(DefaultListableBeanFactory.java:1275)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1101)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1066)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:585)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:88)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:366)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1264)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:553)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:761)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:866)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:542)
	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:443)
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:325)
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:107)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4745)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5207)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:752)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:728)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734)
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:952)
	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1823)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[umltech]INFO 2018-11-15 02:11:24 info com.weibo.api.motan.log.DefaultLogService.info(DefaultLogService.java:55) add resource class com.weibo.api.motan.transport.support.HeartbeatClientEndpointManager$2 to list
[umltech]INFO 2018-11-15 02:11:24 info com.weibo.api.motan.log.DefaultLogService.info(DefaultLogService.java:59) NettyEndpointFactory create client: url=motan://172.16.1.11:8004/uml.api.bigdata.BigDataNeApi?group=default_rpc
[umltech]INFO 2018-11-15 02:11:24 info com.weibo.api.motan.log.DefaultLogService.info(DefaultLogService.java:55) init compress codec
[umltech]INFO 2018-11-15 02:11:24 info com.weibo.api.motan.log.DefaultLogService.info(DefaultLogService.java:55) init nettyclient. url:172.16.1.11-uml.api.bigdata.BigDataNeApi, use codec:DefaultRpcCodec
[umltech]INFO 2018-11-15 02:11:24 info com.weibo.api.motan.log.DefaultLogService.info(DefaultLogService.java:59) NettyClient finish Open: url=motan://172.16.1.11:8004/uml.api.bigdata.BigDataNeApi?group=default_rpc
[umltech]INFO 2018-11-15 02:11:24 info com.weibo.api.motan.log.DefaultLogService.info(DefaultLogService.java:55) add resource class com.weibo.api.motan.util.StatsUtil$2 to list

```

**Comment by rayzhang0603** [comment]
应该是同时依赖了motan-transport-netty和motan-transport-netty4这两个jar包。可以把motan-transport-netty去掉，只引入一个motan-transport-netty4就可以了。

**Comment by 89333367** [comment]
> 应该是同时依赖了motan-transport-netty和motan-transport-netty4这两个jar包。可以把motan-transport-netty去掉，只引入一个motan-transport-netty4就可以了。

嗯，是这样的，去掉一个就好了
