### ISSUE TITLE
在spark项目中使用motan遇到了下面异常，怎么解决？

### ISSUE THREAD

**Issue by 89333367** [weibocom/motan#774]
项目是spark streaming项目，开启了18个线程工作，启动遇到下面异常
```

Logged in as: dr.who 
Logs for container_e169_1537152978270_0893_01_000015
ResourceManager
RM Home
NodeManager
Tools
2018-11-27 09:12:13,348 [Executor task launch worker-0] ERROR [org.apache.spark.executor.Executor] - Exception in task 17.0 in stage 0.0 (TID 17)
java.lang.ExceptionInInitializerError
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at java.lang.invoke.SerializedLambda.readResolve(SerializedLambda.java:230)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at java.io.ObjectStreamClass.invokeReadResolve(ObjectStreamClass.java:1148)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1817)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1353)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2018)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1942)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1808)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1353)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2018)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1942)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1808)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1353)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2018)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1942)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1808)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1353)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:373)
	at scala.collection.immutable.$colon$colon.readObject(List.scala:362)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1058)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1909)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1808)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1353)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2018)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1942)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1808)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1353)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2018)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1942)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1808)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1353)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:373)
	at org.apache.spark.serializer.JavaDeserializationStream.readObject(JavaSerializer.scala:76)
	at org.apache.spark.serializer.JavaSerializerInstance.deserialize(JavaSerializer.scala:115)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:64)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:41)
	at org.apache.spark.scheduler.Task.run(Task.scala:89)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:229)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'kafkaService': FactoryBean threw exception on object creation; nested exception is com.weibo.api.motan.exception.MotanFrameworkException: error_message: [ZookeeperRegistry] false to subscribe motan://192.168.11.156:0/sunyu.example.motan.api.KafkaService?group=common from zookeeper://cdh0:2181/com.weibo.api.motan.registry.RegistryService?group=default_rpc, status: 503, error_code: 20001,r=null
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.doGetObjectFromFactoryBean(FactoryBeanRegistrySupport.java:178)
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.getObjectFromFactoryBean(FactoryBeanRegistrySupport.java:101)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getObjectForBeanInstance(AbstractBeanFactory.java:1647)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.getObjectForBeanInstance(AbstractAutowireCapableBeanFactory.java:1216)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:257)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:224)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveNamedBean(DefaultListableBeanFactory.java:1114)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveBean(DefaultListableBeanFactory.java:407)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:341)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:335)
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1101)
	at uml.bigdata.stream.App.<clinit>(App.java:49)
	... 52 more
Caused by: com.weibo.api.motan.exception.MotanFrameworkException: error_message: [ZookeeperRegistry] false to subscribe motan://192.168.11.156:0/sunyu.example.motan.api.KafkaService?group=common from zookeeper://cdh0:2181/com.weibo.api.motan.registry.RegistryService?group=default_rpc, status: 503, error_code: 20001,r=null
	at com.weibo.api.motan.registry.support.FailbackRegistry.subscribe(FailbackRegistry.java:126)
	at com.weibo.api.motan.cluster.support.ClusterSupport.init(ClusterSupport.java:90)
	at com.weibo.api.motan.config.handler.SimpleConfigHandler.buildClusterSupport(SimpleConfigHandler.java:54)
	at com.weibo.api.motan.config.RefererConfig.createClusterSupport(RefererConfig.java:196)
	at com.weibo.api.motan.config.RefererConfig.initRef(RefererConfig.java:138)
	at com.weibo.api.motan.config.RefererConfig.getRef(RefererConfig.java:94)
	at com.weibo.api.motan.config.springsupport.RefererConfigBean.getObject(RefererConfigBean.java:44)
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.doGetObjectFromFactoryBean(FactoryBeanRegistrySupport.java:171)
	... 63 more
Caused by: com.weibo.api.motan.exception.MotanFrameworkException: error_message: Failed to subscribe motan://192.168.11.156:0/sunyu.example.motan.api.KafkaService?group=common to zookeeper(zookeeper://cdh0:2181/com.weibo.api.motan.registry.RegistryService?group=default_rpc), cause: org.apache.zookeeper.KeeperException$NodeExistsException: KeeperErrorCode = NodeExists for /motan/common/sunyu.example.motan.api.KafkaService/client/192.168.11.156, status: 503, error_code: 20001,r=null
	at com.weibo.api.motan.registry.zookeeper.ZookeeperRegistry.subscribeService(ZookeeperRegistry.java:105)
	at com.weibo.api.motan.registry.support.command.CommandFailbackRegistry.doSubscribe(CommandFailbackRegistry.java:46)
	at com.weibo.api.motan.registry.support.AbstractRegistry.subscribe(AbstractRegistry.java:106)
	at com.weibo.api.motan.registry.support.FailbackRegistry.subscribe(FailbackRegistry.java:119)
	... 70 more
Caused by: org.I0Itec.zkclient.exception.ZkNodeExistsException: org.apache.zookeeper.KeeperException$NodeExistsException: KeeperErrorCode = NodeExists for /motan/common/sunyu.example.motan.api.KafkaService/client/192.168.11.156
	at org.I0Itec.zkclient.exception.ZkException.create(ZkException.java:55)
	at org.I0Itec.zkclient.ZkClient.retryUntilConnected(ZkClient.java:995)
	at org.I0Itec.zkclient.ZkClient.create(ZkClient.java:526)
	at org.I0Itec.zkclient.ZkClient.create(ZkClient.java:497)
	at org.I0Itec.zkclient.ZkClient.createEphemeral(ZkClient.java:550)
	at com.weibo.api.motan.registry.zookeeper.ZookeeperRegistry.createNode(ZookeeperRegistry.java:335)
	at com.weibo.api.motan.registry.zookeeper.ZookeeperRegistry.subscribeService(ZookeeperRegistry.java:99)
	... 73 more
Caused by: org.apache.zookeeper.KeeperException$NodeExistsException: KeeperErrorCode = NodeExists for /motan/common/sunyu.example.motan.api.KafkaService/client/192.168.11.156
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:119)
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:51)
	at org.apache.zookeeper.ZooKeeper.create(ZooKeeper.java:783)
	at org.I0Itec.zkclient.ZkConnection.create(ZkConnection.java:99)
	at org.I0Itec.zkclient.ZkClient$3.call(ZkClient.java:529)
	at org.I0Itec.zkclient.ZkClient$3.call(ZkClient.java:526)
	at org.I0Itec.zkclient.ZkClient.retryUntilConnected(ZkClient.java:985)
	... 78 more
2018-11-27 09:12:13,387 [Executor task launch worker-0] ERROR [org.apache.spark.util.SparkUncaughtExceptionHandler] - Uncaught exception in thread Thread[Executor task launch worker-0,5,main]
java.lang.ExceptionInInitializerError
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at java.lang.invoke.SerializedLambda.readResolve(SerializedLambda.java:230)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at java.io.ObjectStreamClass.invokeReadResolve(ObjectStreamClass.java:1148)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1817)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1353)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2018)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1942)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1808)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1353)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2018)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1942)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1808)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1353)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2018)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1942)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1808)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1353)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:373)
	at scala.collection.immutable.$colon$colon.readObject(List.scala:362)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1058)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1909)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1808)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1353)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2018)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1942)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1808)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1353)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2018)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1942)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1808)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1353)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:373)
	at org.apache.spark.serializer.JavaDeserializationStream.readObject(JavaSerializer.scala:76)
	at org.apache.spark.serializer.JavaSerializerInstance.deserialize(JavaSerializer.scala:115)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:64)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:41)
	at org.apache.spark.scheduler.Task.run(Task.scala:89)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:229)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'kafkaService': FactoryBean threw exception on object creation; nested exception is com.weibo.api.motan.exception.MotanFrameworkException: error_message: [ZookeeperRegistry] false to subscribe motan://192.168.11.156:0/sunyu.example.motan.api.KafkaService?group=common from zookeeper://cdh0:2181/com.weibo.api.motan.registry.RegistryService?group=default_rpc, status: 503, error_code: 20001,r=null
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.doGetObjectFromFactoryBean(FactoryBeanRegistrySupport.java:178)
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.getObjectFromFactoryBean(FactoryBeanRegistrySupport.java:101)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getObjectForBeanInstance(AbstractBeanFactory.java:1647)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.getObjectForBeanInstance(AbstractAutowireCapableBeanFactory.java:1216)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:257)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:224)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveNamedBean(DefaultListableBeanFactory.java:1114)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveBean(DefaultListableBeanFactory.java:407)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:341)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:335)
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1101)
	at uml.bigdata.stream.App.<clinit>(App.java:49)
	... 52 more
Caused by: com.weibo.api.motan.exception.MotanFrameworkException: error_message: [ZookeeperRegistry] false to subscribe motan://192.168.11.156:0/sunyu.example.motan.api.KafkaService?group=common from zookeeper://cdh0:2181/com.weibo.api.motan.registry.RegistryService?group=default_rpc, status: 503, error_code: 20001,r=null
	at com.weibo.api.motan.registry.support.FailbackRegistry.subscribe(FailbackRegistry.java:126)
	at com.weibo.api.motan.cluster.support.ClusterSupport.init(ClusterSupport.java:90)
	at com.weibo.api.motan.config.handler.SimpleConfigHandler.buildClusterSupport(SimpleConfigHandler.java:54)
	at com.weibo.api.motan.config.RefererConfig.createClusterSupport(RefererConfig.java:196)
	at com.weibo.api.motan.config.RefererConfig.initRef(RefererConfig.java:138)
	at com.weibo.api.motan.config.RefererConfig.getRef(RefererConfig.java:94)
	at com.weibo.api.motan.config.springsupport.RefererConfigBean.getObject(RefererConfigBean.java:44)
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.doGetObjectFromFactoryBean(FactoryBeanRegistrySupport.java:171)
	... 63 more
Caused by: com.weibo.api.motan.exception.MotanFrameworkException: error_message: Failed to subscribe motan://192.168.11.156:0/sunyu.example.motan.api.KafkaService?group=common to zookeeper(zookeeper://cdh0:2181/com.weibo.api.motan.registry.RegistryService?group=default_rpc), cause: org.apache.zookeeper.KeeperException$NodeExistsException: KeeperErrorCode = NodeExists for /motan/common/sunyu.example.motan.api.KafkaService/client/192.168.11.156, status: 503, error_code: 20001,r=null
	at com.weibo.api.motan.registry.zookeeper.ZookeeperRegistry.subscribeService(ZookeeperRegistry.java:105)
	at com.weibo.api.motan.registry.support.command.CommandFailbackRegistry.doSubscribe(CommandFailbackRegistry.java:46)
	at com.weibo.api.motan.registry.support.AbstractRegistry.subscribe(AbstractRegistry.java:106)
	at com.weibo.api.motan.registry.support.FailbackRegistry.subscribe(FailbackRegistry.java:119)
	... 70 more
Caused by: org.I0Itec.zkclient.exception.ZkNodeExistsException: org.apache.zookeeper.KeeperException$NodeExistsException: KeeperErrorCode = NodeExists for /motan/common/sunyu.example.motan.api.KafkaService/client/192.168.11.156
	at org.I0Itec.zkclient.exception.ZkException.create(ZkException.java:55)
	at org.I0Itec.zkclient.ZkClient.retryUntilConnected(ZkClient.java:995)
	at org.I0Itec.zkclient.ZkClient.create(ZkClient.java:526)
	at org.I0Itec.zkclient.ZkClient.create(ZkClient.java:497)
	at org.I0Itec.zkclient.ZkClient.createEphemeral(ZkClient.java:550)
	at com.weibo.api.motan.registry.zookeeper.ZookeeperRegistry.createNode(ZookeeperRegistry.java:335)
	at com.weibo.api.motan.registry.zookeeper.ZookeeperRegistry.subscribeService(ZookeeperRegistry.java:99)
	... 73 more
Caused by: org.apache.zookeeper.KeeperException$NodeExistsException: KeeperErrorCode = NodeExists for /motan/common/sunyu.example.motan.api.KafkaService/client/192.168.11.156
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:119)
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:51)
	at org.apache.zookeeper.ZooKeeper.create(ZooKeeper.java:783)
	at org.I0Itec.zkclient.ZkConnection.create(ZkConnection.java:99)
	at org.I0Itec.zkclient.ZkClient$3.call(ZkClient.java:529)
	at org.I0Itec.zkclient.ZkClient$3.call(ZkClient.java:526)
	at org.I0Itec.zkclient.ZkClient.retryUntilConnected(ZkClient.java:985)
	... 78 more

```

**Comment by rayzhang0603** [comment]
可能是相同的referer初始化了多次，导致重复注册client节点。

如果18个线程使用的motan client可以只初始化一次，然后不同线程共用应该可以解决这个问题。

这块motan zkRegistry的处理逻辑会优化一下，注册client节点异常不再抛出，将在下一个release版本中fix。 感谢反馈！

**Comment by 89333367** [comment]
> 可能是相同的service初始化了多次，导致重复注册client节点。
> 
> 如果18个线程使用的motan client可以只初始化一次，然后不同线程共用应该可以解决这个问题。
> 
> 这块motan zkRegistry的处理逻辑会优化一下，注册client节点异常不再抛出，将在下一个release版本中fix。 感谢反馈！

嗯，这个没法控制。spark项目，推送到master的时候，他就会按配置，自动分配到不同的机器上了，也有可能相同机器有多个执行者。

**Comment by rayzhang0603** [comment]
可以先试试在registry中设置`registryRetryPeriod=500`，然后把对应的referer 设置'check=false'，看能不能解决。如果同一个节点上并行运行不是很多的时候应该可以临时解决。
