### ISSUE TITLE
java server使用protobuf+motan2协议。client消费出现异常

### ISSUE THREAD

**Issue by back-zhao** [weibocom/motan#848]
异常信息：
Exception in thread "main" com.weibo.api.motan.exception.MotanServiceException: error_message: NettyChannel send request to server Error: url=motan2://10.0.4.40:8002/cloudwise.service.ServerService local=/10.0.4.40:51049 requestId=1639999514468155393 interface=cloudwise.service.ServerService method=testProtobufTrans(java.lang.String,java.util.Map), status: 503, error_code: 10001,r=null
	at com.weibo.api.motan.transport.netty.NettyChannel.request(NettyChannel.java:100)
	
Caused by: com.weibo.api.motan.exception.MotanFrameworkException: error_message: encode error!type:request, cloudwise.service.ServerService.testProtobufTrans(java.lang.String,java.util.Map) requestId=1639999514468155393, origin errmsg:can't serialize class com.cloudwise.service.MotanApiClient$2, status: 503, error_code: 20002,r=null

Caused by: java.lang.IllegalArgumentException: can't serialize class com.cloudwise.service.MotanApiClient$2
	at com.weibo.api.motan.serialize.ProtobufSerialization.serialize(ProtobufSerialization.java:122)

**Comment by rayzhang0603** [comment]
protobuf序列化只能序列化pb对象和基础的数据类型，`com.cloudwise.service.MotanApiClient$2`内部类序列化不了

**Comment by back-zhao** [comment]
请问java server使用motan2+protobuf时。官方文档中PHP、GO等语言的Client可以调用吧。

**Comment by rayzhang0603** [comment]
可以

**Comment by back-zhao** [comment]
好的 谢谢！
