### ISSUE TITLE
Motan2协议下拿到提供者报文，但过程中出现异常。

### ISSUE THREAD

**Issue by back-zhao** [weibocom/motan#851]
虽然拿到报文，但过程中存在异常，过程中出现异常如下：
ignore weightString:
2019-08-05 14:06:28,889 ERROR [error.error()] - com.weibo.api.motan.transport.EndpointFactory: Error load spi class
com.weibo.api.motan.exception.MotanFrameworkException: error_message: com.weibo.api.motan.transport.netty4.NettyEndpointFactory: :Error spiName already exist motan, status: 503, error_code: 20001,r=null
	at com.weibo.api.motan.core.extension.ExtensionLoader.failThrows(ExtensionLoader.java:458)
	at com.weibo.api.motan.core.extension.ExtensionLoader.loadClass(ExtensionLoader.java:353)
	at com.weibo.api.motan.core.extension.ExtensionLoader.loadExtensionClasses(ExtensionLoader.java:332)
	at com.weibo.api.motan.core.extension.ExtensionLoader.loadExtensionClasses(ExtensionLoader.java:161)
	at com.weibo.api.motan.core.extension.ExtensionLoader.checkInit(ExtensionLoader.java:72)
	at com.weibo.api.motan.core.extension.ExtensionLoader.getExtension(ExtensionLoader.java:83)
	at com.weibo.api.motan.protocol.rpc.DefaultRpcReferer.<init>(DefaultRpcReferer.java:41)
	at com.weibo.api.motan.protocol.v2motan.MotanV2Protocol$V2RpcReferer.<init>(MotanV2Protocol.java:74)
	at com.weibo.api.motan.protocol.v2motan.MotanV2Protocol.createReferer(MotanV2Protocol.java:55)
	at com.weibo.api.motan.protocol.AbstractProtocol.refer(AbstractProtocol.java:94)
	at com.weibo.api.motan.protocol.support.ProtocolFilterDecorator.refer(ProtocolFilterDecorator.java:63)
	at com.weibo.api.motan.cluster.support.ClusterSupport.notify(ClusterSupport.java:178)
	at com.weibo.api.motan.registry.support.AbstractRegistry.notify(AbstractRegistry.java:216)
	at com.weibo.api.motan.registry.support.command.CommandFailbackRegistry.doSubscribe(CommandFailbackRegistry.java:51)
	at com.weibo.api.motan.registry.support.AbstractRegistry.subscribe(AbstractRegistry.java:105)
	at com.weibo.api.motan.registry.support.FailbackRegistry.subscribe(FailbackRegistry.java:119)
	at com.weibo.api.motan.cluster.support.ClusterSupport.init(ClusterSupport.java:90)
	at com.weibo.api.motan.config.handler.SimpleConfigHandler.buildClusterSupport(SimpleConfigHandler.java:54)
	at com.weibo.api.motan.config.RefererConfig.createClusterSupport(RefererConfig.java:196)
	at com.weibo.api.motan.config.RefererConfig.initRef(RefererConfig.java:138)
	at com.weibo.api.motan.config.RefererConfig.getRef(RefererConfig.java:94)
	at com.cloudwise.beanfactory.MotanReferAutoConfig.lambda$start$0(MotanReferAutoConfig.java:58)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at com.cloudwise.beanfactory.MotanReferAutoConfig.start(MotanReferAutoConfig.java:36)
	at com.cloudwise.ClientLatch.main(ClientLatch.java:20)

**Comment by rayzhang0603** [comment]
`com.weibo.api.motan.transport.EndpointFactory: Error load spi class`，`Error spiName already exist motan`

看异常应该是同时引用了motan-transport-netty和motan-transport-netty4两个模块，这两个模块是二选一的，去掉一个就可以了

**Comment by back-zhao** [comment]
确实如此，谢谢回答。上次手动切换流量失效问题出在ZookeeperRegistryFactory类createInnerZkClient()中实例化过程没有指定序列化方式。修改后生效。你这边可以看下
