### ISSUE TITLE
下面这个异常编码不对？

### ISSUE THREAD

**Issue by tailong2016** [weibocom/motan#852]
7300 local=/10.xx.199.xxx:11845 event=UpstreamChannelStateEvent
[2019-08-09 19:50:04.742] ERROR [New I/O server worker #1-22] error - NettyChannelHandler exceptionCaught: remote=/10.xx.199.xxx:47300 local=/10.xx.199.xxx:11845 event=com.weibo.api.motan.exception.MotanFrameworkException: error_message: NettyDecoder transport header not support, type: 18501, status: 503, error_code: 20001,r=null
com.weibo.api.motan.exception.MotanFrameworkException: error_message: NettyDecoder transport header not support, type: 18501, status: 503, error_code: 20001,r=null
        at com.weibo.api.motan.transport.netty.NettyDecoder.decode(NettyDecoder.java:67)
        at org.jboss.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:282)
        at org.jboss.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:216)
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:274)
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:261)
        at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:349)
        at org.jboss.netty.channel.socket.nio.NioWorker.processSelectedKeys(NioWorker.java:280)
        at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:200)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

**Comment by rayzhang0603** [comment]
从异常上看是client端与server端使用的协议不一致，可以检查一下两端protocol的配置
