### ISSUE TITLE
服务注册成功，但客户端请求报错

### ISSUE THREAD

**Issue by zazcoder** [weibocom/motan#856]
客户端请求报异常：
java.lang.NoSuchMethodError: com.weibo.api.motan.util.MotanFrameworkUtil.logEvent(Lcom/weibo/api/motan/rpc/Request;Ljava/lang/String;)V
        at com.weibo.api.motan.transport.netty.NettyClient.request(NettyClient.java:152)
        at com.weibo.api.motan.transport.netty.NettyClient.request(NettyClient.java:108)
        at com.weibo.api.motan.protocol.rpc.DefaultRpcReferer.doCall(DefaultRpcReferer.java:52)
        at com.weibo.api.motan.rpc.AbstractReferer.call(AbstractReferer.java:64)
        at com.weibo.api.motan.cluster.ha.FailoverHaStrategy.call(FailoverHaStrategy.java:74)
        at com.weibo.api.motan.cluster.support.ClusterSpi.call(ClusterSpi.java:73)
        at com.weibo.api.motan.proxy.AbstractRefererHandler.invokeRequest(AbstractRefererHandler.java:77)
        at com.weibo.api.motan.proxy.RefererInvocationHandler.invoke(RefererInvocationHandler.java:72)
        at com.sun.proxy.$Proxy27.getUser(Unknown Source)
        at com.ruyi.core.interceptor.UserInterceptor.intercept(UserInterceptor.java:59

**Comment by rayzhang0603** [comment]
应该是版本兼容问题，motan-core和motan-transport-netty(或者motan-transport-netty4)使用相同的版本号应该就可以了

**Comment by zazcoder** [comment]
> 应该是版本兼容问题，motan-core和motan-transport-netty(或者motan-transport-netty4)使用相同的版本号应该就可以了

感谢回答。我把版本号统一了，然后把线上服务器重装才解决这个问题，单纯的统一所有应用的版本号直接更新还是会报这个错误。这个错误是我从1.1.5 升级到 1.1.6 遇到的，之前从1.1.4 升级到 1.1.5 没遇到过这个问题，不知道是否与本次升级到1.1.6有关。这个问题困扰了我好几天，我排查了各方面问题都无法解决。

**Comment by rayzhang0603** [comment]
1.1.6中motan-core的MotanFrameworkUtil中增加了一个方法，如果运行环境中还存在低版本的motan-core包就会出现这个问题。

可以通过pom查看一下motan-core是否存在依赖冲突，确保项目打包后motan相关的包只有1.1.6版本的包就可以了。
