### ISSUE TITLE
Motan2+Simple PHPClient调用JavaServer 接口参数问题

### ISSUE THREAD

**Issue by back-zhao** [weibocom/motan#868]
当接口入参定义为多个简单数据类型，PHPClient 调用后，Server端Simple序列化类再解析第二个参数开始抛异常，入参改为一个参数（String）后成功调用。Motan2+Simple模式接口只支持一个参数么？

**Comment by back-zhao** [comment]
版本：1.1.6.多个参数异常如下：
2019-10-15 11:28:17.038 [NettyServer-10.0.2.50:8000-1-thread-1] ERROR error.(:) - NettyChannelHandler processRequest fail! request:requestId=63 interface=com.xxxx.xxx.service.rpc.ILogSearchService method=queryLogs(long,long,long,java.lang.String,java.lang.String)
java.nio.BufferUnderflowException: null
	at java.nio.Buffer.nextGetIndex(Buffer.java:500) ~[?:1.8.0_152]
	at java.nio.HeapByteBuffer.get(HeapByteBuffer.java:135) ~[?:1.8.0_152]
	at com.weibo.api.motan.protocol.v2motan.GrowableByteBuffer.get(GrowableByteBuffer.java:139) ~[motan-core-1.1.6.jar:?]
	at com.weibo.api.motan.serialize.SimpleSerialization.deserialize(SimpleSerialization.java:204) ~[motan-core-1.1.6.jar:?]
	at com.weibo.api.motan.serialize.SimpleSerialization.deserializeMulti(SimpleSerialization.java:307) ~[motan-core-1.1.6.jar:?]
	at com.weibo.api.motan.serialize.DeserializableObject.deserializeMulti(DeserializableObject.java:44) ~[motan-core-1.1.6.jar:?]
	at com.weibo.api.motan.transport.ProviderMessageRouter.processLazyDeserialize(ProviderMessageRouter.java:111) ~[motan-core-1.1.6.jar:?]
	at com.weibo.api.motan.transport.ProviderMessageRouter.handle(ProviderMessageRouter.java:92) ~[motan-core-1.1.6.jar:?]
	at com.weibo.api.motan.transport.support.DefaultRpcHeartbeatFactory$HeartMessageHandleWrapper.handle(DefaultRpcHeartbeatFactory.java:98) ~[motan-core-1.1.6.jar:?]
	at com.weibo.api.motan.transport.netty4.NettyChannelHandler.processRequest(NettyChannelHandler.java:155) ~[motan-transport-netty4-1.1.6.jar:?]
	at com.weibo.api.motan.transport.netty4.NettyChannelHandler.processMessage(NettyChannelHandler.java:133) ~[motan-transport-netty4-1.1.6.jar:?]
	at com.weibo.api.motan.transport.netty4.NettyChannelHandler.access$000(NettyChannelHandler.java:32) ~[motan-transport-netty4-1.1.6.jar:?]
	at com.weibo.api.motan.transport.netty4.NettyChannelHandler$1.run(NettyChannelHandler.java:73) ~[motan-transport-netty4-1.1.6.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_152]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_152]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]

**Comment by rayzhang0603** [comment]
支持多参数的。

可以看看是不是php client侧没有正确传递多个参数。多参数request样例如下：

            $req = new \Motan\Request("service_name", 'method_name', 'sdfe', 123, 124, ['xxx','yyy']);

php的调用样例可以参考`ClientTest.php`或者`MClientTest.php`
