### ISSUE TITLE
麻烦帮忙看下这个报错，无法调用服务

### ISSUE THREAD

**Issue by zazcoder** [weibocom/motan#925]
java.lang.NullPointerException
        at com.weibo.api.motan.cluster.support.ClusterSupport.getRegistry(ClusterSupport.java:158)
        at com.weibo.api.motan.cluster.support.ClusterSupport.init(ClusterSupport.java:115)
        at com.weibo.api.motan.config.handler.SimpleConfigHandler.buildClusterSupport(SimpleConfigHandler.java:54)
        at com.weibo.api.motan.config.RefererConfig.createClusterSupport(RefererConfig.java:196)
        at com.weibo.api.motan.config.RefererConfig.initRef(RefererConfig.java:138)
        at com.weibo.api.motan.config.RefererConfig.getRef(RefererConfig.java:94)

**Comment by rayzhang0603** [comment]
看样子是没有获取到对应的注册中心spi实现，可以检查一下注册中心的regProtocol配置是否正确

**Comment by zazcoder** [comment]
> 看样子是没有获取到对应的注册中心spi实现，可以检查一下注册中心的regProtocol配置是否正确

问题是 我这边打fatjar 运行有问题， 打war包部署就没问题 太奇怪了，感觉跟打fatjar包的时候解压依赖的jar包有关系，但具体原因不知道

**Comment by rayzhang0603** [comment]
打fatjar时，spi扩展等描述文件需要使用追加模式打包，否则同名文件会覆盖造成扩展无法生效。可以参考https://github.com/weibocom/motan/issues/910

**Comment by zazcoder** [comment]
> 打fatjar时，spi扩展等描述文件需要使用追加模式打包，否则同名文件会覆盖造成扩展无法生效。可以参考#910

感谢
